### ISSUE TITLE
1.6.2 release

### ISSUE THREAD

**Issue by bfontaine** [dtschump/CImg#1]
Hello,

CImg 1.6.2 used to be available at https://downloads.sourceforge.net/cimg/CImg_1.6.2.zip, but it now resolves to a 404 since you left Sourceforge. I wasn’t able to find the release on your new website ([only the 1.6.2_pre](http://cimg.eu/files/)). Is there any way you could post the 1.6.2 release back online somewhere?

Thanks!

**Comment by dtschump** [comment]
The new URL for download CImg releases is : http://cimg.eu/files/

**Comment by bfontaine** [comment]
Yes, but the 1.6.2 release isn’t available here.

**Comment by dtschump** [comment]
So I'm afraid it is lost forever.
Anyway, I've just released the final 1.6.3, which is very close to 1.6.2. I think there is no problem substituting 1.6.2 by 1.6.3 : http://cimg.eu/files/CImg_1.6.3.zip

**Comment by bfontaine** [comment]
Thanks! I will use this.

**Comment by devernay** [comment]
It would be nice to tag the releases in the git.
That way, source distributions are automatically handled by github.
see https://github.com/blog/1547-release-your-software

If you use the release tag "CImg-1.6.3", the sources are available as
https://github.com/dtschump/CImg/archive/CImg-1.6.3.tar.gz
or
https://github.com/dtschump/CImg/archive/CImg-1.6.3.zip

**Comment by dtschump** [comment]
Indeed. Done, thanks for the suggestion.
