### ISSUE TITLE
multithreaded filtering function in CImg

### ISSUE THREAD

**Issue by ghost** [dtschump/CImg#10]
Hello,
I would like to know if there is a simple way to get multithreaded filtering function in CImg. I tried to modify CImg loop macros with openmp pragma instructions without succes...
Best regards,

**Comment by dtschump** [comment]
Most CImg methods are already parallelized using OpenMP directives (at least on recent versions <1 year I'd say). You just have to define 

    #define cimg_use_openmp

to enable it. What function in particular you are interested in ?

**Comment by mrux2** [comment]
Wow how can I have missed it... Thank you very much, and sorry for this inconvenience. 
Best Regards,
