### ISSUE TITLE
Sharpen only one spectrum channel

### ISSUE THREAD

**Issue by afomushkin** [dtschump/CImg#101]
Hi David,
I am processing images using CImg in LAB color space. I want to sharpen only luminance color channel. Is there simple way to do this? Or I need to cut luminance channel to separate image, sharpen that image and than replace luminance channel in source image by new sharpen image?

**Comment by dtschump** [comment]
Something like this could work:

    img.sRGBtoRGB().RGBtoLab();
    img.get_shared_channel(0).sharpen(30);
    img.LabtoRGB().RGBtosRGB();

**Comment by afomushkin** [comment]
Thank you! That's what I need!
