### ISSUE TITLE
[Question] Get image header without load the whole image.

### ISSUE THREAD

**Issue by saedrna** [dtschump/CImg#103]
Hi,

Is it possible to use CImg to get the image header (e.g., width, height, pixel type) without loading the actual data by calling load function?

Thanks,

Han

**Comment by dtschump** [comment]
No, I don't think so.
Maybe a simple `fread()` would do the job in this case, no ?

**Comment by saedrna** [comment]
Problem is that I have to do that for at least jpg, png, tif, exr, so I think a library with unified interface is better.

**Comment by dtschump** [comment]
I see. I don't think CImg will help you reading only the headers.
Maybe you could check the [Magick++](http://www.imagemagick.org/Magick++/) library for that case.

**Comment by saedrna** [comment]
In fact I have used [GDAL](http://www.gdal.org/) for that. The reason I'm looking into CImg first, is because its simplicity, rather than a heavy library.
