### ISSUE TITLE
Correct strategy for plugin that reads video file?

### ISSUE THREAD

**Issue by Meekohi** [dtschump/CImg#105]
I'm writing a plugin to read various video formats a bit faster than the current ffmpeg>pgm>load_img or OpenCV approach. I noticed the strategy in `load_ffmpeg_external` is to have a function on `CImgList::` that creates a list while loading the video, and then the same thing on `CImg::` is just `return CImgList<T>().load_ffmpeg_external(filename).get_append();` which is clever.

My question is: when writing a plugin for loading video, how do I have some of the functions be members of `CImg` and others of `CImgList`? I see `#define cimglist_load_plugin` and `#define cimg_load_plugin`, but don't quite understand how to make them do what I want. Thanks!

For reference, I guess the typical example for just an image is:
```
#ifndef cimg_load_plugin
#define cimg_load_plugin(filename) \
  if (!cimg::strncasecmp(cimg::split_filename(filename),"foo",3)) return load_foo(filename);
#endif
```

**Comment by Meekohi** [comment]
I guess:
`#define cimg_plugin "plugins/load_libav.h"` will dump that header into `CImg::` so maybe I should split the plugin in two files and also do
`#define cimglist_plugin "plugins/load_libav_list.h"`?

**Comment by dtschump** [comment]
Hello Michael,

I've a question first : is there any reasons you don't want to use the current method `CImg<T>::load_video()` with OpenCV enabled ? (`-Dcimg_use_opencv`). This method is reasonably fast (does not use temporary files but memory buffers), quite robust and convenient (allows to read frames by frames in a "streamed" way for instance). As OpenCV is used basically as a wrapper to the ffmpeg library, I was wondering if there is something more needed.

Anyway, plug-ins that need to include their own files are indeed a bit problematic. What we have done so far is just to warn the user he must include some files by himself prior to the inclusion of `CImg.h`.
This warning is put as a message in the heading comments of the plug-in file.

**Comment by Meekohi** [comment]
So, my own experience has been that OpenCV is brutally slow compared with using libav directly -- admittedly this will be a test of whether that proves true or not.

**Comment by dtschump** [comment]
I see. I'd be interested by any faster plug-in to read video frames by the way :)
