### ISSUE TITLE
Documentation for Math Expression Language

### ISSUE THREAD

**Issue by andreyvps** [dtschump/CImg#106]
The math expression strings for the CImg constructor seem really powerful.  Is there a reference for the syntax?

http://cimg.eu/reference/structcimg__library_1_1CImg.html#a166c79d3886a4587c9e7d85ec450a110

I would like to make a pattern that looks like img1 above, except of a specific color, so I can overlay it on top of another image.  Not sure how to do it using repeating values or the math expressions.

I wasn't sure where to ask this question.  If you know of a better channel, I'll forward this there.

**Comment by devernay** [comment]
http://gmic.eu/reference.shtml#section9

**Comment by dtschump** [comment]
The math expression parser is indeed really powerful, and is a kind of hidden cool feature of CImg. You may be also interested by a blog post I wrote a few months ago about it : http://opensource.graphics/image-processing-made-easier-with-a-powerful-math-expression-evaluator/
This is targeted on the G'MIC software, but it uses exactly the CImg parser.

**Comment by andreyvps** [comment]
Thank you!
