### ISSUE TITLE
CImg and ccache

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#108]
ccache is a utility that caches c files to avoid recompilation. It could be useful for CImg (which has long compilation times) but I can't get it to work. For example, if I run the following twice in the examples/ directory
```
ccache g++ -c use_nlmeans.cpp -I.. -o use_nlmeans.o
```
ccache -s reports a cache miss. 
Has anyone managed to find what the problem is? The __TIME__ and __DATE__ macros aren't involved as far as I can see.

**Comment by dtschump** [comment]
A few years ago, I've also tested the pre-compilation of header files in g++. It wasn't improving anything (just generated a huge file, but this didn't speed up compilation afterwards).

**Comment by dahtah** [comment]
OK, duh, the solution was actually pretty simple, it's indeed because of __TIME__ and __DATE__ macros (or actually, cimg_time and cimg_date). With the default behaviour, the output of the preprocessor is different on every call and ccache doesn't recognise the files it's already seen. 
Compiling with -Dcimg_date='""' -Dcimg_time='""' fixes the problem. I'll close the issue but it might be useful to put this in the FAQ or somewhere.
