### ISSUE TITLE
How take screenshot in and put it in CImg?(Windows API)

### ISSUE THREAD

**Issue by XioNOverMazes** [dtschump/CImg#109]
How take screenshot and not saving it to file, load to image data to CImg class ? (in Windows API).
I know how to take screenshot and get HBITMAP , but then how to load it to CImg - i don't know . Help me pls. Thx .

**Comment by dtschump** [comment]
Use method [CImgDisplay::screenshot](http://cimg.eu/reference/structcimg__library_1_1CImgDisplay.html#a42a1e3dcb55e8e905c97aa8563dd5a13) (or http://cimg.eu/reference/structcimg__library_1_1CImgDisplay.html#a1250a5beb364647157b681f707788ca6 )
