### ISSUE TITLE
cimg on windows7

### ISSUE THREAD

**Issue by blackrust** [dtschump/CImg#11]
This is probably a reflection of my unfamiliarity with Windows.  For some reason I'm trying to compile a program using CImg on Windows7.  The errors I get sort of seem like I'm missing some library, but I really have no clue.  Any help would be appreciated.

The first few lines of errors look like this:
In file included from grey.cpp:9:0:
CImg.h: In function 'char* cimg_library::cimg::number_filename(const char*, int, unsigned int, char*)':
CImg.h:144:23: error: 'snprintf' is not a member of 'std'
 #define cimg_snprintf std::snprintf
                       ^
CImg.h:4961:17: note: in expansion of macro 'cimg_snprintf'
       if (*ext) cimg_snprintf(format,1024,"%%s_%%.%ud.%%s",digits);
                 ^
CImg.h:144:23: note: suggested alternative:
 #define cimg_snprintf std::snprintf
                       ^
CImg.h:4961:17: note: in expansion of macro 'cimg_snprintf'
       if (*ext) cimg_snprintf(format,1024,"%%s_%%.%ud.%%s",digits);
                 ^
In file included from c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\cstdio:42:0,
                 from CImg.h:73,
                 from grey.cpp:9:
c:\mingw\include\stdio.h:317:29: note:   'snprintf'
 int __cdecl __MINGW_NOTHROW snprintf (char *, size_t, const char *, ...);
                             ^
In file included from grey.cpp:9:0:
CImg.h:144:23: error: 'snprintf' is not a member of 'std'
 #define cimg_snprintf std::snprintf
                       ^
CImg.h:4962:12: note: in expansion of macro 'cimg_snprintf'
       else cimg_snprintf(format,1024,"%%s_%%.%ud",digits);
            ^
CImg.h:144:23: note: suggested alternative:
 #define cimg_snprintf std::snprintf
                       ^

..this sort of thing continues for about 3500 lines.
Again, any help would be appreciated.  I'm out of my element on this Windows machine.

**Comment by blackrust** [comment]
Let me add that the preamble to the program looks like this:
#include  <iostream>
#include <cstdlib>
#include <sstream>
#include "../CImg.h"
using namespace cimg_library;
using namespace std;

The path to CImg.h is correct.  

The compile command I gave was 
g++ -o gs.exe grey.cpp -O2 -lgdi32

The program compiles and works fine on my linux machines

**Comment by blackrust** [comment]
OK..I don't feel like a complete idiot.
I reverted from the current release back to the CImg.h I had been using since June.  The program compiled ok on the W7 machine.

**Comment by dtschump** [comment]
Maybe you have found a regression, that could be a possibility.
I'll try to reproduce your bug with the current version, to see if something can be done.
Thanks for reporting.

**Comment by dtschump** [comment]
I think the reason is CImg is trying to invoke `std::snprintf()` instead of just `snprintf()`, and maybe on some older compilers this is not supported.
Some other projects had the same issue (https://github.com/open-source-parsers/jsoncpp/issues/224).
I've removed the `std::` prefix then in the CImg code. Latest commit should fix the issue.
Let me know, and thanks for reporting!

**Comment by blackrust** [comment]
Apologies for the delay.  I'm out of town until Monday and won't be able to test on the W7 machine.  Just fyi, the compiler on that computer is MinGW  version 4.8.1
regards,br

**Comment by blackrust** [comment]
That fixed the problem.  Thanks,br
