### ISSUE TITLE
Definition of boundary conditions

### ISSUE THREAD

**Issue by esteban-filardi** [dtschump/CImg#110]
This is a question rather than an issue.

Some methods of the library accept three types of boundary conditions: zero, Dirichlet and Neumann. I understand that using the Neumann condition is using the value of the nearest pixel. But what are the differences between a zero and Dirichlet boundary condition?

Also, you might want to consider adding the definition of the boundary conditions to the documentation because it's hard finding the definitions using those terms.

Thanks

**Comment by dtschump** [comment]
Actually, this was an error in the documentation.
I've been working two days ago on boundary conditions in CImg, and so it should be fixed now. What we have now is:

- `Dirichlet` means "0 outside image".
- `Neumann` means "Nearest neighbor outside image" (i.e. null derivative)
- `Periodic` means "Periodic" :)
- `Mirror` means "Mirrored image outside".

If you find some weird things remaining in the current doc, please let me know !

**Comment by esteban-filardi** [comment]
Thanks for the clarification

I'm attaching images with the code annotations that confused me. I'm using version 1.7.9.  Perhaps you have already  change these.

![capture](https://cloud.githubusercontent.com/assets/1585383/23106805/c8a0fd92-f6d1-11e6-8dcf-1eaf27422cd2.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1585383/23106806/c8a29936-f6d1-11e6-98d5-04ddeb4c8464.PNG)
(the same occurs in convolution)

**Comment by dtschump** [comment]
Thanks, I've posted a new pre-release package for version 2.0.0, with fixes included.
