### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by brentcl** [dtschump/CImg#112]
Getting this error for some reason:

     CImg.h: In member function ‘cimg_library::CImg<T>& cimg_library::CImg<T>::load_graphicsmagick_external(const char*)’:
     CImg.h:48683:22: error: there are no arguments to ‘pclose’ that depend on a template parameter, so a declaration of ‘pclose’ must be available [-fpermissive]
           pclose(file);
                      ^
     CImg.h:48683:22: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
     CImg.h:48690:20: error: there are no arguments to ‘pclose’ that depend on a template parameter, so a declaration of ‘pclose’ must be available [-fpermissive]
         pclose(file);
                    ^
     CImg.h: In member function ‘cimg_library::CImg<T>& cimg_library::CImg<T>::load_imagemagick_external(const char*)’:
     CImg.h:48797:22: error: there are no arguments to ‘pclose’ that depend on a template parameter, so a declaration of ‘pclose’ must be available [-fpermissive]
           pclose(file);
                      ^
     CImg.h:48805:20: error: there are no arguments to ‘pclose’ that depend on a template parameter, so a declaration of ‘pclose’ must be available [-fpermissive]
         pclose(file);
                    ^
     CImg.h: In member function ‘cimg_library::CImg<T>& cimg_library::CImg<T>::load_dcraw_external(const char*)’:
     CImg.h:48908:22: error: there are no arguments to ‘pclose’ that depend on a template parameter, so a declaration of ‘pclose’ must be available [-fpermissive]
           pclose(file);
                      ^
     CImg.h:48915:20: error: there are no arguments to ‘pclose’ that depend on a template parameter, so a declaration of ‘pclose’ must be available [-fpermissive]
         pclose(file);

Ok so I used -fpermissive to force the erros into warnings. But now I'm getting this error:

`/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay12screen_widthEv[_ZN12cimg_library11CImgDisplay12screen_widthEv]+0x2b): undefined reference to XOpenDisplay
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay12screen_widthEv[_ZN12cimg_library11CImgDisplay12screen_widthEv]+0x2b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XOpenDisplay
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay12screen_widthEv[_ZN12cimg_library11CImgDisplay12screen_widthEv]+0x98): undefined reference to XCloseDisplay
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay12screen_widthEv[_ZN12cimg_library11CImgDisplay12screen_widthEv]+0x98): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XCloseDisplay
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay13screen_heightEv[_ZN12cimg_library11CImgDisplay13screen_heightEv]+0x2b): undefined reference to XOpenDisplay
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay13screen_heightEv[_ZN12cimg_library11CImgDisplay13screen_heightEv]+0x2b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XOpenDisplay
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay13screen_heightEv[_ZN12cimg_library11CImgDisplay13screen_heightEv]+0x98): undefined reference to XCloseDisplay
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay13screen_heightEv[_ZN12cimg_library11CImgDisplay13screen_heightEv]+0x98): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XCloseDisplay
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0xdb): undefined reference to XUnmapWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0xdb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XUnmapWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x13b): undefined reference to XCheckWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x13b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XCheckWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x232): undefined reference to XResizeWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x232): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XResizeWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x30b): undefined reference to XCheckWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x30b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XCheckWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x35e): undefined reference to XGetWindowAttributes
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x35e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XGetWindowAttributes
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x37a): undefined reference to XSync
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x37a): relocation truncated to fit: R_X86_64_PC32 against undefined symbol XSync
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x3a5): undefined reference to XSetInputFocus
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x3a5): additional relocation overflows omitted from the output
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x4d5): undefined reference to XCheckWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x655): undefined reference to XCheckWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x691): undefined reference to XLookupString
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x6c1): undefined reference to XQueryKeymap
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x763): undefined reference to XLookupString
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x7aa): undefined reference to XCheckWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x88a): undefined reference to XCheckWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent[_ZN12cimg_library11CImgDisplay14_handle_eventsEPK7_XEvent]+0x902): undefined reference to XCheckWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_events_threadEPv[_ZN12cimg_library11CImgDisplay14_events_threadEPv]+0x74): undefined reference to XCheckTypedEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay14_events_threadEPv[_ZN12cimg_library11CImgDisplay14_events_threadEPv]+0x9f): undefined reference to XCheckMaskEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay13_set_colormapERmj[_ZN12cimg_library11CImgDisplay13_set_colormapERmj]+0x2a7): undefined reference to XStoreColors
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay11_map_windowEv[_ZN12cimg_library11CImgDisplay11_map_windowEv]+0x4e): undefined reference to XMapRaised
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay11_map_windowEv[_ZN12cimg_library11CImgDisplay11_map_windowEv]+0x78): undefined reference to XWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay11_map_windowEv[_ZN12cimg_library11CImgDisplay11_map_windowEv]+0xce): undefined reference to XGetWindowAttributes
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay11_map_windowEv[_ZN12cimg_library11CImgDisplay11_map_windowEv]+0xed): undefined reference to XSync
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay6_paintEb[_ZN12cimg_library11CImgDisplay6_paintEb]+0xfa): undefined reference to XSendEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay6_paintEb[_ZN12cimg_library11CImgDisplay6_paintEb]+0x1a1): undefined reference to XPutImage
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay16_init_fullscreenEv[_ZN12cimg_library11CImgDisplay16_init_fullscreenEv]+0x134): undefined reference to XCreateWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay16_init_fullscreenEv[_ZN12cimg_library11CImgDisplay16_init_fullscreenEv]+0x242): undefined reference to XCreateImage
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay16_init_fullscreenEv[_ZN12cimg_library11CImgDisplay16_init_fullscreenEv]+0x26c): undefined reference to XSelectInput
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay16_init_fullscreenEv[_ZN12cimg_library11CImgDisplay16_init_fullscreenEv]+0x289): undefined reference to XMapRaised
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay16_init_fullscreenEv[_ZN12cimg_library11CImgDisplay16_init_fullscreenEv]+0x2b3): undefined reference to XWindowEvent
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay16_init_fullscreenEv[_ZN12cimg_library11CImgDisplay16_init_fullscreenEv]+0x34b): undefined reference to XPutImage
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay16_init_fullscreenEv[_ZN12cimg_library11CImgDisplay16_init_fullscreenEv]+0x36f): undefined reference to XGetWindowAttributes
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay16_init_fullscreenEv[_ZN12cimg_library11CImgDisplay16_init_fullscreenEv]+0x38b): undefined reference to XSync
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay19_desinit_fullscreenEv[_ZN12cimg_library11CImgDisplay19_desinit_fullscreenEv]+0x35): undefined reference to XUngrabKeyboard
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay19_desinit_fullscreenEv[_ZN12cimg_library11CImgDisplay19_desinit_fullscreenEv]+0x5c): undefined reference to XDestroyWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x11d): undefined reference to XOpenDisplay
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x38e): undefined reference to XVisualIDFromVisual
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x3b7): undefined reference to XGetVisualInfo
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x418): undefined reference to XFree
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x651): undefined reference to XCreateWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x6eb): undefined reference to XCreateSimpleWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x722): undefined reference to XSelectInput
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x766): undefined reference to XStoreName
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x7d3): undefined reference to XCreateColormap
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x837): undefined reference to XSetWindowColormap
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x83c): undefined reference to XAllocClassHint
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x884): undefined reference to XSetClassHint
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x890): undefined reference to XFree
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x9c1): undefined reference to XCreateImage
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0x9f1): undefined reference to XInternAtom
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0xa21): undefined reference to XInternAtom
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0xa69): undefined reference to XSetWMProtocols
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb[_ZN12cimg_library11CImgDisplay7_assignEjjPKcjbb]+0xab5): undefined reference to XGrabKeyboard
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay6assignEv[_ZN12cimg_library11CImgDisplay6assignEv]+0x11d): undefined reference to XDestroyWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay6assignEv[_ZN12cimg_library11CImgDisplay6assignEv]+0x192): undefined reference to XFreeColormap
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay6assignEv[_ZN12cimg_library11CImgDisplay6assignEv]+0x1b2): undefined reference to XSync
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay6resizeEiib[_ZN12cimg_library11CImgDisplay6resizeEiib]+0x237): undefined reference to XResizeWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay6resizeEiib[_ZN12cimg_library11CImgDisplay6resizeEiib]+0x258): undefined reference to XGetWindowAttributes
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay4moveEii[_ZN12cimg_library11CImgDisplay4moveEii]+0x86): undefined reference to XMoveWindow
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay10show_mouseEv[_ZN12cimg_library11CImgDisplay10show_mouseEv]+0x4e): undefined reference to XUndefineCursor
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay10hide_mouseEv[_ZN12cimg_library11CImgDisplay10hide_mouseEv]+0x7c): undefined reference to XCreateBitmapFromData
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay10hide_mouseEv[_ZN12cimg_library11CImgDisplay10hide_mouseEv]+0xb1): undefined reference to XCreatePixmapCursor
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay10hide_mouseEv[_ZN12cimg_library11CImgDisplay10hide_mouseEv]+0xc5): undefined reference to XFreePixmap
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay10hide_mouseEv[_ZN12cimg_library11CImgDisplay10hide_mouseEv]+0xe3): undefined reference to XDefineCursor
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay9set_titleEPKcz[_ZN12cimg_library11CImgDisplay9set_titleEPKcz]+0x12c): undefined reference to XStoreName
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_resizeIhEEvT_jjb[_ZN12cimg_library11CImgDisplay7_resizeIhEEvT_jjb]+0x148): undefined reference to XCreateImage
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_resizeItEEvT_jjb[_ZN12cimg_library11CImgDisplay7_resizeItEEvT_jjb]+0x150): undefined reference to XCreateImage
/tmp/ccNuzKZj.o:HW2.cpp:(.text$_ZN12cimg_library11CImgDisplay7_resizeIjEEvT_jjb[_ZN12cimg_library11CImgDisplay7_resizeIjEEvT_jjb]+0x154): undefined reference to XCreateImage
collect2: error: ld returned 1 exit status`

**Comment by dtschump** [comment]
I think the two errors are not related.
The problem with `pclose()`, if I remember well comes from a bug of the g++ compiler in an older version, where the C++11 flags were activated (`-std=c++11`). With a recent version of the compiler, I think the problem should be gone. What version did you use to compile ?

When you use `-fpermissive`, it seems the linker has problems to find the definitions of the X11 library functions. If you don't need X11 capabilities in CImg (basicallu if you don't use the class `CImgDisplay`), then it is safe/better to disable the use of X11 in CImg, by using the compiling flag `-Dcimg_display=0`.
