### ISSUE TITLE
draw_ellipse() is sometimes asymmetric

### ISSUE THREAD

**Issue by karnigen** [dtschump/CImg#114]
Here is simple example, when cimg draws ellipse asymmetrically to center. In example I compare ellipse with circle to be more visual, see picture, green is ellipse, red circle is ok.
I think, that symmetry of ellipse should be somehow guaranteed.

![elcirc](https://cloud.githubusercontent.com/assets/7215249/23583272/d1dac870-013f-11e7-91c6-1b0bb6b0d8b6.png)

  uint8_t red[3]={255,0,0};
  uint8_t green[3]={0,255,0};
  CImg<uint8_t> img(99, 99, 1, 3);
  img.fill(0);
  img.draw_ellipse(49,49, 45, 45, 0, green);
  img.draw_circle(49,49, 45, red);
  img.save("elcirc.png");

**Comment by dtschump** [comment]
Thanks for reporting.
I've done this to try fixing this issue : https://github.com/dtschump/CImg/commit/01ef86a765050f083fca4866b59b6ec3254d080c

Does it look OK for you ?
