### ISSUE TITLE
compilation fails on Solaris

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#116]
I know, nobody uses Solaris, but there's a grumpy official at CRAN who keeps complaining about the following issue: 

```
../inst/include/CImg.h: In member function ‘cimg_library::CImg<typename cimg_library::cimg::last<T, int>::type> cimg_library::CImg<T>::_get_select(cimg_library::CImgDisplay&, const char*, unsigned int, unsigned int*, int, int, int, bool, bool, bool) const’:
../inst/include/CImg.h:43494:15: error: expected unqualified-id before numeric constant
               _X = (int)X, _Y = (int)Y, _Z = (int)Z
```

_X, _Y and _Z are defined by "ctype.h" and reserved for the system.

**Comment by dtschump** [comment]
Ah, nice :)
Does the following fix the issue ? https://github.com/dtschump/CImg/commit/f91cead98f3e0d0642846be480c086333de21a72

**Comment by dahtah** [comment]
Thanks, it should - let me report back

**Comment by dahtah** [comment]
I'm happy to report that CImg now officially compiles on Solaris. Next up: Commodore 64.
