### ISSUE TITLE
warning C4197: 'volatile double' in max_min function

### ISSUE THREAD

**Issue by funbiscuit** [dtschump/CImg#117]
Hello,
I use CImg for loading images and retrieving array of pixels (nothing else). During compilation I get this huge warning:

1> ***\cimg.h(22740): warning C4197: 'volatile double': top-level volatile in cast is ignored
1> ***\cimg-1.7.9\cimg.h(50716): note: see reference to function template instantiation 'const T &cimg_library::CImg<T>::max_min<volatile double>(t &) const' being compiled
1>          with
1>          [
1>              T=unsigned char,
1>              t=volatile double
1>          ]
1>  ***\cimg-1.7.9\cimg.h(50716): note: see reference to function template instantiation 'const T &cimg_library::CImg<T>::max_min<volatile double>(t &) const' being compiled
1>          with
1>          [
1>              T=unsigned char,
1>              t=volatile double
1>          ]
1>  ***\cimg-1.7.9\cimg.h(50700): note: while compiling class template member function 'const cimg_library::CImg<unsigned char> &cimg_library::CImg<unsigned char>::_save_png(FILE *const ,const char *const ,const unsigned int) const'
1>  ***\cimg-1.7.9\cimg.h(50691): note: see reference to function template instantiation 'const cimg_library::CImg<unsigned char> &cimg_library::CImg<unsigned char>::_save_png(FILE *const ,const char *const ,const unsigned int) const' being compiled
1>  ***\cimg-1.7.9\cimg.h(58628): note: see reference to class template instantiation 'cimg_library::CImg<unsigned char>' being compiled

Yes, everything works fine but this warning is annoying so I wanted to know how it can be fixed? Other than just disabling. Currently I use this:

#pragma warning( disable : 4197 ) 
#define cimg_use_jpeg
#define cimg_use_png
#include "CImg.h"
#pragma warning( default : 4197 ) 

But I wanted to know a solution, not a workaround.
I use Visual Studio 2015, target platform is win32.

**Comment by dtschump** [comment]
I believe this has been already fixed in current pre-release version *2.0.0_pre* available from the current git master : https://github.com/dtschump/CImg/blob/master/CImg.h?raw=true

Could you try with this one and tell me if you still get the issue ?
Thanks.

**Comment by funbiscuit** [comment]
No, it is still there (line numbers have changed). I replaced original file with one from that link.

1>\cimg-1.7.9\cimg.h(23744): warning C4197: 'volatile double': top-level volatile in cast is ignored
1> \cimg-1.7.9\cimg.h(52166): note: see reference to function template instantiation 'const T &cimg_library::CImg<T>::max_min<volatile double>(t &) const' being compiled
1>          with
1>          [
1>              T=unsigned char,
1>              t=volatile double
1>          ]
1>  r:\_documents\visual_studio\src\cimg-1.7.9\cimg.h(52166): note: see reference to function template instantiation 'const T &cimg_library::CImg<T>::max_min<volatile double>(t &) const' being compiled
1>          with
1>          [
1>              T=unsigned char,
1>              t=volatile double
1>          ]
1> \cimg-1.7.9\cimg.h(52150): note: while compiling class template member function 'const cimg_library::CImg<unsigned char> &cimg_library::CImg<unsigned char>::_save_png(FILE *const ,const char *const ,const unsigned int) const'
1> \cimg-1.7.9\cimg.h(52141): note: see reference to function template instantiation 'const cimg_library::CImg<unsigned char> &cimg_library::CImg<unsigned char>::_save_png(FILE *const ,const char *const ,const unsigned int) const' being compiled
1> \cimg-1.7.9\cimg.h(60089): note: see reference to class template instantiation 'cimg_library::CImg<unsigned char>' being compiled

**Comment by dtschump** [comment]
OK, then commit : https://github.com/dtschump/CImg/commits/master should be OK :)

**Comment by funbiscuit** [comment]
Thanks! That helped.
BTW, awesome library.
