### ISSUE TITLE
Strongly need to draw a text using TrueType Font. Is it possible?

### ISSUE THREAD

**Issue by ProgrammingLife** [dtschump/CImg#119]
I want to draw a text using **TrueType** Font. How to properly do it? I know that **CImg** can't work with **TTF**. Maybe I can find some solution for this problem and draw a text using **.ttf** font? :)

**Comment by ProgrammingLife** [comment]
Actually I didn't find any information on how to work with fonts in CImg. Is there any example on how to do it? Does CImg work with BMFont, for example?

**Comment by ProgrammingLife** [comment]
Any ideas?

**Comment by devernay** [comment]
see https://github.com/ilc-opensource/smart_mug/blob/master/src/image.cpp#L445

**Comment by ProgrammingLife** [comment]
Wow... thanks!

**Comment by dtschump** [comment]
Yes, there are no support for TrueType fonts in CImg. The use of a third-party library is required.
Thanks @devernay for the hint.
