### ISSUE TITLE
Please elaborate on the permute_axes string

### ISSUE THREAD

**Issue by btschumy** [dtschump/CImg#120]
Following the discussion in this thread:

https://github.com/dtschump/CImg/issues/16

I'm trying to instantiate a CImg object from an interleaved data buffer.  In my case the data is RGBA.

So I would assume I would do:

`cimg_library::CImg<unsigned char> result(byteDataPtr, (unsigned int)imageWidth, (unsigned int)imageHeight, 1, 4, true);
`

where the depth is 1 and the spectrum is 4.

Then I need to do the permute to make the data planar.  Is this still correct for RGBA data?

`result.permute_axes("yzcx");
`

I am then going to do some blurring of the image and display it on an iPhone.  To do this I need to convert back to RGBA.  

What is the permute string I would use?  This string seems like black magic to me and the docs don't do much to clarify it.  Can you give a brief description on how to interpret it?

**Comment by dtschump** [comment]
I would write : 

     CImg<unsigned char> result(byteDataPtr, 4, imageWidth, imageHeight, 1);
     result.permute_axes("yzcx");   
     result.blur(5);
     result.permute_axes("cxyz");   

then, `result.data()` is a buffer with RGBARGBARGBARGBA.... pixels.

**Comment by btschumy** [comment]
David,

Thanks for responding.  I'm a bit confused by what you list as the constructor.  Looking at the header file it seems like the constructor would be:

int imageWidth = /* the actual image width */;
int imageHeight =  /* the actual image height */;
int imageDepth = 1;
int spectrum = 4;
int shared = true;
CImg<unsigned char> result(byteDataPtr, imageWidth, imageHeight, imageDepth, spectrum, shared);

I don't see any that take the spectrum as the second argument.  Am I missing it?  I do need this to be a share image for performance.

**Comment by dtschump** [comment]
You are right, this is the constructor I'm using, but I use it first to create an image with size `width=4, height=W, depth=H, spectrum=1` where W,H is the width and height of your original RGBA image.
Then, when I call `permute_axes`, the `CImg` image size will be permuted to `WxHx1x4` which is what you want.

**Comment by btschumy** [comment]
That makes sense now.  Thanks for the help.
