### ISSUE TITLE
How to load jpg and png images ?. (in native c++ windows).

### ISSUE THREAD

**Issue by PGTBoos** [dtschump/CImg#121]
_* this is not a Clmg bug issue, rather a call for help with missing documention*_

Well since it is possible to [create native c++ in visual studio 2015](https://msdn.microsoft.com/en-us/library/ms235629.aspx) i tried the parrot example which works fine.

However i have trouble getting Clmg to work with jpg and png files.
I include 'example code' as seen on the website below and an overview of the files i have inside this project.

If i miss some file please let me know how it should look like in the folder structure to make it work.
Besides of typical visualstuddio added prj files basically that structure is close to how one would set it up in codeblocks or other compilers, its just that i'm not exactly sure what my folders and code should contain to make it work.

My intentions are to write a filter for Blender 3D app that would beatify render results. The filter is a new kind of smooth operation. Note I'm a bit new to using c++ on computers, though it must be done in c++ 
(i'm used to write c++ in micro controllers but that's slightly different).
The filter i want make is not in the code below, its just that I need the example code below to be working so that i can  start writing my thing.

`
#include "CImg.h"
#include "stdafx.h"
#define cimg_use_png 1

using namespace cimg_library;

int main() {
 //CImg<unsigned int> image("Lenna.png"), visu(500,400,1,3,0);
 CImg<unsigned char> image("D:\\Lenna.png"), visu(500, 400, 1, 3, 0);
 const unsigned char red[] = { 255,0,0 }, green[] = { 0,255,0 }, blue[] = { 0,0,255 };
 image.blur(2.5);
 CImgDisplay main_disp(image, "Click a point"), draw_disp(visu, "Intensity profile");
  while (!main_disp.is_closed() && !draw_disp.is_closed()) {
    main_disp.wait();
    if (main_disp.button() && main_disp.mouse_y() >= 0) {
      const int y = main_disp.mouse_y();
      visu.fill(0).draw_graph(image.get_crop(0, y, 0, 0, image.width() - 1, y, 0, 0), red, 1, 1, 0, 255, 0);
      visu.draw_graph(image.get_crop(0, y, 0, 1, image.width() - 1, y, 0, 1), green, 1, 1, 0, 255, 0);
      visu.draw_graph(image.get_crop(0, y, 0, 2, image.width() - 1, y, 0, 2), blue, 1, 1, 0, 255, 0).display(draw_disp);
       }
     }
   return 0;
}
`

My folder structure for this project : 

|   CImg.h
|   Lenna.jpg
|   Lenna.png
|   PGT2.cpp
|   PGT2.vcxproj
|   PGT2.vcxproj.filters
|   stdafx.cpp
|   stdafx.h
|   targetver.h
|   zlib.h
|
+---Debug
|   |   PGT2.Build.CppClean.log
|   |   PGT2.log
|   |   PGT2.obj
|   |   stdafx.obj
|   |   vc140.idb
|   |   vc140.pdb
|   |
|   \---PGT2.tlog
|           CL.command.1.tlog
|           CL.read.1.tlog
|           CL.write.1.tlog
|           link.command.1.tlog
|           link.read.1.tlog
|           link.write.1.tlog
|           PGT2.lastbuildstate
|
\---Release
    |   PGT2.log
    |   stdafx.obj
    |   vc140.pdb
    |
    \---PGT2.tlog
            CL.command.1.tlog
            CL.read.1.tlog
            CL.write.1.tlog
            link.command.1.tlog
            link.read.1.tlog
            link.write.1.tlog
            PGT2.lastbuildstate
            unsuccessfulbuild

**Comment by AtenaKid** [comment]
You need to build png and jpeg image. There is very nice tutorial that you can follow [here]([url]https://github.com/dan-silver/edge-detection-cs-4650(url)).
