### ISSUE TITLE
Example Compile Problem

### ISSUE THREAD

**Issue by maxhicks9** [dtschump/CImg#122]
When I try to compile the use_RGBclass.cpp, I receive the error

./CImg.h:361:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>

in the terminal.  Is this a separate library that I have to download? If so, is there a specific version of this library I need to have?

**Comment by ProgrammingLife** [comment]
I've solved this issue with: `#define cimg_display 0` because I don't have X11 installed on my OS X system and I really don't need to **display()** images.
