### ISSUE TITLE
OpenMP problem with Intel compiler

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#123]
I'm copying and pasting from an [imager issue](https://github.com/dahtah/imager/issues/44). There seems to be an OpenMP problem that the Intel compiler picks up and gcc/clang don't:

```
../inst/include/CImg.h(28776): error: parallel loops with collapse must be perfectly nested
for (int c = c0; c<(int)sc; c+=spectrum())
^
detected during:
instantiation of "cimg_library::CImg cimg_library::CImg::get_resize(int, int, int, int, int, unsigned int, float, float, float, float) const [with T=unsigned char]" at line 28711
instantiation of "cimg_library::CImg &cimg_library::CImg::resize(int, int, int, int, int, unsigned int, float, float, float, float) [with T=unsigned char]" at line 58816
instantiation of "const cimg_library::CImgList<cimg_library::CImgList::ucharT> &cimg_library::CImgList::font(unsigned int, bool) [with T=unsigned char]" at line 44013
instantiation of "cimg_library::CImg &cimg_library::CImg::draw_text(int, int, const char *, const tc1 *, const tc2 *, float, unsigned int, ...) [with T=unsigned char, tc1=unsigned char, tc2=unsigned char]" at line 59949
instantiation of "int cimg_library::cimg::dialog(const char *, const char *, const char *, const char *, const char *, const char *, const char *, const char *, const cimg_library::CImg &, bool) [with t=unsigned char]" at line 60088

Error: the OpenMP "single" pragma must not be enclosed by the "for" pragma
detected during:
instantiation of "cimg_library::CImg cimg_library::CImg::get_resize(int, int, int, int, int, unsigned int, float, float, float, float) const [with T=unsigned char]" at line 28711 of "../inst/include/CImg.h"
instantiation of "cimg_library::CImg &cimg_library::CImg::resize(int, int, int, int, int, unsigned int, float, float, float, float) [with T=unsigned char]" at line 58816 of "../inst/include/CImg.h"
instantiation of "const cimg_library::CImgList<cimg_library::CImgList::ucharT> &cimg_library::CImgList::font(unsigned int, bool) [with T=unsigned char]" at line 44013 of "../inst/include/CImg.h"
instantiation of "cimg_library::CImg &cimg_library::CImg::draw_text(int, int, const char *, const tc1 *, const tc2 *, float, unsigned int, ...) [with T=unsigned char, tc1=unsigned char, tc2=unsigned char]" at line 59949 of "../inst/include/CImg.h"
instantiation of "int cimg_library::cimg::dialog(const char *, const char *, const char *, const char *, const char *, const char *, const char *, const char *, const cimg_library::CImg &, bool) [with t=unsigned char]" at line 60088 of "../inst/include/CImg.h"
```

**Comment by dtschump** [comment]
Thanks for reporting Simon.
Anyway, I've absolutely no idea why this doesn't compile. The error messages are weird, I'm not even using the 'single' instruction in the OpenMP directives used in CImg.
I'm then afraid this won't be the only OpenMP-related errors found in CImg.
Are there any chances the OP tries to remove these two particular directives and see if the rest compiles fine ?

**Comment by dahtah** [comment]
No, I've told them to try and disable OpenMP. Apparently the icc compiler is available from Intel free of charge for open source developers but you have to register and I haven't got time for that right now. 
The first error seems related to (this commit)[https://github.com/ceres-solver/ceres-solver/commit/ee44fc91b59584921c1d1c8db153fda6d633b092]. 
The second one may be related to (this discussion)[http://dev-archive.ambermd.org/201509/0004.html].

**Comment by dtschump** [comment]
OK, I've just installed the Intel C++ compiler. I'll try to reproduce the bug and fix it.

**Comment by dtschump** [comment]
Looks like commit https://github.com/dtschump/CImg/commit/d66a4e7f1b13594a572c22160c20e2bd3f231f6c makes things better.
Still testing though.

**Comment by boegel** [comment]
I'm hitting similar problems, any progress on this @dtschump?

**Comment by boegel** [comment]
Here's the full patch I came up with for imager-0.31 to fix the compilation problems with the Intel compilers: https://gist.github.com/boegel/8560e16e3c54995b3b7681326fa17232

Any feedback on it?

**Comment by dtschump** [comment]
I've already done similar modifications to CImg to fix those issues as well, so current git master of CImg should already compile fine with icc/OpenMP.

**Comment by boegel** [comment]
@dtschump, @dahtah I'd need either a new release of `imager` that includes the updates to `CImg`, or a patch that applies cleanly to `imager-0.31` (preferably without introducing other changes)...

Is that an option? Or does the patch I came up with look reasonable?

**Comment by dahtah** [comment]
I've updated imager (see master branch), I was waiting for OP to report success.

**Comment by boegel** [comment]
@dahtac Are you also planning to release a new version of imager that includes the fixes?

**Comment by dahtah** [comment]
Do you mean release on CRAN? Yes, but maybe not this week. You can install the current version using devtools:
```devtools::install_github("dahtah/imager")```
Do you need the package to be on CRAN?

**Comment by boegel** [comment]
@dahtahYes, I mean a CRAN release. We prefer to stick to (versioned) releases, since that allows us to reproduce the installation later in other places.

**Comment by boegel** [comment]
@dahtah Also, the last update to `master` at https://github.com/dahtah/imager was 16 days ago, so the CImg changes to fix Intel compilation aren't there yet?

**Comment by dahtah** [comment]
My bad, forgot to push commit. Should work now. 
I'll try and submit to CRAN later this week, hoping they won't make me jump through hoops.

**Comment by boegel** [comment]
@dahtah Latest commit in `master` is still from March 18th...

**Comment by dahtah** [comment]
I'm an idiot. For real, this time.

**Comment by boegel** [comment]
@dahtah OK, I included the changes in `master` for `CImg.h` as a patch on top of `imager` 0.40.1, which were sufficient to make the compilation work with Intel compilers, as long as I included `wd308` as a C++ compiler option to avoid errors like:
```
member "std::complex<double>::_M_value" is inaccessible
```
