### ISSUE TITLE
use_tiff_stream compile error

### ISSUE THREAD

**Issue by svensk-pojke** [dtschump/CImg#124]
Hello. When trying to build the examples I get the following error. Any help is appreciated.

Thanks,
Erik

** Compiling 'use_tiff_stream (2.0.0_pre031617)' with 'gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) '

g++ -o use_tiff_stream use_tiff_stream.cpp -I.. -Wall -Wextra -Wfatal-errors -O2 -mtune=generic -Dcimg_use_vt100 -Dcimg_display=1    -Dcimg_use_xrandr  -Dcimg_use_tiff  -Dcimg_use_openexr -I/usr/include/OpenEXR -Dcimg_use_png  -Dcimg_use_jpeg  -Dcimg_use_zlib   -Dcimg_use_curl -Dcimg_use_opencv -I/usr/include/opencv   -I/usr/include/opencv -Dcimg_use_magick -I/usr/include/GraphicsMagick   -Dcimg_use_fftw3  -lm -lX11   -lpthread  -lXrandr -ltiff -ltiffxx -lIlmImf -lHalf -lpng -lz -ljpeg -lz   -lcurl -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab   -lGraphicsMagick++ -lGraphicsMagick   -lfftw3 -lfftw3_threads
In file included from ../CImg.h:10608:0,
                 from use_tiff_stream.cpp:52:
../plugins/tiff_stream.h: In instantiation of ‘cimg_library::CImg<T>& cimg_library::CImg<T>::load_tiff(std::istream*, unsigned int, unsigned int, unsigned int) [with T = short unsigned int; std::istream = std::basic_istream<char>]’:
use_tiff_stream.cpp:68:26:   required from here
../plugins/tiff_stream.h:166:47: error: no matching function for call to ‘max(unsigned int&, unsigned int&)’
           resize(cimg::max(frame._width,_width),cimg::max(frame._height,_height),
                                               ^
compilation terminated due to -Wfatal-errors.
m

**Comment by dtschump** [comment]
This is actually a bug.
Commit https://github.com/dtschump/CImg/commit/e4e80e90b93526e62151ebf4983a1bf3c90566b2 should fix it.
I'll release a new package today with this fix. Thanks for reporting.

**Comment by svensk-pojke** [comment]
Just tested with the new 2.0.0_pre032317 download and it builds fine.
Thanks!
