### ISSUE TITLE
pop-up boxes on Windows when loading TIFF images

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#125]
Libtiff behaves in a very annoying fashion and opens a pop-up box on Windows when it wants to issue a warning about fields it doesn't know about. This prevents batch processing of images on Windows with CImg. The issue also appeared in RawTherapee, see [here](https://github.com/Beep6581/RawTherapee/issues/2078).

**Comment by heckflosse** [comment]
`        TIFFSetWarningHandler(nullptr);    // avoid annoying message boxes`

fixed that in RawTherapee

**Comment by dtschump** [comment]
Ah yes, I used it too in CImg, but with the wrong test to enable it :(
Commit : https://github.com/dtschump/CImg/commit/2b1ea39e3c00ba898fcaac0374ddecdec9cf3d88 should fix that issue.

**Comment by dahtah** [comment]
Great, thanks David!

**Comment by dahtah** [comment]
Sorry David, have to re-open this. Popup boxes appear during the call to TIFFReadDirectory, TIFFSetWarningHandler(0) and TIFFSetErrorHandler(0) come too late. They should be moved up a few lines.

**Comment by dtschump** [comment]
Hi Simon, does this https://github.com/dtschump/CImg/commit/1b70e48a9a787c072f956bceec20e45cf99c1c4f fix the issue ?
Otherwise, do you have a non-working tiff file to attach maybe ?

**Comment by dtschump** [comment]
Issue fixed with https://github.com/dtschump/CImg/commit/c640d181bf51c71d853e5e516f1054fbfd197680
