### ISSUE TITLE
How to put one image over another at a specified XY-position?

### ISSUE THREAD

**Issue by ProgrammingLife** [dtschump/CImg#126]
How to put one image over another at a specified XY-position?
I mean I need something like this: **img3 = img1 + img2;** but using specified XY-position, i.e.: 

`img1.draw( img2, 50, 70 ); // position: 50x70`

**Comment by dtschump** [comment]
Use `CImg<T>::draw_image()` for this (http://cimg.eu/reference/structcimg__library_1_1CImg.html#a952f376650e7aed047648391a55da5de).
