### ISSUE TITLE
Multiplication operator performs wrong checks

### ISSUE THREAD

**Issue by volucris-flagrans** [dtschump/CImg#127]
If I understand it correctly the mutiplication operator
    CImg<_cimg_Tt> operator*(const CImg<t>& img) const
should check if both images have the same dimensions, instead it checks
      if (_width!=img._height || _depth!=1 || _spectrum!=1)

**Comment by dtschump** [comment]
No, the multiplication operator in CImg acts as a matrix multiplication.
Use `CImg<T>::mul()` and `CImg<T>::get_mul()` for pointwise multiplication.
