### ISSUE TITLE
Can CImg work using CUDA/GPU resources?

### ISSUE THREAD

**Issue by ProgrammingLife** [dtschump/CImg#128]
Can CImg work using CUDA/GPU resources?

**Comment by dtschump** [comment]
Not at this point, no.

**Comment by pderian** [comment]
CImg won't work directly with GPU resources. However, the raw data (array of pixel of a given type) under the CImg structure can be easily accessed (.data() method) and copied from/to the GPU. E.g. the following workflow:

- open image files, preprocess on the CPU with CImg;
- copy the underlying data to the GPU, do all heavy computations there;
- send result back to CPU and display on screen, save images, etc. again with CImg.

When applicable, it is very efficient. We use it for [cuTyphoon](http://www.pierrederian.net/typhoon.html), the GPU-accelerated version of a fluid motion estimator.

**Comment by dtschump** [comment]
@pderian , so I've added a link to *Typhoon* [here](http://cimg.eu/links.shtml) :+1: 
Your software looks great!

**Comment by pderian** [comment]
Thanks @dtschump ! 
CImg has been extremely useful to the development of _Typhoon_. Then its GPU-accelerated extension _cuTyphoon_ ended up being fairly simple to deal with, following the workflow I described above. So many, many thanks for CImg as well :)

**Comment by heckflosse** [comment]
@pderian OT:  I found a typo ;-)
![typo](https://user-images.githubusercontent.com/13733487/27084753-47910500-504d-11e7-9a8e-155dcf2e80b4.png)

**Comment by pderian** [comment]
@heckflosse typo fixed, thanks!

**Comment by heckflosse** [comment]
@pderian De rien.
