### ISSUE TITLE
Why it's not support alpha channel in png?

### ISSUE THREAD

**Issue by ProgrammingLife** [dtschump/CImg#129]
I have a code:
```
cimg_library::CImg < float > image( "images/img2.png" ); // with alpha channel!
image.save( "images/test.png" );
```
I don't know why but it loose alpha channel in the output file. Why does it work like this?

**Comment by ProgrammingLife** [comment]
I've just found the solution for this problem. I just need to turn on LibPNG for my project:
`g++ cimg-test.cpp --std=c++14 -o cimg-test.o -Dcimg_use_png -lpng `pkg-config --libs libpng` `pkg-config --cflags libpng``

**Comment by dtschump** [comment]
Yes, without using libpng, the default fallback is to use `convert` from ImageMagick, and in that case, I don't try to preserve the alpha-channel (explicit conversion to non-compressed .bmp files are used in the process).

**Comment by pwplus7** [comment]
I have found it better to use LODE_PNG (http://lodev.org/lodepng/) vs libpng when using CImg.
LODE_PNG is a fairly complete and platform-independent PNG library that only requires one header file to run and it has no dependencies on any other library (zlib is part of LODE_PNG).
