### ISSUE TITLE
CImg with imageMagick++

### ISSUE THREAD

**Issue by zhanghaocol** [dtschump/CImg#133]
I make the example code with
1. cmake -DCMAKE_BINARY_DIR="./" -DPROJECT_SOURCE_DIR="../examples" ../examples/  -G "Eclipse CDT4 - Unix Makefiles"
2.make
 but encounter the problem like /CImg.h:47980:12: error: ‘PaletteMatteType’ is not a member of ‘Magick’
 any help would be appreciate

**Comment by dtschump** [comment]
I'm currently on vacations. I'll check this when I return. Thanks for your report.

**Comment by dorpxam** [comment]
I've the same problem. PaletteMatteType seem remove from the enum in the latest version of ImageMagick (2.0.0). What is the most perfect version to use with Cimg? Thank you for all!
