### ISSUE TITLE
Fail to open .bmp with pixel depth > 8

### ISSUE THREAD

**Issue by elia-maracani** [dtschump/CImg#134]
Hi!

I'm doing a university project for an exam in which we have to read grayscale BMP images. 
If I use an 8-bit one, there is no problem, but as soon as I switch to a 24-bit, or 32-bit one, it crashes :/
Does this library support higher BMP depth than 8-bit? If so, what should I do to make it work?

This is my line of code, if it is of any help:
`CImg<float> image("duck.bmp");`

Thanks,
M.E.

**Comment by dtschump** [comment]
BMP files should be supported with 24 and 32 bits/pixels, except if the file is saved in a compressed way.
Is it the case ?
Could you provide on file that does not work ? On what OS did you try ?
What is the error message you get ? Is it a real crash or just an exception thrown ?

**Comment by elia-maracani** [comment]
First of all, WOW, thanks for such a quick reply :D

- I honeslty have no idea :/
- This is the image I've downloaded and I'm currently working on: [duck.bmp](http://www.d10.karoo.net/ruby/quiz/50/duck.bmp)
- I'm working on Windows 10, with Visual Studio 2017 CE
- This is the Exception I get on the terminal:
[CImg] *** CImgIOException *** [instance(0,0,0,0,0000000000000000,non-shared)] CImg<float>::load(): Failed to open file 'duck.bmp'.

**Comment by dtschump** [comment]
I've just tested with your image, and it works for me. I don't think the image is stored compressed.
Considering the error message you get, I suspect you didn't put your file `duck.bmp` in the same folder as your executable (the error says nothing about the file format, but just that it doesn't find the file).
Please try again, by copying the image file in the correct folder, or try to load it specifying its absolute path in your C++ code.. It should work.

**Comment by elia-maracani** [comment]
I feel so dumb right now. Looks like the .exe I was looking at was not the one that VS was executing when debugging :/ 
Used the absolute path instead, now it works. Thanks! :)
