### ISSUE TITLE
slide show

### ISSUE THREAD

**Issue by renatorocci** [dtschump/CImg#135]
I have never written a C++ program. I used to be a IBM 370 programmer but in seventies, many years ago.
Now I would use CImg to write a program to perform a slide show of my big archive of jpg pictures. I understand that  Cimg should be useful for my porpose.
The program should read the pictures from their directories one by one, show one by one on the monitor for a given number of seconds, store last picture shown (file name and directory) and so on.
The program should start a certain time in the morning and stop a certain time in the evening.
When the program starts the first pictures shown should be that following the last stored as shown.
To start I copied the following from a  Cimg example to display a single picture

`#include "CImg.h"
// Include the main and only header file of the CImg library. 
using namespace cimg_library;
//Use the library namespace to ease the declarations afterward. 
int main() {
//Definition of the main function. 
  CImg<unsigned char> image("lena.jpg");
//Creation of one instance of image of unsigned char pixels. The image image is initialized by reading an image file from the disk. Here, lena.jpg must be in the same directory as the current program. Note that you must also have installed the ImageMagick package in order to be able to read JPG images.). 
  CImgDisplay main_disp(image);
//Creation of one display window, one for the input image image. By default, CImg displays handles events (mouse,keyboard,..). On Windows, there is a way to create fullscreen displays. 
  while (!main_disp.is_closed()) {
//Enter the event loop, the code will exit when one of the two display windows is closed. 
    main_disp.wait();
//Wait for an event (mouse, keyboard,..) in the display window main_disp. 
       }
  return 0;
}`

 but I collected a list of errors.
Could you help me?

**Comment by dtschump** [comment]
What kind of errors did you encounter ?
Basically, that's the right way to go, using `CImgDisplay` in conjunction with `CImg<unsigned char>`, and a little timer. If I have time, I'll try to write some basic code to do that.

**Comment by dtschump** [comment]
This is what I've done quickly : 

```
#include "CImg.h"
using namespace cimg_library;

int main(int argc, char **argv) {

  const char *const folder = cimg_option("-i",".","Path containing pictures");
  char pattern[1024];
  std::snprintf(pattern,1024,"%s/*.jpg",folder);
  const CImgList<char> filenames = cimg::files(pattern,true,0,true);

  CImgDisplay disp(1,1,0,0,1,1);
  cimglist_for(filenames,l) {
    const char
      *const filename = filenames[l],
      *const basename = cimg::basename(filename);

    const CImg<unsigned char> img(filename);
    disp.resize(cimg_fitscreen(img.width(),img.height(),1),0);
    disp.display(img).set_title(basename);
    if (disp.is_keyESC()) std::exit(0);
    cimg::wait(3000);
  }

  return 0;
}

```

I'm using Linux, and compile it like this : 

    $ g++ -o foo foo.cpp -lX11 -lpthread

Then, invoke it like this : 

    $ ./foo -i ~/work/img/

Hope this helps.

**Comment by renatorocci** [comment]
First of all thank you for your answer!
I changed only the compilation adding

 -lX11 -lpthread

and the program goes!

Now I will work around your code and I let you now!
Thank you again!
Renato

**Comment by renatorocci** [comment]
I tried to understand your code.
I have understood that you collect the folder name from the command line
and I succeeded to display the pictures from my folder in this way:
renato@renato-mansarda:~/programmaC$ ./prova3+ -i "Versione per Cornice digitale1024x768anni20"

at the end of the display the program ends in this way: 
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  4 (X_DestroyWindow)
  Resource id in failed request:  0x769fce11
  Serial number of failed request:  304
  Current serial number in output stream:  306

Now I have to explain that my real purpose is to write a program that displays pictures from different fixed folders.
I thought to give the names of the folders to the program in the way you see below

#include "CImg.h"
using namespace cimg_library;

int main(int argc, char **argv) {
 char folders [14] [50] = {
"Versione per Cornice digitale1024x768anni20",
"Versione per Cornice digitale1024x768anni30",
"Versione per Cornice digitale1024x768anni40",
"Versione per Cornice digitale1024x768anni50",
"Versione per Cornice digitale1024x768anni60",
"Versione per Cornice digitale1024x768anni70",
"Versione per Cornice digitale1024x768anni80",
"Versione per Cornice digitale1024x768anni90",
"Versione per Cornice digitale1024x768anni2000-1",
"Versione per Cornice digitale1024x768anni2000-2",
"Versione per Cornice digitale1024x768anni2000-3",
"Versione per Cornice digitale1024x768anni2010-1",
"Versione per Cornice digitale1024x768anni2010-2",
"Versione per Cornice digitale1024x768anni2010-3",
  };
  const char *const folder = cimg_option("-i",".","Path containing pictures");
  char pattern[1024];
  std::snprintf(pattern,1024,"%s/*.jpg",folder);
  const CImgList<char> filenames = cimg::files(pattern,true,0,true);

  CImgDisplay disp(1,1,0,0,1,1);
  cimglist_for(filenames,l) {
    const char
      *const filename = filenames[l],
      *const basename = cimg::basename(filename);

    const CImg<unsigned char> img(filename);
    disp.resize(cimg_fitscreen(img.width(),img.height(),1),0);
    disp.display(img).set_title(basename);
    if (disp.is_keyESC()) std::exit(0);
    cimg::wait(3000);
  }

  return 0;
}


After the display of the last picture of the last folder the display should restart from the fist picture of the fist folder, but due to the large number of pictures per folder this process could last for many days.
That’s why I would stop and restart the process at certain times or with certain commands.

What I have not understood is how your program stops and how restarts from the picture where stopped.

Thanks again,
Renato
