### ISSUE TITLE
SHA-256 mismatch for CImg_2.0.0.zip

### ISSUE THREAD

**Issue by ilovezfs** [dtschump/CImg#136]
Homebrew users currently cannot install `cimg` due to a SHA-256 checksum mismatch for CImg_2.0.0.zip.

7 hours ago the checksum was
f6ee5c6b16fac167c120a060998ab6864856ff0a2bbb78134472db7ca0f26889

Now it appears to be
9f94dd7294d52a0515369534cf3c616532a6b32191724d53aba1dc7b636cedb2

Have you been hacked? We'll need to understand why the file has changed before the checksum can be updated in Homebrew. Thanks!

**Comment by dtschump** [comment]
Ah sorry about that, I've fixed a one-line bug in the source code a few hours after the first release.
Won't happen anymore :)

**Comment by ilovezfs** [comment]
@dtschump OK, thanks for confirming!

**Comment by ilovezfs** [comment]
This was sorted out. Thanks again!
