### ISSUE TITLE
convert opencv cv::Mat into CImg?

### ISSUE THREAD

**Issue by Thanh-Binh** [dtschump/CImg#137]
I try to convert cv::Mat into CImg as follows:
#define cimg_plugin1 "cvMat.h"
......
cv::Mat tmp;
CImg img(tmp);
......
but got an error like
missing template argument before 'img'
Can you help me? Thanks

**Comment by aalbiol** [comment]
Have you tried "CImg<float> img(tmp); "?

Also I would suggest not to use empty cv::Mat.

**Comment by Thanh-Binh** [comment]
yes, but I use non-empty cv::Mat. In my test, I put
cv::Mat tmp = cv::Mat:zeros(100,100, CV_8UC1);

**Comment by Usernamezhx** [comment]
@Thanh-Binh hi how did you solve this probelm?

**Comment by Thanh-Binh** [comment]
I remember I wrote my own small function for converting Mat to CImg

**Comment by Usernamezhx** [comment]
> I remember I wrote my own small function for converting Mat to CImg

thanks for your reply
