### ISSUE TITLE
Errors with saving

### ISSUE THREAD

**Issue by oa10712** [dtschump/CImg#138]
Attempts to save as a bmp result in the following error:
`[CImg] *** CImgIOException *** cimg::fopen(): Failed to open the file '~/tiles/0/0/0.bmp' with mode 'wb'.`
as a result of the following code to call the save function:
```
    std::string directoryCommand = "mkdir -m777 -p ~/tiles/" + boost::lexical_cast<std::string>(zoom) + "/" + boost::lexical_cast<std::string>(x);
    std::string filename = "~/tiles/" + boost::lexical_cast<std::string>(zoom) + "/" + boost::lexical_cast<std::string>(x) + "/" + boost::lexical_cast<std::string>(y) + ".bmp";

    const char* file_o = cimg_option("-o", filename.c_str(), "Output file");
    system(directoryCommand.c_str());
    std::cout << "Made required dirs\n";
    CImg<unsigned char> imageClone = image.get_resize(256, 256, -100, -100, 1);

    std::cout << "scaled image\n";
    imageClone.save(file_o);
```

**Comment by dtschump** [comment]
`~/tiles/0/0/0.bmp` should be probably replaced by something like `/home/username/tiles/0/0/0.bmp`.

The tilde `~` means the value of `$HOME` only when used in a shell. But you have to keep in mind that this substitution is not done anywhere else, particularly in a C++ code :)
