### ISSUE TITLE
how can I use Cimg for working with video?

### ISSUE THREAD

**Issue by Thanh-Binh** [dtschump/CImg#139]
Could anybody give me a hint how to read video into Cimg?
I tried to use get_load_video(), but can not compile it due to many errors.
Thanks

**Comment by Thanh-Binh** [comment]
Any help please!

**Comment by aalbiol** [comment]
You must have opencv installed to use get_load_video().

#define cimg_use_opencv //To be able to use capture from camera in cimg
#include "CImg.h"


		int count;
		for( count = 0; 1 ; count++ ) {
			imgv.load_video( input.c_str(), count, count);
			if ( imgv.is_empty() || disp_cimg.is_keyQ() || disp_cimg.is_keyESC()) {
				if ( count == 0) {//Video not found
					std::cerr << "Could not read from video " << input << "\n";
					exit(0);
				}
				else
					break; //End of video
			}

			//Here you can do whatever you want with imgv. The following is just an example
			CImg<unsigned char> out;
			sample_processing_function(imgv,out);
			out = imgv.get_append(out,'x');
			disp_cimg.display(out).set_title( "Video" );
		}
		imgv.load_video( input.c_str(), 0, 0, 0, 0);

	}

BONUS:
If you want to capture images from a camera the code is:
		CImg<unsigned char> cimg_img;
		cimg_img.load_camera( camera_number, 0, false, capt_width, capt_height);
		if ( cimg_img.is_empty() ) {
			std::cerr << "Could not capture from camera " << camera_number << "\n";
			exit(0);
		}

		while(1) {
			// Load image
			cimg_img.load_camera(camera_number,0,false);
			if ( cimg_img.is_empty() || disp_cimg.is_keyQ() || disp_cimg.is_keyESC())
				break;

			// Do what you want with  cimg_img
			CImg<unsigned char> out;
			sample_processing_function(cimg_img,out);

			out = cimg_img.get_append(out,'x');
			disp_cimg.display(out).set_title( "Camera" );
		}

		//Release camera
		cimg_img.load_camera( camera_number, 0, true, capt_width, capt_height);
	}
