### ISSUE TITLE
VisualStudio 2015, x64, Compiler Warning C4319

### ISSUE THREAD

**Issue by ojde** [dtschump/CImg#141]
CImg 2.0.2
Visual Studio 2015 Community Edition
Configuration: Debug x64

Lines 16786 and 19917
"warning C4319: '~': zero extending 'unsigned int' to 'double' of greater size"

Is this (a new) one of the 'silly warnings on some Microsoft VC++ compilers'? Can it be ignored? Or something serious which should prevent me using CImg with x64 compile?

Full warning text:

    ...\cimg.h(16786): warning C4319: '~': zero extending 'unsigned int' to 'double' of greater size
        ...\cimg.h(15354): note: while compiling class template member function 'unsigned int cimg_library::CImg<float>::_cimg_math_parser::compile(char *,char *,const unsigned int,unsigned int *const )'
        ...\cimg.h(15233): note: see reference to function template instantiation 'unsigned int cimg_library::CImg<float>::_cimg_math_parser::compile(char *,char *,const unsigned int,unsigned int *const )' being compiled
        ...\cimg.h(24044): note: see reference to class template instantiation 'cimg_library::CImg<float>::_cimg_math_parser' being compiled
        ...\cimg.h(24033): note: while compiling class template member function 'double cimg_library::CImg<float>::_eval(cimg_library::CImg<float> *const ,const char *const ,const double,const double,const double,const double,const cimg_library::CImgList<T> *const ,cimg_library::CImgList<T> *const ) const'
            with
            [
                T=float
            ]
        ...\cimg.h(24028): note: see reference to function template instantiation 'double cimg_library::CImg<float>::_eval(cimg_library::CImg<float> *const ,const char *const ,const double,const double,const double,const double,const cimg_library::CImgList<T> *const ,cimg_library::CImgList<T> *const ) const' being compiled
            with
            [
                T=float
            ]
        ...\cimg.h(36199): note: see reference to class template instantiation 'cimg_library::CImg<float>' being compiled
        ...\cimg.h(59016): note: see reference to class template instantiation 'cimg_library::CImg<wchar_t>' being compiled
    ...\cimg.h(19917): warning C4319: '~': zero extending 'unsigned int' to 'double' of greater size
        ...\cimg.h(19915): note: while compiling class template member function 'double cimg_library::CImg<float>::_cimg_math_parser::mp_bitwise_not(cimg_library::CImg<float>::_cimg_math_parser &)'
        ...\cimg.h(16785): note: see reference to function template instantiation 'double cimg_library::CImg<float>::_cimg_math_parser::mp_bitwise_not(cimg_library::CImg<float>::_cimg_math_parser &)' being compiled

see also: https://msdn.microsoft.com/en-us/library/bh558kz2.aspx

**Comment by dtschump** [comment]
Checked the source code, and this is indeed correct.
The behavior described by the warning is indeed intended in this case. I'm not sure if this warning message can be discarded by any means, but I'm sure this won't make your code crash :)

**Comment by ojde** [comment]
Great! Thanks for the quick response!
Then best would be to just add another entry after Line 123 in 

    117: // Disable silly warnings on some Microsoft VC++ compilers." 
    [...]
    123: #pragma warning(disable:4312)
    ++124: #pragma warning(disable:4319)
    125: #pragma warning(disable:4512)

**Comment by dtschump** [comment]
Done : https://github.com/dtschump/CImg/commit/9bece010425184d6793e05e54a7bd2df1cec16f7
Please tell me if that is working or not. I had some troubles in the past trying to disable MSVC warnings with pragmas :)

**Comment by ojde** [comment]
Does work! Warning gone in _Visual Studio 2015 Community Edition_
