### ISSUE TITLE
CImg,h needs to be modified to avoid compiler errors

### ISSUE THREAD

**Issue by pwplus7** [dtschump/CImg#147]
In file Cimg.h,  line# 6164 to 6180,  marked //LG below,  must be deleted to avoid two compiler errors
on Microsoft Windows OS :
"undefined reference to _fseeki64"   and "undefined reference to _ftelli64 "  

e.g. These compiler errors are generated by the stmt: CImg<u8> img ("MyFileName.bmp") ;

line# 6164 to 6180 are as follows (with deleted lines marked //LG ):
//! Version of 'fseek()' that supports >=64bits offsets everywhere (for Windows).
    inline int fseek(FILE *stream, cimg_long offset, int origin) {
//LG #if cimg_OS==2
//LG      return _fseeki64(stream,(__int64)offset,origin);
//LG #else
      return std::fseek(stream,offset,origin);
//LG #endif
    }

    //! Version of 'ftell()' that supports >=64bits offsets everywhere (for Windows).
    inline cimg_long ftell(FILE *stream) {
//LG #if cimg_OS==2
//LG      return (cimg_long)_ftelli64(stream);
//LG #else
      return (cimg_long)std::ftell(stream);
//LG #endif
    }

**Comment by dtschump** [comment]
Which compiler, which version of Windows ?
This is working well here, with MSVC2010 and g++ on Windows 7 (64bits).

**Comment by pwplus7** [comment]
David:

windows 10

g++ 5.1.0 (32 bit)

ps .resize and .assign also dont work

On Sat, Aug 19, 2017 at 4:35 AM, David Tschumperlé <notifications@github.com

**Comment by pwplus7** [comment]
PS

prior to my changes the following stmt generated compiler errors :
   CImg<u8> img ("chess/WRook.bmp") ;

after my changes, it compiles and the stmt compiles and runs OK

**Comment by pwplus7** [comment]
PS here you can get details on the 32-bit, MS Windows g++ compiler I'm
using:

https://sourceforge.net/projects/tdm-gcc/

On Sat, Aug 19, 2017 at 4:35 AM, David Tschumperlé <notifications@github.com

**Comment by dtschump** [comment]
Thanks for the report. I understand that for Win32, the `std::ftell()` function must be used instead of `__fseeki64()`.
I propose this change : 

    l. 6167 : #if cimg_OS==2 && (defined(WIN64) || defined(_WIN64))

instead of

    l. 6167: #if cimg_OS==2

Could you tell me if that fixes your issue ? With that at least, the previous call will still hold for 64bits systems.

**Comment by pwplus7** [comment]
David:

your change worked. I also made the same change a few lines below 6167
i.e
#if cimg_OS==2 && (defined(WIN64) || defined(_WIN64))
      return (cimg_long)_ftelli64(stream);
#else
      return (cimg_long)std::ftell(stream);

On Sat, Aug 19, 2017 at 2:58 PM, David Tschumperlé <notifications@github.com

**Comment by pwplus7** [comment]
another issue:

under
http://cimg.eu/reference/structcimg__library_1_1CImg.html#a24f3b43daa4444b94a973c2c3fff82c5

section:

CImg <http://cimg.eu/reference/structcimg__library_1_1CImg.html> ( const
unsigned int  size_x,
const unsigned int  size_y,
const unsigned int  size_z,
const unsigned int  size_c,
const int  value0,
const int  value1,
  ...
)

Construct image with specified size and initialize pixel values from a
sequence of integers.

..contains a small example which generates compiler errors, i.e.
CImg<float> img(2,2,1,3, // Construct a 2x2 color (RGB) image 0,255,0,255, //
Set the 4 values for the red component

0,0,255,255, // Set the 4 values for the green component.

64,64,64,64); // Set the 4 values for the blue component.
img.resize(150,150).display();

(same compiler errors when I change '2,2,1,3' above

to '2,2,1,4')

On Sat, Aug 19, 2017 at 2:58 PM, David Tschumperlé <notifications@github.com

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/CImg/commit/82b7a22b7c343af194245f5389e95c22cab44762 should fix the first issue.
I don't get the second issue with the constructor. What kind of error messages do you get ?
I cannot test here as I don't have a Win32 machine available for testing, sorry about that.

**Comment by pwplus7** [comment]
*no matching function for call to 'cimg_library::CImg<unsigned
char>::resize(int, int) const'*
* img.resize(150,150*).display();
                   ^
In file included from test.cpp:8:0:
CImg.h:28886:14: note: candidate: cimg_library::CImg<T>&
cimg_library::CImg<T>::*resize(int, int, int, int, int, unsigned int,
float, float, float, float) [with T = unsigned char] <near match>*
     CImg<T>& resize(const int size_x, const int size_y=-100,
              ^
CImg.h:28886:14: note:   passing 'const cimg_library::CImg<unsigned char>*'
as 'this' argument discards qualifiers
CImg.h:29806:14: note: candidate: template<class t> cimg_library::CImg<T>&
cimg_library::CImg<T>::resize(const cimg_library::CImg<t>&, int, unsigned
int, float, float, float, float) [with t = t; T = unsigned char]
     CImg<T>& resize(const CImg<t>& src,
              ^
CImg.h:29806:14: note:   template argument deduction/substitution failed:
test.cpp:40:19: note:   mismatched types 'const cimg_library::CImg<T>' and
'int'
 img.resize(150,150).display();
                   ^
In file included from test.cpp:8:0:
CImg.h:29834:14: note: candidate: cimg_library::CImg<T>&
cimg_library::CImg<T>::resize(const cimg_library::CImgDisplay&, int,
unsigned int, float, float, float, float) [with T = unsigned char]
     CImg<T>& resize(const CImgDisplay& disp,
              ^
CImg.h:29834:14: note:   no known conversion for argument 1 from 'int' to
'const cimg_library::CImgDisplay&'

On Sat, Aug 19, 2017 at 5:30 PM, David Tschumperlé <notifications@github.com

**Comment by dtschump** [comment]
From the error message, I understand you are trying to resize a `const` instance of a `CImg<unsigned char>`, which is indeed not permitted.
I don't understand why is that appearing if you have been using the example source code, as I don't define my `CImg` as `const`.
It works for me.

**Comment by pwplus7** [comment]
David:
OK I understand your point on the example taken from the documentation file.

But why does this example give incorrect results ?

typedef unsigned char u8;
typedef unsigned int u32;

....

u8 pix[]= { 11,12,13, 21,22,23, 31,32,33, 41,42,43, 51,52,53, 61,62,63 } ;
CImg<u8> img(pix, 3,2,1,3) ;
u32 h=img.height(), w= img.width(), s=img.spectrum();

printf("\n\n using u8* .data()") ;
u8 *p= img.data() ;
for (int y=0; y< w*h*s; y++) { if (!( y%(w*s) )) printf("\n "); printf("
%d", *(p+y) ) ; }


printf("\n\n using cimg_for ");
cimg_forY (img, y)
{ printf("\n y= %d: ", y);
  cimg_forX (img, x)
  { printf("\n     x= %d: ", x);
    cimg_forC (img, c)
      // printf(" c %d %d", c, img[y*w*s +x*s +c] ) ;  // This gives
correct results
       printf(" c %d %d", c, img(x,y,c) ) ;          // This gives
INCORRECT results
      // { u8* d=img.data(x,y,1,c); printf(" c %d %d", c, *d ); }  // This
gives INCORRECT results
} }

On Sun, Aug 20, 2017 at 3:29 AM, David Tschumperlé <notifications@github.com

**Comment by dtschump** [comment]
This is another (non)-issue, but let me explain this briefly.
In a CImg buffer, pixel data are not stored as RGBRGBRGB...RGBRGB but as RRRRRR....GGGGGG....BBBBB, so basically your `img[y*w*s +x*s +c]` is definitely not equivalent to `img(x,y,c)`.

`img(x,y,c)` is actually equivalent to `img[x + y*w + c*w*h]`.

**Comment by dtschump** [comment]
#define cimg_verbosity 3

will add extra checks to limit the access to wrong memory address. In CImg, the first column/row/slice/channel of an image starts indeed with `0`, not `1` (as it is usually done in C/C++).

For the `static` class function, use it as you would do with any other class (that's a C++ related trick, not particular to CImg):

    CImg<u8> img  = CImg<u8>::lines_LUT256();
