### ISSUE TITLE
GraphicsMagick not working with CImg

### ISSUE THREAD

**Issue by sylvester328** [dtschump/CImg#152]
I believe I can either install imagemagick OR graphicsmagick for cimg to handle jpg, png, etc.

I installed graphicsmagick, without imagemagick, cimg gives error 'sh: 1: convert: not found'.

Looking at the source, graphicsmagick will be used if an exception is caught when trying imagemagick.  It seems no exception is thrown in this case and the code just terminates.

I swapped the try sequence and get graphicsmagick to work but doing that the situation is just reversed: 
installed imagemagick will be not used if cimg finds that graphicsmagick is missing ('sh: 1: gm: not found').

By the way, using Debian 8.

try { load_magick(filename); }
      catch (CImgException&) {
        try { load_imagemagick_external(filename); }
        catch (CImgException&) {
          try { load_graphicsmagick_external(filename); }
          catch (CImgException&) {
            try { load_cimg(filename); }
            catch (CImgException&) {
              try {
                std::fclose(cimg::fopen(filename,"rb"));
              } catch (CImgException&) {
                cimg::exception_mode(omode);
                throw CImgIOException(_cimg_instance
                                      "load_other(): Failed to open file '%s'.",
                                      cimg_instance,
                                      filename);
              }
              cimg::exception_mode(omode);
              throw CImgIOException(_cimg_instance
                                    "load_other(): Failed to recognize format of file '%s'.",
                                    cimg_instance,
                                    filename);
            }
          }
        }
      }

**Comment by dtschump** [comment]
Thanks for reporting, I'll check that today!

**Comment by sylvester328** [comment]
Sorry, I was fooled by the error messages.  It in fact works despite the message.  It will be great if the messages can be suppressed.

**Comment by dtschump** [comment]
The error message is actually displayed by the `system()` call.
To remove it we need a way to have 'silent' calls to system(), not sure if this is possible.

**Comment by sylvester328** [comment]
Just a thought:  How about add tests at the start of load_imagemagick_external()?

If full path given, we can check the existence of the binary, otherwise:

if (cimg::system("which convert > /dev/null"))
throw CImgIOException(_cimg_instance
"load_graphicsmagick_external(): ImageMagick not installed.",
cimg_instance);

**Comment by dtschump** [comment]
Ah, yes, but this won't work on Windows :)
Also, in this case, I guess that adding `>/dev/null` to the system("convert...") call will discard error messages too.

**Comment by sylvester328** [comment]
The nature of 'which' won't give surprising error message I suppose :)  It shows the path to the binary if it is found which is equally annoying so I put '/dev/null' just for this call.    Windows?...  who cares, kidding.  no experience on that.  May be it has something similar.

**Comment by dtschump** [comment]
I've written some code to add `>/dev/null 2&>1` to all systems calls in Linux, maybe that could help ?
Could you test with the version currently in git ?

**Comment by sylvester328** [comment]
No.  The message is still popping up.  It comes from popen call in line 50894.  Your changes dealing with cimg::system() couldn't suppress that.

**Comment by dtschump** [comment]
Ah OK, but if I add `>/dev/null 2&>1` in the string passed to `popen()`, then this will probably fix the problem, right ?

**Comment by sylvester328** [comment]
It doesn't seem to work and it also breaks the legitimate popen call. 

I see your code in imagemagick_path() trying to guess the path to the imagemagick binary, At the moment, if it couldn't find it, it simply set it to "convert" and hopefully it's there in the path env.  May be it makes sense to determine it is actually install at this point.

**Comment by dtschump** [comment]
So maybe this patch https://github.com/dtschump/CImg/commit/f9f6a9cdc505c9aed83ed0421402c461566cb429 could solve this issue ?

**Comment by sylvester328** [comment]
Look like that does the trick.  Thanks.
