### ISSUE TITLE
Compile for Raspberry Pi

### ISSUE THREAD

**Issue by renatorocci** [dtschump/CImg#153]
I wrote a slide show program that works correctly in ubuntu. 
Now I have a problem when I try to compile it for a Raspberry Pi where the slide show should run, the compiler does not find lX11:

$ arm-linux-gnueabi-g++ -o FOTOSHOWarm SHOW4.cpp -lX11 -lpthread
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: impossibile trovare -lX11
collect2: error: ld returned 1 exit status

Could you help me?

**Comment by leo07046219** [comment]
I have the same problem when I try CImg in my android cellphone.Cross-compiling X11 lib is a hard work。
http://blog.csdn.net/q1302182594/article/details/42028985 , you can try this blog .
I stuck in xtrans for the dependency of Xorg, and have no idea the relation between xorg  and android.

**Comment by aalbiol** [comment]
Try installing libx11 development packages
sudo apt-get install libx11-dev

**Comment by renatorocci** [comment]
I did it, but nothing changed ...

**Comment by renatorocci** [comment]
Finally  I succeed to compile directly on Raspberry
but running on Raspberry the program aborted with the following messages:
sh: 1: convert: not found
sh: 1: gm: not found
sh: 1: convert: not found
sh: 1: gm: not found
sh: 1: convert: not found
sh: 1: gm: not found
[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file 'Versione.jpg'.
terminate called after throwing an instance of 'cimg_library::CImgIOException'
what(): [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file 'Versione.jpg'.
Aborted

It seems that .jpg do not work with Raspberry?
