### ISSUE TITLE
compile errors visual c++ 6.0

### ISSUE THREAD

**Issue by kknasher** [dtschump/CImg#154]
I'm getting lots of "... not a member of 'std' " errors trying to compile the examples using visual c++ 6.0.
the home page says vc6 is ok but is that out of date now?

**Comment by kknasher** [comment]
it is here in FAQ 
http://cimg.eu/reference/group__cimg__faq.html#ssf12
and also implied here
http://cimg.eu/reference/group__cimg__overview.html 
in "How to compile".
thanks.

**Comment by dtschump** [comment]
Thanks, I've fixed these pages.
