### ISSUE TITLE
SHA-256 mismatch for CImg_2.0.4.zip

### ISSUE THREAD

**Issue by ilovezfs** [dtschump/CImg#155]
Homebrew users currently cannot install cimg due to a SHA-256 checksum mismatch for CImg_2.0.4.zip.

18 Sep 2017 the checksum was
5abe230585e784b85607bbca3e3d61e872309654f8c0dd59b677227d66120a27

Now it appears to be
50cdc91f0434364c55211f3578829514fe7ee30824e45094d15b24c5057766d3

Do you have any idea what happened here? To rule out malicious circumstances, we'll need to know why the file has changed before the checksum can be updated in Homebrew. Thanks!

**Comment by dtschump** [comment]
Silent release has been done, once again, because of a small fix.
Nothing malicious here.

**Comment by ilovezfs** [comment]
Thanks for confirming @dtschump :)
