### ISSUE TITLE
Local standard deviation

### ISSUE THREAD

**Issue by rschuste90** [dtschump/CImg#156]
Hi,
is there a function that can compute the local standard deviation for each pixel of an image like stdfilt in matlab or variance filter in Imagej?

Thank you!

**Comment by dahtah** [comment]
No, but it's easy to do. The variance equals E(x^2) - E(x)^2. This means the local variance can be computed using two box blurs: the box blur of the initial signal (m=E(x)), then the box blur of the squared signal (m2= E(x^2)). The local std. dev  equals sqrt(m2 - m^2)

**Comment by rschuste90** [comment]
Thank you for the answer, it's very helpful.
Do you know the difference between boxfilter() and blur_box()?

**Comment by dtschump** [comment]
My guess: `boxfilter()` should be able to estimate also the first and second derivatives of a smoothing box filter.

**Comment by rschuste90** [comment]
Ok, thank you.
