### ISSUE TITLE
segfault in shift method

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#158]
Hi David

The following code causes CImg to segfault:
```
#include <CImg.h>

using namespace cimg_library;
typedef cimg_library::CImg<double> CId;
int main()
{
  CId im(3,3);
  double s = 1.0/0.0;
  im.shift(s,s);
  return 1;
}
```
The issue was originally reported [here](https://github.com/dahtah/imager/issues/55)

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/CImg/commit/467ea41ea7f17988e4fcb7c5fd442c55046b0147 should fix this issue. Thanks for reporting.

**Comment by dahtah** [comment]
I confirm the issue is fixed. Thanks!
