### ISSUE TITLE
Construct CImg from multiplexed C-style array

### ISSUE THREAD

**Issue by tobybear** [dtschump/CImg#16]
In the documentation and the header file, there is a section on the most used methods for constructing a CImg. I think there is an error in the part about constructing images from C-style arrays:

- CImg<int> img(data_buffer,256,256); constructs a 256x256 greyscale image from a int* buffer data_buffer (of size 256x256=65536).
- CImg<unsigned char> img(data_buffer,256,256,1,3,false); constructs a 256x256 color image from a unsigned char* buffer data_buffer (where R,G,B channels follow each others).
- CImg<unsigned char> img(data_buffer,256,256,1,3,true); constructs a 256x256 color image from a unsigned char* buffer data_buffer (where R,G,B channels are multiplexed).

I think this is wrong as the 6th parameter does not define multiplex yes/no but rather if the CImg is shared or not. At least it always seems to expect non-multiplexed data at all time, right?

I have not found any function to construct a CImg directly from a C-Style array that contains the pixels as interleaved values (RGBRGB...), so I am currently copying the pixels manually in a loop. Recently, I stumbled upon the "load_raw" function that actually allows loading of either multiplexed or serialized pixel data, but only from file, not from memory. Looking into the sources, I saw that in multiplexed mode, it does a copy loop as well, so nothing gained here.

But it probably makes sense to at least correct the documentation (or enlight me in case I misunderstood something).

**Comment by dtschump** [comment]
That is correct indeed.
There is anyway a simple method to get an image from multiplexed buffer that uses the method `CImg<T>::permute_axes()` :  

    CImg<unsigned char> img(buffer,S,W,H);
    img.permute_axes("YZCX");

where S is the final spectrum() (so 3 for a RGB color image), W and H are the final width and height of the image.
I'll fix the doc asap. Thanks.

**Comment by tobybear** [comment]
Thank you very much for this quick answer and solution - I can confirm it works with permute_axes. :)
