### ISSUE TITLE
How to best convert to fixed format?

### ISSUE THREAD

**Issue by 93i** [dtschump/CImg#160]
I want to internally always use the format cimg&lt;float&gt; with 4 channels, how can i convert any format to that specific format? For example, when reading a jpeg, there are only 3 channels, as there is no alpha, but i want to work with it with 4 channels and its alpha set to 255

This is what i came up with, but it does not look like it is an efficiant way?

    const cimg_library::CImg<float> newImage = cimg_library::CImg("somefile.jpeg");
    cimg_library::CImg<float> outImage_ = std::move(newImage.get_resize(newImage.width(), newImage.height(), 1, 4, -1));
    auto * srcA = outImage_.data(0, 0, 0, 3);
    const auto pixels = newImage.width()*newImage.height();
    for (auto i = 0; i < pixels; ++i) {
    	*(srcA++) = 255.;
    }

is there a better way?

**Comment by StefRe** [comment]
does [this](https://stackoverflow.com/questions/32238522/set-default-value-for-alpha-in-cimg) work for you?

**Comment by 93i** [comment]
Yes it does, thank you very much
