### ISSUE TITLE
Gaussian blur not working as expected

### ISSUE THREAD

**Issue by casper** [dtschump/CImg#162]
I'm trying to see if CImg can duplicate the Photoshop Gaussian blur exactly, but I end up with an invalid image when using `is_gaussian = true`.

Test program:

```c++
CImg<unsigned char> image("lena.jpg");

// sigma, boundary_conditions, is_gaussian
image.blur(1.0, true, true);
image.save("lena_blur_gaussian.png");
```

Resulting image:

![lena_blur_gaussian](https://user-images.githubusercontent.com/25386/31855591-d0f6cb0c-b6b6-11e7-9419-dca41af8cbc6.png)

Any idea what went wrong? If I change `is_gaussian` to `false`, I get a properly blurred image, but this image does not match what Photoshop produces :(

**Comment by casper** [comment]
Never mind. The fix was to use `unsigned int`, instead of `unsigned char`. However this still does not duplicate the Photoshop effect. See difference image below:

![image](https://user-images.githubusercontent.com/25386/31855692-0c91613e-b6b9-11e7-80de-e4b90ea1999b.png)

**Comment by dtschump** [comment]
I was not able to reproduce your bug. What version of CImg did you use ?
With the current git master, the following source code works as expected : 

~~~~
#include "CImg.h"
using namespace cimg_library;

int main(int argc, char **argv) {

  CImg<unsigned char>
    _img("/home/dtschump/work/img/lena.bmp"),
    img = _img.get_normalize(0,255),
    img1 = img.get_blur(1,true,false),
    img2 = img.get_blur(1,true,true);

  (img,img1,img2).display();

  return 0;
}
~~~~
And I'm still keeping `unsigned char` pixel types for the image.
The input image is also 8bits / channels.

Maybe it's a bug that has already been corrected in recent versions?

**Comment by casper** [comment]
This was on git master (commit 419621b2b7fa0337963c16cc264ba08dc63f3974). 
Ubuntu 14.04, g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4.

Exact sample code used:

```c++
#define cimg_display 0
#include "CImg.h"
using namespace cimg_library;

int main() {
  CImg<unsigned char> image("lena.jpg");
  image.blur(1.0, true, true);
  image.save("lena_blur_gaussian.png");

  return 0;
}
```

Different values of sigma produces other results. For example 5.0 produces a black image.

**Comment by dtschump** [comment]
I see. I was able to reproduce the bug, I'm working on a fix.

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/CImg/commit/a0d371ac44455e7f5d56c8415186a675d3598749 should solve your issue. Could you please check and tell me if that is the case ?
Thanks !

**Comment by casper** [comment]
Works now, however it still differs from the Photoshop Gaussian blur. I think it's because CImg uses an optimized algo. Would be nice if CImg had a true Gaussian filter too. But seems the bug is fixed now in any case.

**Comment by dtschump** [comment]
There are plenty of different algorithms to blur an image with a gaussian blur, so it will be hard to replicate exactly what Photoshop does without knowing the algorithm it uses (which is impossible, as it's not an open-source software, so you'll never know :) ).
You can try also using `CImg<T>::convolve()` with a (discrete) gaussian kernel if you think this gives something more close to what PS does (I can't say).
Eventually, two calls to `CImg<T>::convolve()` with 1D gaussian kernels along 'x' and 'y' will be fast enough and is equivalent to a 2D gaussian blur.

**Comment by casper** [comment]
As far as I've been able to figure out PS uses a true Gaussian kernel and not an optimized algo like Box Blur or something like that, which try to approximate a Gaussian distribution in favor of speed. I don't know what CImg uses, but it looks like it's also an approximation algo (vanvliet?). 

Both ImageMagick and libvps\[1\]\[2\] are almost identical to the PS method. I think the small difference I found comes from the chosen precision. But you're right I haven't found a 100% match so far, and probably never will because of some minor internal representation differences (looks like rounding errors for example).

Perhaps I'll try and build my own kernel, if I can figure out how to do it :-/ In any case it's not a big issue, more like a slightly obsessive curiosity at this point, stemming from the fact that the PS Unsharp Mask is the best sharpening filter I've found so far, and it's using their Gaussian blur as the starting point. So I wanted to get that part right before I proceed with the rest.

\[1\]: https://github.com/jcupitt/libvips/blob/master/libvips/create/gaussmat.c#L95
\[2\]: https://github.com/jcupitt/libvips/blob/master/libvips/convolution/gaussblur.c

**Comment by casper** [comment]
> Eventually, two calls to CImg<T>::convolve() with 1D gaussian kernels along 'x' and 'y' will be fast enough and is equivalent to a 2D gaussian blur.

Can you explain why this is equivalent? Won't it become an approximation also, because you will not be convolving all the factors in the 2D matrix?

**Comment by dtschump** [comment]
Convolution by an isotropic 2D gaussian kernel is separable : 
https://blogs.mathworks.com/steve/2006/10/04/separable-convolution/

With any method you chose, you'll end up with an approximated result, as theoretically both the convolution and the gaussian kernels are expressed as continuous functions.
The fact they are discretized somewhere during the process makes the result not exact.

**Comment by casper** [comment]
Oh wow. That is super-cool. Thanks for the clarification.

**Comment by casper** [comment]
Ok I tried it with a Gaussian 21 point 1D normalized kernel with integrated midpoint values. The results were almost as good as with libvips, but not quite. 

My question is why does convolving with `is_normalized` as `true` produce a black image? My assumption was `is_normalized` should be `true` because the kernel is normalized, but perhaps I misunderstood. Test code:

```c++
int main() {
  float gd_2_21[] = {
    0.000001, 0.00001 , 0.000078, 0.000489, 0.002403, 0.009245, 0.027835, 0.065591,
    0.120978, 0.174666, 0.197413, 0.174666, 0.120978, 0.065591, 0.027835, 0.009245,
    0.002403, 0.000489, 0.000078, 0.00001 , 0.000001
  };

  CImg<float> gd_x(gd_2_21, 21, 1);
  CImg<float> gd_y(gd_2_21, 1,  21);

  CImg<unsigned char> image("lena.jpg");

  image.convolve(gd_x, true, true);  // <- produces black image, while convolve(gd_x/y); does not
  image.convolve(gd_y, true, true);  // <--| 
  image.save("lena_gb_convolved.png");
  return 0;
}
```

Second question: why is the result improved if I load the image with `CImg<float> image("lena.jpg");` instead?

**Comment by dtschump** [comment]
First question:
-------------------
Function argument `is_normalized` has nothing to do with the type of input kernel you give to the function.
When set to `true`, what is computed is not the classical convolution, but the 'normalized' convolution, defined by `res(x,y) = (sum_(p,q) I(x-p,y-q)*K(p,q))/(||K||*||NI(x,y)||)` where K is the kernel and NI the neighbor around point (x,y). This is basically used if you want to match a kernel with the local neighborhoods of your images (more useful with `CImg<T>::correlate()` to be honest).
This does not compute an usual convolution, and outputs values in range `[0,1]`, that's why your output image is black (you store the result with `unsigned char` pixel types).

Second question:
------------------------
I'm not surprised. Doing two consecutive convolutions and storing the intermediate result in `CImg<unsigned char>` means you'll lose some precision during the whole process.
I'd recommend always using (at least) `CImg<float>`  when you want to perform non-trivial calculus or filtering with image data, and eventually convert the result in `CImg<unsigned char>` only at the end. You won't lose too much precision doing that.

**Comment by casper** [comment]
Ok. That makes sense. Thanks. I got it working pretty much as I want now. Using floats and precomputed gaussian table, result is close enough to what I wanted.
