### ISSUE TITLE
Can't Get Demos to Compile

### ISSUE THREAD

**Issue by letthelightin** [dtschump/CImg#164]
I'm having trouble getting demos to compile.

I've read the setup under the website FAQ:

> Basically, you need to add these two lines in your C++ source code, in order to be able to work with CImg images :
> #include "CImg.h"
> using namespace cimg_library;

I'm using IDE Dev-C++ 5.11 with included compiler TDM-GCC 4.9.2 64-bit.

Any help would be greatly appreciated.

**Comment by dtschump** [comment]
What kind of trouble ? Any error messages ?

**Comment by letthelightin** [comment]
I suppose I should also point out that I'm new to using third party libraries. I've added the CImg directory to includes under Compiler Options>Directories.

The error message:
C:\Users\Q702\AppData\Local\Temp\ccfCW2MY.o	CImg_demo.cpp:(.text$_ZN12cimg_library11CImgDisplay5paintEv[_ZN12cimg_library11CImgDisplay5paintEv]+0xb7): undefined reference to `__imp_SetDIBitsToDevice'
C:\Users\Q702\Downloads\Waterfox\CImg_latest\CImg-2.1.1\examples\collect2.exe	[Error] ld returned 1 exit status


C:\Users\Q702\AppData\Local\Temp\ccUKaTpc.o	CImg_demo.cpp:(.text$_ZN12cimg_library11CImgDisplay5paintEv[_ZN12cimg_library11CImgDisplay5paintEv]+0xb7): undefined reference to `__imp_SetDIBitsToDevice'

**Comment by StefRe** [comment]
You must link your program against the gdi32 lib, typically with the -lgdi32 option on the command line. There should be an option in your projects settings in the IDE to include further libraries. There you'll have to include the gdi32 library.

**Comment by letthelightin** [comment]
Thanks a lot! That solved it. 

Was this information somewhere on the website? I'm trying to develop my programming skills, and a major part of that appears to be finding and interpreting documentation. 

Thanks again.

**Comment by StefRe** [comment]
> Was this information somewhere on the website?

--> see [here](http://cimg.eu/reference/group__cimg__overview.html#s3)
