### ISSUE TITLE
CImgBlob bug or not bug?

### ISSUE THREAD

**Issue by BernardLittau** [dtschump/CImg#167]
https://github.com/ihar/CImgBlob/blob/master/CImgBlob.cpp

CImgBlob.cpp line 94:
    // Border of single-pixel region
    if (1 == it->second.area) return blobs;

I changed this to:
    // Border of single-pixel region
    if (1 == it->second.area) continue;

Works better for me.  Maybe I should smooth my image a bot more :-)

**Comment by dtschump** [comment]
Hello. This seems to be a fork of CImg, with an additional file that is not in the original repository.
I suggest then to ask on the forked repo instead : https://github.com/ihar/CImgBlob/issues
At this point, I can't tell anything about this issue (I don't even know what this forked repository is about :) ).
