### ISSUE TITLE
Label doesn't work on unsigned int or unsigned long images

### ISSUE THREAD

**Issue by StefRe** [dtschump/CImg#170]
The following code yields a black image for image types `unsigned int` and `unsigned long`. It works as expected for `unsigned char` and all signed types (`int` and `long` as well as `char`, `short`, `float`, `double`)

```
#include "CImg.h"
using namespace cimg_library;

int main(int argc, char **argv) {

  CImg<unsigned long> img(100,100,1,1,0);

  const float one = 1;
  img.draw_circle(20,20,10,&one).draw_circle(50,50,20,&one);

  img.label().display();

}
```

**Comment by dtschump** [comment]
Thanks for reporting !
Commit https://github.com/dtschump/CImg/commit/d3151977c00b08cfe0d737d10c6363a91fbe82d9 should fix this bug.

**Comment by StefRe** [comment]
Works perfectly. As always I'm impressed by the speed you come up with the bug fix.
