### ISSUE TITLE
Any built-in minimum filter & maximum filter?

### ISSUE THREAD

**Issue by hubutui** [dtschump/CImg#171]
Hello. I'm trying to write a minimum filter & maximum filter. It seems that there is no such built-in method. So I need to write it myself. I'm considering how to do this. Here is my code:
```c++
void im::maximumFilter(const int &size)
{
    CImg<unsigned char> img("lenna.png");
    // slide window
    CImg<unsigned char> window(size, size);
    CImg<unsigned char> dest(img);

    cimg_forXY(img, x, y) {
        cimg_forXY(window, u, v) {
            window(u, v) = img(x + u, y + v);
        }
        // (x + (size - 1)/2, y + (size - 1)/2) is the middle pos
        // of the slide window
        // check if it's out of array boundary
        if (x + (size - 1)/2 < img.width() && y + (size - 1)/2 < img.height()) {
            dest(x, y) = window.max();
        }
    }

    dest.save_png("tmp.png");
}
```
But it's slow, how could I improve it? Or maybe CImg could add maximum filter & minimum filter.

**Comment by dtschump** [comment]
Max and min filters are usually known as the 'Dilate' and 'Erode' operators, and methods `CImg<T>::dilate()` and `CImg<T>::erode()` implement it.

**Comment by hubutui** [comment]
Thank you. I don't know max & min filters are known as dilate & erode. I thought dilate & erode are just morphological image processing, and have not relation to any other method.
