### ISSUE TITLE
Question about histogram equalization &  histogram matching (histogram specification).

### ISSUE THREAD

**Issue by hubutui** [dtschump/CImg#172]
I'm aware that there is a `equalize` & `get_equalize` for histogram histogram equalization. Is there any built-in function for histogram matching? Say I wanna adjust an image's histogram using another image as reference. Thank you.

**Comment by dtschump** [comment]
No specific method for that, but this should be fairly easy to do, as histogram transfer is basically achieved first by equalizing the image histogram, then applying the accumulated histogram function from the model to the image values.

**Comment by hubutui** [comment]
Thank you! I follow this [post](https://stackoverflow.com/questions/26763974/histogram-matching-of-two-images-without-using-histeq) to write one for my project. It works great. Would you considering add one `histmatch` to CImg?
