### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by renatorocci** [dtschump/CImg#173]
I have written a C++ program to perform a slide show that works perfectly sequentially and randomly on my ubuntu desktop and also on the target Raspberry Pi where the slide show should run.

I used CImg according to the suggestion you gave me  on May 23:

"This is what I've done quickly :
#include "CImg.h"
using namespace cimg_library;
int main(int argc, char **argv) {
  const char *const folder = cimg_option("-i",".","Path containing pictures");
  char pattern[1024];
  std::snprintf(pattern,1024,"%s/*.jpg",folder);
  const CImgList<char> filenames = cimg::files(pattern,true,0,true);

  CImgDisplay disp(1,1,0,0,1,1);
  cimglist_for(filenames,l) {
    const char
      *const filename = filenames[l],
      *const basename = cimg::basename(filename);
    const CImg<unsigned char> img(filename);
    disp.resize(cimg_fitscreen(img.width(),img.height(),1),0);
    disp.display(img).set_title(basename);
    if (disp.is_keyESC()) std::exit(0);
    cimg::wait(3000);
  }
  return 0;
}"

The program runs perfectly but the pictures are not displayed full screen as I would.
I presume that the reason depends from the resize disposition but I do not achieve the solution.
What I would is that the pictures were viewed (as Ubuntu Shotwell Photo Manager or Raspberry Image Viewer do) on full screen without deformations ... and if possible the void background of the screen were black.
I hope you can help me once again!
Renato Rocci

**Comment by StefRe** [comment]
See my [answer](https://stackoverflow.com/a/47733144/3944322) on SO.

**Comment by renatorocci** [comment]
I apologize for delay. Your suggestion works perfectly. Thank you very much.
