### ISSUE TITLE
wrong constant specs in CImg.h

### ISSUE THREAD

**Issue by devernay** [dtschump/CImg#174]
Older gcc compilers (such as 4.2.1) choke on these lines:
```
          fn1 = (cimg_uint64)1304969544928657U,
          fn2 = (cimg_uint64)806515533049393U,
```
with
```
./CImg.h:5863: error: integer constant is too large for 'unsigned long' type
./CImg.h:5864: error: integer constant is too large for 'unsigned long' type
```

changing U to LLU at the end of the constants fixes this on GCC, but I don't know if it is supported by older VS.

**Comment by dtschump** [comment]
According to https://stackoverflow.com/questions/14588997/llu-bad-suffix-on-number , LLU is not recognized everywhere (where `ULL` seems to be, at least on recent compilers !).
If `ULL` is working for you, then we can put this suffix for these number declarations.

**Comment by devernay** [comment]
go for `ULL`!

**Comment by dtschump** [comment]
Should be OK. Thanks for your report ;)
