### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by tiwawan** [dtschump/CImg#178]
I'd like to distribute my program using CImg.h without modification in the form of object code.
I think I need to show a copyright notice about CImg, but I couldn't find files such as COPYRIGHT or LICENSE.

Are there any sentence to be copied? ( something like copyright (c) - )
Or do I only need to show raw CeCiLL-C license agreement?

**Comment by tiwawan** [comment]
The Article 6.4 of CeCILL-C License says

> The Licensee expressly undertakes:

> 1. not to remove, or modify, in any manner, the intellectual property notices attached to the Software;

> 2. to reproduce said notices, in an identical manner, in the copies of the Software modified or not;

> 3. to ensure that use of the Software, its intellectual property notices and the fact that it is governed by the Agreement is indicated in a text that is easily accessible, specifically from the interface of any Derivative Software.

In my understanding, there are not "the intellectual property notices attached to the Software" in the CImg library, so I cannot reproduce it. According to 3., what I need to notice is that I used the CImg library and it is governed by CeCILL-C license.

Is my understanding correct?

**Comment by devernay** [comment]
Exactly, your software should mention somewhere (e.g. in an About dialog) that it's using CImg which is licensed under CeCILL-C.
You can see CeCILL-C as LGPL, with the addition of that article which is here because of the French law: in France, the author of an intellectual work such as a book, a movie, or a software, keeps his/her authorship forever, and must be mentioned in any derived work.

**Comment by tiwawan** [comment]
@devernay 
Thank you for your explanation.

So, in case of CImg, just mentioning CImg and CeCILL-C license like "This software is using CImg library (http://cimg.eu/) which is distributed under CeCILL-C license (http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.txt)" is enough and typical copyright notice like "Copyright (year) (author)" is not required to reproduce, right?

**Comment by devernay** [comment]
Exact

**Comment by tiwawan** [comment]
Now I understood, thank you!
