### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [dtschump/CImg#179]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by ZaMaZaN4iK** [comment]
https://github.com/bincrafters/conan-cimg

**Comment by crohkohl** [comment]
I prepared a recipe and a package. Info can be found here:

https://github.com/crohkohl/conan-cimg
