### ISSUE TITLE
Incomplete Type error when trying to build Hello World program in XCode

### ISSUE THREAD

**Issue by trmontgomery** [dtschump/CImg#181]
I was going through the tutorials for CImg and I tried to run the hello world program but I am getting this error: "Invalid use of incomplete type 'CImg<unsigned char>'"
<img width="876" alt="screen shot 2018-01-20 at 3 37 50 pm" src="https://user-images.githubusercontent.com/8525201/35187802-f478efd2-fdf7-11e7-9acc-c7873231855c.png">

Any ideas on how to proceed?

**Comment by StefRe** [comment]
You missed the variable name `img` and the trailing semicolon `;`. 

    CImg<unsigned char> img(640,400,1,3);
    unsigned char purple[] = { 255,0,255 };
    img.draw_text(100,100,"Hello World",purple);
    img.display("My first CImg code");
