### ISSUE TITLE
Error : Can't build the code with CImg.h in Xcode

### ISSUE THREAD

**Issue by gabinguo** [dtschump/CImg#186]
#include "CImg.h"

using namespace cimg_library;

    int main() {
        // Declare an image
        CImg<unsigned char> image; // Load an image file into it
        image.load("lena.ppm");
        // Declare a display and dispay the image into it
        CImgDisplay disp(image,"Image");
        // Wait for the display window to close
        while (!disp.is_closed()) { disp.wait();
        }
        return 0;
    
    }

![de92ccda-1398-4cf3-b9a9-5ee86c54e12a](https://user-images.githubusercontent.com/27879119/36931382-7b316c98-1eb4-11e8-9028-9c7affe99ed5.png)

Cant build in Xcode.

**Comment by gabinguo** [comment]
bump~

**Comment by mwPlouffe** [comment]
you're missing the X11 library needed to support displaying images.
