### ISSUE TITLE
Can't run code with CImg.h in Xcode

### ISSUE THREAD

**Issue by gabinguo** [dtschump/CImg#187]
********CODE************
#include "CImg.h"
using namespace cimg_library;

int main() {
    
    // Declare an image
    CImg<unsigned char> image;
    // Load an image file into it
    image.load("lena.ppm");
    
    // Declare a display and dispay the image into it
    CImgDisplay disp(image,"Image");
    
    // Wait for the display window to close
    while (!disp.is_closed()) {
        disp.wait();
    }
    
    return 0;
}

********ERROR***********
Undefined symbols for architecture x86_64:
  "_XAllocClassHint", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XCheckMaskEvent", referenced from:
      cimg_library::CImgDisplay::_events_thread(void*) in main.o
  "_XCheckTypedEvent", referenced from:
      cimg_library::CImgDisplay::_events_thread(void*) in main.o
  "_XCheckWindowEvent", referenced from:
      cimg_library::CImgDisplay::_handle_events(_XEvent const*) in main.o
  "_XCloseDisplay", referenced from:
      cimg_library::CImgDisplay::screen_width() in main.o
      cimg_library::CImgDisplay::screen_height() in main.o
  "_XCreateColormap", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XCreateImage", referenced from:
      cimg_library::CImgDisplay::_init_fullscreen() in main.o
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
      void cimg_library::CImgDisplay::_resize<unsigned char>(unsigned char, unsigned int, unsigned int, bool) in main.o
      void cimg_library::CImgDisplay::_resize<unsigned short>(unsigned short, unsigned int, unsigned int, bool) in main.o
      void cimg_library::CImgDisplay::_resize<unsigned int>(unsigned int, unsigned int, unsigned int, bool) in main.o
  "_XCreateSimpleWindow", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XCreateWindow", referenced from:
      cimg_library::CImgDisplay::_init_fullscreen() in main.o
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XDestroyWindow", referenced from:
      cimg_library::CImgDisplay::assign() in main.o
      cimg_library::CImgDisplay::_desinit_fullscreen() in main.o
  "_XFree", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XFreeColormap", referenced from:
      cimg_library::CImgDisplay::assign() in main.o
  "_XGetVisualInfo", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XGetWindowAttributes", referenced from:
      cimg_library::CImgDisplay::_init_fullscreen() in main.o
      cimg_library::CImgDisplay::_map_window() in main.o
      cimg_library::CImgDisplay::_handle_events(_XEvent const*) in main.o
      cimg_library::CImgDisplay::resize(int, int, bool) in main.o
  "_XGrabKeyboard", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XInternAtom", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XLookupString", referenced from:
      cimg_library::CImgDisplay::_handle_events(_XEvent const*) in main.o
  "_XMapRaised", referenced from:
      cimg_library::CImgDisplay::_init_fullscreen() in main.o
      cimg_library::CImgDisplay::_map_window() in main.o
  "_XMoveWindow", referenced from:
      cimg_library::CImgDisplay::move(int, int) in main.o
  "_XOpenDisplay", referenced from:
      cimg_library::CImgDisplay::screen_width() in main.o
      cimg_library::CImgDisplay::screen_height() in main.o
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XPutImage", referenced from:
      cimg_library::CImgDisplay::_init_fullscreen() in main.o
      cimg_library::CImgDisplay::_paint(bool) in main.o
  "_XQueryKeymap", referenced from:
      cimg_library::CImgDisplay::_handle_events(_XEvent const*) in main.o
  "_XResizeWindow", referenced from:
      cimg_library::CImgDisplay::_handle_events(_XEvent const*) in main.o
      cimg_library::CImgDisplay::resize(int, int, bool) in main.o
  "_XSelectInput", referenced from:
      cimg_library::CImgDisplay::_init_fullscreen() in main.o
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XSendEvent", referenced from:
      cimg_library::CImgDisplay::_paint(bool) in main.o
  "_XSetClassHint", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XSetInputFocus", referenced from:
      cimg_library::CImgDisplay::_handle_events(_XEvent const*) in main.o
  "_XSetWMProtocols", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XSetWindowColormap", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XStoreColors", referenced from:
      cimg_library::CImgDisplay::_set_colormap(unsigned long&, unsigned int) in main.o
  "_XStoreName", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XSync", referenced from:
      cimg_library::CImgDisplay::assign() in main.o
      cimg_library::CImgDisplay::_init_fullscreen() in main.o
      cimg_library::CImgDisplay::_map_window() in main.o
      cimg_library::CImgDisplay::_handle_events(_XEvent const*) in main.o
  "_XUngrabKeyboard", referenced from:
      cimg_library::CImgDisplay::_desinit_fullscreen() in main.o
  "_XUnmapWindow", referenced from:
      cimg_library::CImgDisplay::_handle_events(_XEvent const*) in main.o
  "_XVisualIDFromVisual", referenced from:
      cimg_library::CImgDisplay::_assign(unsigned int, unsigned int, char const*, unsigned int, bool, bool) in main.o
  "_XWindowEvent", referenced from:
      cimg_library::CImgDisplay::_init_fullscreen() in main.o
      cimg_library::CImgDisplay::_map_window() in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by SolarJuice** [comment]
#207 
I am experiencing the same issue as you did. Now I opened another issue as I see yours have no reply for months. Have you solved this problem already?

**Comment by dtschump** [comment]
By default CImg is enabling X11 display, so you need to have the X11 libraries installed to make it compile (and to get `CImgDisplay` working as expected).
If you don't need displays at all, just define `#define cimg_display 0` and the X11 dependency will vanish.

**Comment by SolarJuice** [comment]
I have just solved this problem without disabling the display function. See my post just a minute ago.
#207

**Comment by SolarJuice** [comment]
In my approach I made the X11 fully functional.
