### ISSUE TITLE
Issue draw_image not works or how to draw image at image ?

### ISSUE THREAD

**Issue by Karaulov** [dtschump/CImg#189]
How to find easy examples ??? In examples dir i found only incomprehensible crap :( 

How to download easy examples with code comments ?!!!

```
img<unsigned char> image ....  (256,256,1,4)
img<unsigned char> newimage....  (32,32,1,4)
...

img.draw_image(x,y, newimage) not works!  (bad color result)
```

after saving **img** to bmp( img.save("dump.bmp") ), i see nonsense result.

**Comment by Karaulov** [comment]
For example drawing BLUE image at RED image got result green

**Comment by Karaulov** [comment]
```

	for ( unsigned i = 0; i < drawheight; i++ )
	{
		unsigned char *rchannel = tmpRawImage.img.data( drawx, drawy + i, 0, 0 );
		unsigned char *gchannel = tmpRawImage.img.data( drawx, drawy + i, 0, 1 );
		unsigned char *bchannel = tmpRawImage.img.data( drawx, drawy + i, 0, 2 );
		unsigned char *achannel = tmpRawImage.img.data( drawx, drawy + i, 0, 3 );

		unsigned char *rchannel2 = tmpRawImage2.img.data( 0, i, 0, 0 );
		unsigned char *gchannel2 = tmpRawImage2.img.data( 0, i, 0, 1 );
		unsigned char *bchannel2 = tmpRawImage2.img.data( 0, i, 0, 2 );
		unsigned char *achannel2 = tmpRawImage2.img.data( 0, i, 0, 3 );

		std::memcpy( rchannel, rchannel2, drawwidth );
		std::memcpy( gchannel, gchannel2, drawwidth );
		std::memcpy( bchannel, bchannel2, drawwidth );
		std::memcpy( achannel, achannel2, drawwidth );
	}
```

This code works without color problems. But why i can't just draw_img at img ?????

**Comment by dtschump** [comment]
> In examples dir i found only incomprehensible crap :(
...
> This code may be works without color problems. But this is unsafe. Why i can't just draw_img at img ?????

You can, but please stay polite and friendly when asking questions.
Otherwise, there are high chances you won't get answers at all.

`img.draw_image(0,0, newimage)` is generally the way to go to draw `newimage` into the upper left corner of `img` (if those two images have the same number of channels). If this doesn't work for you then it's your probably due to something else (this method has worked for years, for hundred of people). Check twice your code, and look at the example files where this method is used.

**Comment by Karaulov** [comment]
Sorry, I do not know English, but Google translator can "slightly embellish" the message.

**Comment by Karaulov** [comment]
How to save image in rgba channel to disk for view, why CIMG not support TGA output ?

**Comment by Karaulov** [comment]
CImg<unsigned char> test( 256, 64, 1, 4, 0 );
	test.fill( color );
	test.save( "test.rgba" );

	fill with cimg vector rgba color not works ?

**Comment by Karaulov** [comment]
Sorry possible problem in drawing image at image with alpha channel in my code, and cimg don't support it.
