### ISSUE TITLE
how to open jpg format pictures?

### ISSUE THREAD

**Issue by 11wangwei11** [dtschump/CImg#19]
i have install imagesmagick software on my windows 7 computer, but the code stiil fail to load a jpg format picture.why?

**Comment by 11wangwei11** [comment]
this is the code:


#include  "CImg.h"
using  namespace  cimg_library;
int  main()  
{CImg<double>  img("1.jpg");
img.display();
return 0;}

**Comment by dtschump** [comment]
In which folder did you install ImageMagick ?

**Comment by 11wangwei11** [comment]
D:\ImageMagick-6.9.2-Q16

**Comment by 11wangwei11** [comment]
the installed file is "ImageMagick-6.9.2-3-Q16-x86-dll.exe"

**Comment by dtschump** [comment]
As this is not a standard folder for the installation, you need to specify it to CImg.
This should be as easy as adding this line of code before trying to load your jpeg file:

    cimg::imagemagick_path("D:\\ImageMagick-6.9.2-Q16\\convert.exe");

or something similar (you need to specify the exact path to the 'convert.exe' executable).

**Comment by 11wangwei11** [comment]
thank you, you are right.

**Comment by wongdu** [comment]
very helpful

**Comment by wongdu** [comment]
after installed the executable file in the default directory ,the jped picture loaded successfully!
