### ISSUE TITLE
How to speed up Cimg ?

### ISSUE THREAD

**Issue by gvee-s** [dtschump/CImg#191]
Hello,

I have a question related about speeding up cimg executions for image processing, so I think that this is a question more than an issue. Sorry but I don't know where to post general questions about Cimg.

I have an algorithm which mainly use some nested for loops as

```
cimg_forY(img, y)
{
   cimg_forX(img, x)
   {
       cimg_forC(img, c)
       // processing code 
   }
}
```
and one filtering function (using **convolve**) but I having speed problems on an embedded board (ARM 4 cores @ 1.2 GHz per core). For example, to convolve an image of 304128 pixels with a 7 * 7 kernel, the **convolve** execution time is about 200 ms, and the whole algorithm execution time is about 600 ms. For a 938496 pixels image the whole execution time of the algoritm is more than 2 seconds.

Is there some tips & trick to improve the speed of the code with Cimg ? 
Thanks.

**Comment by dtschump** [comment]
Two things to check:
- Have you set the max optimization flags when compiling. I've heard in the past some people complaining about the speed of CImg functions, but who compiled with default flag '-O1'. CImg supports '-Ofast' for g++.
- In case of multi-core, you can enable OpenMP, by defining macro 'cimg_use_openmp'. Then you can use openMP `pragma` to parallelize your loops when possible. Most CImg methods use such OpenMP optimizations, and when OpenMP is enabled, this makes a big difference.

**Comment by devernay** [comment]
Does your arm board have hardware for floating point computation? Many embedded processors don't. Le 22 mars 2018 21:04, gvee <notifications@github.com> a écrit :Hello,
I have a question related about speeding up cimg executions for image processing, so I think that this is a question more than an issue. Sorry but I don't know where to post general questions about Cimg.
I have an algorithm which mainly use some nested for loops as
cimg_forY(img, y)
{
   cimg_forX(img, x)
   {
       cimg_forC(img, c)
       // processing code 
   }
}

and one filtering function (using convolve) but I having speed problems on an embedded board (ARM 4 cores @ 1.2 GHz per core). For example, to convolve an image of 304128 pixels with a 7 * 7 kernel, the convolve execution time is about 500 ms, and the whole algorithm execution time is about 600 ms. For a 938496 pixels image the whole execution time of the algoritm is more than 2 seconds.
Is there some tips & trick to improve the speed of the code with Cimg ?
Thanks.

**Comment by gvee-s** [comment]
Hello,

Thank you for your interest. Please notice that the **5**00 ms was an typing error. It's 200 ms, but it's still a big delay, I think.

The processor is an ARM Cortex A-53 with Floating point unit and SIMD NEON support:
https://developer.arm.com/products/processors/cortex-a/cortex-a53

I have enabled `-Ofast` and at the time of writing the first post also the `-03` and `-ftree-vectorize` options but it doesn't help a lot. I though to rewrite my code using SIMD instructions, but rewriting the whole Cimg code should be painfull..

In particular, what openmp `pragma` do you suggest ?
Regards

**Comment by gvee-s** [comment]
Hello, 
I noticed that using openmp (enabling it with `-fopenmp`) the execution of the convolution is even slower.
Do you have any idea why this happens ?
Regards.

**Comment by gvee-s** [comment]
The issue was related to non planar (unuseful) image processing, so the non optimized pixel access was slowing the program execution.
