### ISSUE TITLE
Can you split the big CImg.h file to separate smaller .h and .cpp files

### ISSUE THREAD

**Issue by likev** [dtschump/CImg#193]
Yes, It is true that having a single header file has plenty of advantages.

But I can't view the code in GitHub.
![Sorry about that, but we can’t show files that are this big right now.](https://user-images.githubusercontent.com/3146974/38792862-9782393c-4181-11e8-9d5c-4f6c6291214c.png)

And I can't copy the permalink of lines of code to discuss with others like this:
https://github.com/dtschump/CImg/blob/8761ce483600ccbbea05a14b18d916744f3580af/examples/captcha.cpp#L105-L109

**Comment by dtschump** [comment]
Honestly, I think this is a github-related issue (maybe you could ask them to allow the viewing of bigger files). I don't imagine splitting `CImg.h` (which would imply quite a lot of work, for no advantages), just to be able to view it on github.

**Comment by likev** [comment]
I have modularized the CImg.h using `gpt-5.3-codex` https://github.com/likev/CImgModule/tree/work-on-plan-3.md

**Comment by dtschump** [comment]
What problem does it solve?
How can you ensure gpt did a decent work without introducing bugs?
