### ISSUE TITLE
How to resize a raw NV12 frame ?

### ISSUE THREAD

**Issue by gvee-s** [dtschump/CImg#195]
Hi !
I would need to resize a NV12 raw frame without changing pixel format.
I know that the following code
```
    // load raw of 1280 x 720 (size is 1280 * 720 * 3 / 2)
    CImg <uint8_t> nv12rawInput;
    nv12rawInput.load_raw(argv[1], 1280, 1080);
    nv12rawInput.resize(1280, 728);
```
cannot give the correct results due to the separate planes of the NV12 pixel format.

The only way I see it possible with CImg is to separate the planes into 2 different images, resize each separately and then join them. Sounds like it could work.

But maybe there is another straightforward method ?
Do you have any suggestion about how to do it using CImg functions ? 

Thank you.
Regards,
Simon

**Comment by dtschump** [comment]
I'm not familiar with NV12, but if I understand that page well (http://paulbourke.net/dataformats/nv12/), then NV12 is just a particular case of raw `.yuv` file with 4:2:0 chroma subsampling.
If this is the case, then something like : 
~~~~
  img.load_yuv("image.nv12",Width,Height,420);
  img.resize(1280,600,1,3,3);  // linear interpolation
  img.save_yuv("image.nv12",420);
~~~~
should work.

**Comment by gvee-s** [comment]
One strange thing I noticed is that if I load the NV12 file as you suggest, the image size is equal to the equivalent RGB size, even setting the yuv2rgb argument to false.

If the image is 1280  * 720, the NV12 size should be 1280 * 720 * 3/2 (AFAIK).
But the load_yuv function sets the image size to 1280 * 720 * 3.

Regards,
Simon

**Comment by gvee-s** [comment]
This code seems to work fine:
```
    CImg <uint8_t> nv12rawInput;
    // 720 * 3/2 = 1080
    nv12rawInput.load_raw(argv[1], 1280, 1080);
    // 736 * 3/2 = 1104
    nv12rawInput.resize(1280, 1104, 1, 1, 1);
    nv12rawInput.save_raw("nv12_resized.raw");
```

**Comment by gvee-s** [comment]
Update: the previous code seems to work fine with small resizment.

This code works better: https://www.codeproject.com/Tips/691062/Resizing-NV-image-using-Nearest-Neighbor-Interpo

**Comment by zyc4me** [comment]
@gvee-s 
Update: the previous code seems to work fine with small resizment.

This code works better: https://www.codeproject.com/Tips/691062/Resizing-NV-image-using-Nearest-Neighbor-Interpo

the  bilinear scale in this code can not work well when then to get the uv result，can you help me？
