### ISSUE TITLE
Saving images to memory buffers

### ISSUE THREAD

**Issue by auxiliary** [dtschump/CImg#196]
Is there currently a way (or will there be in the near future) to save say a PNG or a JPG image into a memory buffer instead of a file? 

This can be very useful if one is using CImg behind a web service and would like to return image bytes.

**Comment by gvee-s** [comment]
Hello,
I had to deal the same problem just this week-end.
Based on the code for libjpeg, you can write to a memory buffer using a custom function, using
`uint8_t *data_buffer = NULL;
long unsigned int data_buffer = NULL;
// set up struct jpeg_compress_struct and struct jpeg_error_mgr
// and then
jpeg_mem_dest(&cinfo, &data_buffer, &data_buffer);`
Regards.
