### ISSUE TITLE
Problem with libx.so

### ISSUE THREAD

**Issue by VaperDeKin** [dtschump/CImg#20]
Hello. I'm building a tool that should work on the machine without X server. The tool just generates some simple colored shapes.
I'm using cmake to build it. The problem that when I', running it on the target machine, it says:
"error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory"
Does that means any tool that use CImg, require X Server installed?
How can I disable libX11.so requirement? I don't use any windows in that tool.

**Comment by dahtah** [comment]
Use #define cimg_display 0 or the equivalent compiler flag. That should 
do it, I think
