### ISSUE TITLE
Support for color space retrieval of file

### ISSUE THREAD

**Issue by stijnfrishert** [dtschump/CImg#200]
CImg works great for loading in image files, but afaik there is currently no way to know whether the loaded data is in RGBA/CMYK/etc. apart from the channel count. When uploading the image data to the GPU like with OpenGL, this is necessary information.

Would it be possible to add this to CImg?

(Linking to [this](https://stackoverflow.com/questions/50374103/how-do-you-retrieve-the-colour-space-with-cimg-of-an-image-loaded-with-cimg/50374282?noredirect=1#comment87788209_50374282) StackOverflow post for reference.)

**Comment by kar-dim** [comment]
Hello, can I ask if this feature exists or is it not planned? I also cannot find a method to retrieve the colorspace in cimg 3.5, only some conversion methods that assume we know the colorspace beforehand. Thanks!

**Comment by dtschump** [comment]
Not planed indeed.
Sorry about that.
