### ISSUE TITLE
Unexpected results when loading JPEG photos

### ISSUE THREAD

**Issue by ZM-J** [dtschump/CImg#202]
Hi everyone.
I tried to load my JPEG photos in my cellphone using CImg with LibJpeg library. Because of inaccurate gravity sensors in my cellphone, I had to rotate the images 90° many times in my cellphone or using photos app in win10.
However, I just loaded these photos with CImg and store them in an another directory, but all I got are photos before rotating, i.e., all rotation I did was in vain.
I have no idea to explain this phenomenon. Could anyone help me?

**Comment by dtschump** [comment]
Rotation angle is sometimes stored in the file metadata, which are not parsed by the JPG reader of CImg. You can still use `img.rotate(90)` to fix this if necessary.
