### ISSUE TITLE
how to calculate text dimension

### ISSUE THREAD

**Issue by Magallo** [dtschump/CImg#204]
I'mtrying to use the draw_text() method. My purpose is draw a text centered horizontally at the top of the image. To do this I would need a way to calculate the size (width and height) of the text I'm going to draw, just to calculate the correct x position to start drawing.

Is there something similar? I tried searching the documentation but I wasn't able to find anything about. A sort of get_text_size() method which returns both the width and the height of a specific text in a specific font or font height.

**Comment by dtschump** [comment]
Yes, there is a trick for this.
Drawing your text on an empty image will actually expand the image size enough to contain the text. Then you can get the width/height of the resulting image, and draw your text again on your final image at the correct location `(w - wt)/2, (h-ht)/2`.
where `w,h` is the size of your canvas, and `wt,ht` the size of your text image.

**Comment by Magallo** [comment]
Thanks! It works like a charm!

**Comment by Magallo** [comment]
It works! Perfect! Thank you a lot! In any case I would suggest to add this kind of information in the somewhere documentation. Thanks again for the support!
