### ISSUE TITLE
can't use the draw_rectangle overloaded to draw outlined 2d rectangle

### ISSUE THREAD

**Issue by Magallo** [dtschump/CImg#205]
I'm trying to use the draw_rectangle() method to draw an outlined 2d rectangle (draw only borders, no filled) but I'm not able to use it successfully. I am referring to http://cimg.eu/reference/structcimg__library_1_1CImg.html#a988dfaa2fefd6715358c8c32467247be

How it is supposed to call this? What the paramer 'pattern' stands for? What are the possible values and meaning?

**Comment by dtschump** [comment]
`pattern` is a 32bits integer whose bits defines the hatching type. So basically for a plain line, use `~0U` (equivalent to `0xFFFFFFFF`). If you set it to `0`, there won't be any drawn line at all.

**Comment by Magallo** [comment]
Thanks, it works! Sorry for my questions here, but I don't know  where to ask otherwise.
