### ISSUE TITLE
how to stretch/shrink an image on another

### ISSUE THREAD

**Issue by Magallo** [dtschump/CImg#206]
I create a new image on memory and I start drawing on it.

On this image I draw several primitives (lines, rectangles and so on) but I want also to draw an input image loaded from disk. When I do this, the resulting output image shows the input 'red' filtered' for some stange reasons. Do you have an idea why? I show you the result in a screenshot and also the code:

```
CImg<unsigned char> dst(800, 800, 1, 3);
CImg<unsigned char> src("sfondo.png");
dst.draw_image(10, 10, src);
```

If I use "sfondo.png" dst (once saved on disk) shows the 'src' image starting at pixel 10, 10 (as expected). However the image is 'red filtered', don't know why.

Is it possible to publish some screenshot here? I would like to show you what I mean with 'red filtered'.

Second problem regarding the draw_image() method. When I draw the input image, I would like to draw it not keeping the original size of input image, but I want to specify start x/y and end x/y of destination so that the operation could eventually stretch or shrink the input image when drawn on the destination image.

something similar to:

`dst.draw_image(10, 10, 100, 100, src);`

so that src image is stretched inside dst having size 90x90 (from 10x10, to 100x100).

How can I do this?

**Comment by Magallo** [comment]
This is "sfondo.png"

![sfondo](https://user-images.githubusercontent.com/19425083/40846081-d9ba550e-65b8-11e8-82ea-aba8cdf035ed.png)

When using this as 'src' the output of 'dst' looks like this

![dst](https://user-images.githubusercontent.com/19425083/40846174-1f83937a-65b9-11e8-8316-fa0987cd63ea.png)

If I use a different input image, as example this one called sfondo2.png

![sfondo_2](https://user-images.githubusercontent.com/19425083/40846200-307ffeac-65b9-11e8-90cd-c84f5ead1e21.png)

In this case the output is correct (apart the stretching problem).

![dst_2](https://user-images.githubusercontent.com/19425083/40846333-95283522-65b9-11e8-9b3e-2bf597a9dae4.png)

**Comment by dtschump** [comment]
> When I do this, the resulting output image shows the input 'red' filtered' for some stange reasons. Do you have an idea why?

Your image has probably only one channel, and if you draw it in a multi-channel image (e.g. color image), then it will appear only in the first channel (red).
Just resize its number of channels to 3 before drawing it, with `img.resize(-100,-100,-100,3)`.

WIth the same idea, if you want to stretch the image before drawing it, then just resize it before, with method `img.resize(new_W,new_H,1,3)`.

**Comment by Magallo** [comment]
It works!!!! Both the resize to 3 channels and the resize before calling the draw_image() method for stretching/shrinking it!!! Thanks a lot!!!
