### ISSUE TITLE
Example odykill aborts

### ISSUE THREAD

**Issue by HongxuChen** [dtschump/CImg#209]
Not a big issue, but annoying.

Steps to reproduce:
1. compile with `make linux`
2. run `./odykill` and select one of the "weapons"; and then close the app.

Behavior:
It exits with the following message:
```


 YOUR SCORE : 1


double free or corruption (!prev)
[1]    17460 abort      ./odykill
```
```
$ echo $?
134
$ uname -a
Linux CSL-H5 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dtschump** [comment]
Looks like I incorrectly used shared images to define masks.
Does the commit  https://github.com/dtschump/CImg/commit/b98cdb4242f60a09d815414b7d8bcc35416cd920 fix the issue for you ?

**Comment by HongxuChen** [comment]
It fixes!
