### ISSUE TITLE
CImg<float>::assign(): Failed to allocate memory

### ISSUE THREAD

**Issue by HongxuChen** [dtschump/CImg#210]
We foun with our fuzzer a suspicious exception at CImg.h:11393 (fa8622b) when running `image2ascii -i $FILE`.

[memory_CImg.h:11393_1.txt](https://github.com/dtschump/CImg/files/2130802/memory_CImg.h.11393_1.txt)

```
$ ../../../CImg/examples/image2ascii -i memory_CImg.h:11393_1.txt
terminate called after throwing an instance of 'cimg_library::CImgInstanceException'
  what():  [instance(0,0,0,0,(nil),non-shared)] CImg<float>::assign(): Failed to allocate memory (192.0 Gio) for image (4294967293,4,1,3).
[1]    11468 abort      ../../../CImg/examples/image2ascii -i memory_CImg.h:11393_1.txt
```

[memory_CImg.h:11393_2.txt](https://github.com/dtschump/CImg/files/2130803/memory_CImg.h.11393_2.txt)
```
$ ../../../CImg/examples/image2ascii -i memory_CImg.h:11393_2.txt
terminate called after throwing an instance of 'cimg_library::CImgInstanceException'                                                                                                         
  what():  [instance(0,0,0,0,(nil),non-shared)] CImg<float>::assign(): Failed to allocate memory (336144.0 Gio) for image (7003,4294967204,1,3).
[1]    25320 abort      ~/FOT/CImg/examples/image2ascii -i memory_CImg.h:11393_2.txt 
```

I was expecting that the program to recognize that these files are *not* images and throw an exception `CImg<float>::load(): Failed to recognize format of file ...`.
```
$ file memory_CImg.h:11393_1.txt
memory_CImg.h:11393_1.txt: ASCII text
$ file memory_CImg.h:11393_2.txt
memory_CImg.h:11393_2.txt: data
```
(Please ignore `.txt` in the file name since GitHub does not allow file with other suffixes to be uploaded.)

**Comment by HongxuChen** [comment]
These two files will hang `image2ascii`.

[hang_1.txt](https://github.com/dtschump/CImg/files/2130815/hang_1.txt)
[hang_2.txt](https://github.com/dtschump/CImg/files/2130816/hang_2.txt)

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/CImg/commit/4d54d452896fdf9347af68d3854f98f4986eea4c should fix the first case.
I don't get an error in the second case (hang2_txt). This file actually looks like a 3d PBM (PINK extension), and CImg seems to load the file without errors. I'll double check tomorrow, but right now I don't get any issues with it.

**Comment by dtschump** [comment]
EDIT: I got the issue with the second case, but not `hang2_txt`, but `memory_CImg.h:11393_2.txt`.
Working on a fix...

**Comment by dtschump** [comment]
Seems that my previous commit also fixes the second case.
