### ISSUE TITLE
build errors when using version 2.3.6 of the lib on CentOS 5

### ISSUE THREAD

**Issue by Magallo** [dtschump/CImg#213]
Hi all,
I have used a custom version of the library for several months. It was a version 2.2.3 with some modifications (see https://github.com/dtschump/CImg/issues/203 for details).

Now I have been trying updating my program using a newer version of the library. I just downloaded the latest which is 2.3.6 and I got build errors.

The system is a CentOS release 5.10 (Final) and g++ gcc version 4.1.2 20080704 (Red Hat 4.1.2-55). 

Here's the errors:

> /usr/local/CImg/CImg-2.3.6/CImg.h: In function ‘double cimg_library::cimg::acosh(double)’:
> /usr/local/CImg/CImg-2.3.6/CImg.h:5301: error: ‘acosh’ is not a member of ‘std’
> /usr/local/CImg/CImg-2.3.6/CImg.h: In function ‘double cimg_library::cimg::asinh(double)’:
> /usr/local/CImg/CImg-2.3.6/CImg.h:5310: error: ‘asinh’ is not a member of ‘std’
> /usr/local/CImg/CImg-2.3.6/CImg.h: In function ‘double cimg_library::cimg::atanh(double)’:
> /usr/local/CImg/CImg-2.3.6/CImg.h:5319: error: ‘atanh’ is not a member of ‘std’
> /usr/local/CImg/CImg-2.3.6/CImg.h: In function ‘double cimg_library::cimg::log2(double)’:
> /usr/local/CImg/CImg-2.3.6/CImg.h:5333: error: ‘log2’ is not a member of ‘std’
> gmake[2]: *** [build/Debug/GNU-Linux/encode.o] Error 1
> ................
> gmake[1]: *** [.build-conf] Error 2
> 
> BUILD FAILED (exit value 2, total time: 3s)
> 

Thanks for your help.

**Comment by heckflosse** [comment]
@Magallo gcc 4.1.2 ? That's from 2007, more than 10 years old...

**Comment by Magallo** [comment]
Se have sone legacy installation from some customers that use centos 5 and that is the gcc provided so Inwonder if it could be possibile to use the library with it.

**Comment by dtschump** [comment]
You should try with the latest version **2.4.0** available from the CImg web site, I think this issue has been fixed in the new version.

**Comment by Magallo** [comment]
I sill try and I’ll let you know. Thanks!
