### ISSUE TITLE
instantiating CImg<bool> fails for a C++17

### ISSUE THREAD

**Issue by Bigpet** [dtschump/CImg#219]
The operators ++ and -- were deprecated for bools in C++11 and completely removed in C++17

This means that `CImg<bool>` can no longer be instantiated on a C++17 compliant compiler

Instead of unconditionally defining the operators like this
```C++ 
    CImg<T>& operator++() {
      if (is_empty()) return *this;
      cimg_openmp_for(*this,*ptr + 1,524288);
      return *this;
    }

    CImg<T> operator++(int) {
      const CImg<T> copy(*this,false);
      ++*this;
      return copy;
    }
```

They can be excluded for bools as follows (including <type_traits> for std::is_same and enable_if might be necessary ):
```C++ 
    template<typename U=T>
    std::enable_if<!std::is_same<U,bool>::value,CImg<T>&>::type operator++() {
      if (is_empty()) return *this;
      cimg_pragma_openmp(parallel for cimg_openmp_if(size()>=524288))
      cimg_rof(*this,ptrd,T) ++*ptrd;
      return *this;
    }

    template<typename U=T>
    std::enable_if<!std::is_same<U,bool>::value,CImg<T>>::type operator++(int) {
      const CImg<T> copy(*this,false);
      ++*this;
      return copy;
    }
```

or I guess to keep backwards-compatibility with C++98 

```C++
#if cimg_use_cpp11==1
    template<typename U=T>
    std::enable_if<!std::is_same<U,bool>::value,CImg<T>&>::type 
#else
    CImg<T>&
#endif
    operator++() {
      if (is_empty()) return *this;
      cimg_pragma_openmp(parallel for cimg_openmp_if(size()>=524288))
      cimg_rof(*this,ptrd,T) ++*ptrd;
      return *this;
    }

#if cimg_use_cpp11==1
    template<typename U=T>
    std::enable_if<!std::is_same<U,bool>::value,CImg<T>>::type 
#else
    CImg<T>
#endif
    operator++(int) {
      const CImg<T> copy(*this,false);
      ++*this;
      return copy;
    }

```

**Comment by dtschump** [comment]
That's interesting. Thanks.

But, there is something I don't understand anyway.
When you say
> This means that CImg<bool> can no longer be instantiated on a C++17 compliant compiler

I don't see any `boolean++` anywhere in the current CImg code. I've tried compiling
~~~
 CImg<bool> img(200,200,1,1,false);
 ++img;
~~~
with C++17 enabled, without any issue, while I've indeed verified that
~~~
  bool a = false;
  a++;
~~~
gives an error message:
~~~
toto.cpp: In function ‘int main(int, char**)’:
toto.cpp:16:4: error: use of an operand of type ‘bool’ in ‘operator++’ is forbidden in C++1z
~~~
(I'm using `g++ v.7.4.0`).

Could you tell me how you got an error when compiling ?

**Comment by Bigpet** [comment]
the bool ++ is in `++*ptrd;` and the error I got was with msvc from VS2017 with /std:c++17

    error C2675: unary '++': 'cimg_library::CImg<bool>' does not define this operator or a conversion to a type acceptable to the predefined operator

Clang 5 with --std=c++17 says

    error: ISO C++17 does not allow incrementing expression of type bool [-Wincrement-bool]

Gcc 7.4 with --std=c++17 says

    error: use of an operand of type 'bool' in 'operator++' is forbidden in C++1z

**Comment by Bigpet** [comment]
Oh, I think it might just be me using an older version of CImg that still had the `++*ptrd` which seems to be replaced now
