### ISSUE TITLE
errors on Mac OS x

### ISSUE THREAD

**Issue by juraev** [dtschump/CImg#223]
Couldn't open images on Mac OS X. And get errors like that:
`g++ -L/usr/ -L/usr/X11/include/ -o "line_segmentation"  ./src/linesegmentation.o ./src/main.o   
Undefined symbols for architecture x86_64:
  "_png_create_info_struct", referenced from:
      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

      cimg_library::CImg<unsigned char>::_save_png(__sFILE*, char const*, unsigned int) const in linesegmentation.o

  "_png_create_read_struct", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_create_write_struct", referenced from:

      cimg_library::CImg<unsigned char>::_save_png(__sFILE*, char const*, unsigned int) const in linesegmentation.o

  "_png_destroy_read_struct", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_destroy_write_struct", referenced from:

      cimg_library::CImg<unsigned char>::_save_png(__sFILE*, char const*, unsigned int) const in linesegmentation.o

  "_png_get_IHDR", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_get_valid", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_init_io", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

      cimg_library::CImg<unsigned char>::_save_png(__sFILE*, char const*, unsigned int) const in linesegmentation.o

  "_png_read_end", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_read_image", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_read_info", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_read_update_info", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_set_IHDR", referenced from:

      cimg_library::CImg<unsigned char>::_save_png(__sFILE*, char const*, unsigned int) const in linesegmentation.o

  "_png_set_expand_gray_1_2_4_to_8", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_set_filler", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_set_gray_to_rgb", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_set_longjmp_fn", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

      cimg_library::CImg<unsigned char>::_save_png(__sFILE*, char const*, unsigned int) const in linesegmentation.o

  "_png_set_palette_to_rgb", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_set_sig_bytes", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_set_tRNS_to_alpha", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_sig_cmp", referenced from:

      cimg_library::CImg<unsigned char>::_load_png(__sFILE*, char const*, unsigned int*) in linesegmentation.o

  "_png_write_end", referenced from:

      cimg_library::CImg<unsigned char>::_save_png(__sFILE*, char const*, unsigned int) const in linesegmentation.o

  "_png_write_image", referenced from:

      cimg_library::CImg<unsigned char>::_save_png(__sFILE*, char const*, unsigned int) const in linesegmentation.o

  "_png_write_info", referenced from:

      cimg_library::CImg<unsigned char>::_save_png(__sFILE*, char const*, unsigned int) const in linesegmentation.o

ld: symbol(s) not found for architecture x86_64`

**Comment by juraev** [comment]
Please, respond

**Comment by devernay** [comment]
add `-lpng -lz` to the linking command-line

**Comment by juraev** [comment]
> add `-lpng -lz` to the linking command-line

Thanks. 
Another question. What should I do if I want my program could handle any types of images(jpeg, bmp, ...), not only png.

**Comment by dtschump** [comment]
compile with appropriate flags : `-Dcimg_use_jpeg -ljpeg`.
.bmp file is natively supported (partially).
