### ISSUE TITLE
Add constructor that accepts a permute_axes like string that describes axes ordering of supplied values

### ISSUE THREAD

**Issue by MBraedley** [dtschump/CImg#224]
It is common for color image data to be stored in an interleaved array, like RGBRGBRGB...

The library would be easier to use, and the software written with it more maintainable, if there was a constructor that took the axes order in as an argument, and keep the order of the axes arguments consistent.  For a 2D RGB image, this could look something like this: `CImg image(data, "cxyz", width, height, 1, 3);`.  The constructor would then call `permute_axes` to get the data into its internal format.  This might also require an "`unpermute_axes`" method for when the data is retrieved, returning it to the original interleaved format.

This improves maintainability of the software using the library, as any time you use an interleaved format, a comment is needed explaining why you didn't supply the axes in the same order as the documentation, and comments explaining the order for the two `permute_axes` calls.  It adds unnecessary mental work, which means it's more prone to mistakes, especially in maintenance phases of development.

**Comment by dtschump** [comment]
That's a good idea indeed. Will think about it.

**Comment by dtschump** [comment]
I've added a new constructor
~~~
    template<typename t>
    CImg(const t *const values, const unsigned int size_x, const unsigned int size_y,
         const unsigned int size_z, const unsigned int size_c,
         const char *const axes_order);
~~~
and its associated `assign()` method.

Can be used for instance like this, to construct an image from an interleaved memory buffer (RGBRGBRGB...):
~~~~
  CImg<float> img(pixel_data,512,512,1,3,"cxyz");
~~~~
