### ISSUE TITLE
sort_eigenvalues used but undefined in v.2.5.0

### ISSUE THREAD

**Issue by thierry-FreeBSD** [dtschump/CImg#225]
When lapack is enabled, compilation fails, caused by the undefined variable sort_eigenvalues.
Just removing the line is sufficient:

```
--- CImg.h.orig 2019-03-10 14:46:23.000000000 +0100
+++ CImg.h      2019-03-14 21:46:11.209513000 +0100
@@ -26529,7 +26529,6 @@
           cimg_forXY(vec,k,l) vec(k,l) = (T)(lapA[(N - 1 - k)*N + l]);
         } else { val.fill(0); vec.fill(0); }
         delete[] lapA; delete[] lapW; delete[] WORK;
-        sort_eigenvalues = false;
 #else
 
        val.assign(1,_width);
```

**Comment by dtschump** [comment]
Ah Indeed, thanks for noticing this.
I've also fixed a small bug in `CImg<T>::symmetric_eigen()`. Sorry for the double release

**Comment by dtschump** [comment]
I've done some new modifications, so I'll release CImg 2.5.1 in a few hours.
