### ISSUE TITLE
how to compile CImg with OpenMP support using MSVC2017

### ISSUE THREAD

**Issue by uxhub** [dtschump/CImg#227]
Hi all,

Given the incompatibility between OpenMP4.5 (that CImg uses) and MSVC2017 (see https://stackoverflow.com/questions/43318137/using-openmp-3-4-in-visual-studio-2017), is there really no way to compile last CImg versions by using OpenMP with MSVC ? 
What should be done to keep the CImg portability without leaving VS compiler ?
Any advice will be appreciated !

Sincerely

**Comment by dtschump** [comment]
I've done some modifications recently, to allow the compilation of CImg with OpenMP 3.
I guess this should work now.

**Comment by uxhub** [comment]
I will have a try and come back with confirmations.
Thank you for your efforts !
Regards,

**Comment by dtschump** [comment]
Good to know, thanks for your feedback !
I'm closing the issue then.
