### ISSUE TITLE
how to properly handle transparency of input png files

### ISSUE THREAD

**Issue by Magallo** [dtschump/CImg#228]
Hi all, I have some problems understanding how to properly manage input files with transparency (for example png images).

I tried with a very basic and simple example. I just load a file into a CImg object, just resize to 200x200 and save back to another file as output.

When I open the output png file I realize that the transparency part that the input file has, is lost in the output file.

I tried using the resize method passing (200, 200, -100, -100) to ignore the z and c channels, but also passing (200, 200, -100, 4) to force someway the image to be 4 channels. In both cases it doesn't work.

Here my example source code:

```
const char *inFile = argv[1];
const char *outFile = argv[2];

//create base image loading from file
cimg_library::CImg<unsigned char> finalImg(inFile);
finalImg.resize(200, 200, -100, 4); //or finalImg.resize(200, 200, -100, -100);
    
//save the image
finalImg.save(outFile);
```

How can I solve this problem? What am I doing wrong?

Ciao.
![sfondo_trans](https://user-images.githubusercontent.com/19425083/56128003-cb218380-5f7e-11e9-885a-e5af5ad56392.png)

**Comment by dtschump** [comment]
Transparency in .png files is only handled if you link your code with `libpng`, i.e. define `cimg_use_png` before including `CImg.h`, and link with the necessary libraries `libpng and libz`.
Is it what you are already doing ?

**Comment by Magallo** [comment]
No, I didn't do that. I didn't know this. Is it written somewhere in the documentation? Now I will try and I'll let you know. Thanks for the moment.

**Comment by Magallo** [comment]
It works! Perfect! Thank you a lot! In any case I would suggest to add this kind of information in the somewhere documentation. Thanks again for the support!

**Comment by Magallo** [comment]
Just a question. What if I would like to implement a platform independent source code capable of being built and run both on Windows and Linux?
