### ISSUE TITLE
how to properly draw an image with transparency over another background image

### ISSUE THREAD

**Issue by Magallo** [dtschump/CImg#229]
Hi all,
in #228 I asked a question on handling properly png images considering also the alpha channel. The answer was good and I solved the problem (it's necessary to link libpng and libz and define cimg_use_png in the preprocessor definition).

However I still have some problems on properly manipulating images considering the transparency factor of them.

I have two images: one background image and one overlay image. The overlay image is a sort of logo with transparency. What I want is to load both the images in memory, then draw the overlay image over the background image preserving the transparency of the second one. With "preserving the transparency" I means that if one pixel of the overlay image is transparent, the result should be keeping the background pixel as it is. The background image is yellow and I would like is to mantain the yellow when the corresponding pixel of the overlay image is completely transparent.

I don't know how to achieve this. I am using the `draw_image()` method and I know that there is also a parameter called `opacity` that could be used and its default is 1 but I really don't know how to use it to achieve what I want. The documentation doesn't explain in detail its usage. I tried `opacity=1` and the effect is that the yellow is completely replaced by the transparent color of the overlay image. If I use zero instead of 1 the result is that the overlay image is completely ignored and the resulting image is identical to the background image. I know or I guess the solution is something related to this parameter, but I just can't realize how.

Please help.

Here below my code:

```
const char *bgrFile = argv[1];
const char *overFile = argv[2];
const char *outFile = argv[3];
    
//create base image loading from file
cimg_library::CImg<unsigned char> bgrImg(bgrFile);
    
//load overlay image from file
cimg_library::CImg<unsigned char> overImg(overFile);
       
//draw overlay over base image
int x = 0;
int y = 0;
bgrImg.draw_image(x, y, overImg, 1); //tried also '0' or '0xFFFFFF00' or something else without success
    
//save the image
bgrImg.save(outFile);
    
exit(0);
```

Here below my images (background and overlay) and the result I get using opacity=1

![sfondo_con_trans](https://user-images.githubusercontent.com/19425083/58246806-54835d00-7d58-11e9-872c-3a2d3ad011e7.png)

![logo_con_trans](https://user-images.githubusercontent.com/19425083/58246814-5b11d480-7d58-11e9-8fdf-061a5f3db93e.png)

![out](https://user-images.githubusercontent.com/19425083/58246822-5ea55b80-7d58-11e9-82d5-508691d88225.png)

**Comment by Magallo** [comment]
Anyone?

**Comment by hededesedede** [comment]
how did you impelement CImg to Visual Studio 2017?

**Comment by dtschump** [comment]
Here is one solution, with a RGB background, and a RGBA foreground.
Basically, you have to specify an opacity mask when using `CImg<T>::draw_image()`:
~~~~
#define cimg_use_png
#include "CImg.h"
using namespace cimg_library;

int main(int argc, char **argv) {

  const CImg<> bg("background.png"); // RGB image
  const CImg<> fg("foreground.png"); // RGBA image.

  const CImg<> fg_rgb = fg.get_shared_channels(0,2); // Only RGB part of the foreground.
  const CImg<> fg_a = fg.get_shared_channel(3); // Only Alpha part of the foreground.

  CImg<> result(bg);
  result.draw_image(30,30,fg_rgb,fg_a,1,255);

  (bg,fg,result).display();
}
~~~~
which leads to:
![cimg_alpha_drawing](https://user-images.githubusercontent.com/10114565/62687258-b8680a00-b9c6-11e9-88ab-ff79e2e9dfe6.png)
