### ISSUE TITLE
converting cv mat to cimg ? 

### ISSUE THREAD

**Issue by snnlsy** [dtschump/CImg#236]
I'm trying to convert cv mat image to cimg using function "_cvmat2cimg" but getting following 
error: ‘_cvmat2cimg’ was not declared in this scope _cvmat2cimg(im);

I put these on top the code: 
#include "CImg.h"
using namespace cimg_library;
#include "cvMat.h"
#define cimg_plugin1 "cvMat.h"
#define cimg_plugin_cvMat
#define cimg_use_opencv

How is the correct way of using this function?

**Comment by aalbiol** [comment]
Below you can find an example using cvMat.h plugin.
The order of defines and includes IS IMPORTANT.
1.- OpenCV headers
2.- #define cimg_plugin "cvMat.h"
3.- #include<CImg.h>
// Example to illustrate

//    Conversion CIMG <--> OpenCV using plugin cimgcvMat.h


#include <iostream>

// It is important to include opencv headers before CImg.h
#include <opencv2/core.hpp>

#define cimg_plugin1 "cvMat.h"
#include <CImg.h>

using namespace cv;
using namespace cimg_library;


int main( int argc, char** argv )
{

//Read CIMG Image
	CImg<unsigned char> cimg( argv[1] );


//Create an OPENCV copy	from CIMG
	Mat cv_image = cimg.get_MAT();

// Convert to CIMG from OPENCV
	CImg<unsigned char> cimg2(cv_image);

	return 0;
}
