### ISSUE TITLE
Reading RGB565 image gives wrong output.

### ISSUE THREAD

**Issue by bodzio131** [dtschump/CImg#238]
Hi,
CImg reads 16bit RGB565 BMP files and makes some unexpected changes in them. Tried with latest CImg, no changes in configuration except disabled OpenMP.

Steps to reproduce:
- open gimp, create 1x1 image with 0x**19**0000 background color, export it as 16bit RGB565 BMP
- load this file with CImg and save as another file (tried BMP and PNG)
- open this second file and check that this is 1x1 image with 0x**18**0000 color

Is there a way to solve this problem?

EDIT: no need to save it, just load image and check *data(0, 0, 0, 0) for mentioned input file.

Best regards,
Bogdan

**Comment by dtschump** [comment]
Confirmed. I'll try to fix that ASAP. Thanks for reporting!

**Comment by dtschump** [comment]
It seems that 16-bits BMP files were actually not read by CImg, but by the fallback method `CImg<T>::load_other()` , which is using `ImageMagick`'s convert to read the image.
It means that probably the reading bug is mainly in ImageMagick rather than CImg.
(Anyway, I have to fix CImg to make such BMP ready directly by CImg, not by `load_other()`).

**Comment by dtschump** [comment]
Thinking a bit about this...
If your image is encoded in RGB656, then it means you have 5 bits for Red, 6 bits for Green and 5 bits for Blue.
If you scale this in the usual [0,255] range, you won't be able to have a lot of different values:

For 5 bits : possible values are 0,8,16,24,32,40,48,56,64,72,80,88,96,104,112,120,128,136,144,152,160,168,176,184,192,200,208,216,224,232,240,248

For 6bits : possible values are
0,4,8,12,16,20,24,28,32,36,40,44,48,52,56,60,64,68,72,76,80,84,88,92,96,100,104,108,112,116,120,124,128,132,136,140,144,148,152,156,160,164,168,172,176,180,184,188,192,196,200,204,208,212,216,220,224,228,232,236,240,244,248,252

So, a color value of 0x19 = 25 cannot be represented accurately by 5 or 6 bits-encoded value, and there is a rounding occuring (ImageMagick says 24, which is correct in that case).

**Comment by bodzio131** [comment]
Sorry, I don't understand. 0x19 is 11001 binary so I assumed it is in 5 bits range (all the more that gimp saves/reads it without a problem). What is the "If you scale this in the usual [0,255] range" subject? please, could you provide more details or point me into some source to read about it?

**Comment by bodzio131** [comment]
Finally I found what mentioned possible values are. Still I don't know how gimp reads 0x19 from bitmap where is 0x18 written but it's not a CImg issue.
