### ISSUE TITLE
fftw_init_threads function is used even when "cimg_use_fftw3_singlethread" is defined

### ISSUE THREAD

**Issue by ShotaOchi** [dtschump/CImg#241]
If I understand correctly, we can define the macro "cimg_use_fftw3_singlethread" to avoid to use the multi-threaded routines of fftw.
However, fftw_init_threads function is used even when "cimg_use_fftw3_singlethread" is defined.
Thus, we have to enable threads even when we don't use multi-threaded routines of fftw.
Is this by design?

**Comment by ShotaOchi** [comment]
Is the struct "FFTW3_info" necessary even when we don't use the multi-threaded routines of fftw?
If not needed, the modification shown below seems good.

Line 3195-3202
```
#if defined(cimg_use_fftw3)
    struct FFTW3_info {
      FFTW3_info() {
        fftw_init_threads();
      }
    }; // struct FFTW3_info { ...
    static FFTW3_info _FFTW3_info;
#endif
```
Modified
```
#if defined(cimg_use_fftw3)
#ifndef cimg_use_fftw3_singlethread
    struct FFTW3_info {
      FFTW3_info() {
        fftw_init_threads();
      }
    }; // struct FFTW3_info { ...
    static FFTW3_info _FFTW3_info;
#endif
#endif
```

**Comment by dtschump** [comment]
Sound good indeed, I've done that : https://github.com/dtschump/CImg/commit/39215451d0b839b4e72d32afb15ea69701a7f4eb

**Comment by ShotaOchi** [comment]
Thanks!
Now, we can use CImg without enabling threads.
