### ISSUE TITLE
Keeping image's density during resize()

### ISSUE THREAD

**Issue by AzimovParviz** [dtschump/CImg#242]
For example, when resizing an image with density of 72x72, I end up with an image of density 1x1.
```
$ ./rez -i img/ay1.jpg -s 0.5 -o test.jpg
$ file test.jpg 
test.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 432x540, components 3
$ file img/ay1.jpg 
img/ay1.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, baseline, precision 8, 864x1080, components 3
```

**Comment by AzimovParviz** [comment]
I have another issue with CImg library, where on Mac OS X despite linking -lpng and -lz and setting up cimg_use_png 1, alpha channel in transparent png images is ignored. I suppose I am compiling something wrong, so advice is welcome.
```
clang++ -I .. -I /usr/local/X11/include main.cpp -Dcimg_use_png -O2 -L /opt/X11/lib -lX11 -lpthread -libpng -lz -ljpeg -o rez
```

**Comment by AzimovParviz** [comment]
```c++ -I /usr/local/X11/include main.cpp -Dcimg_use_png -L /opt/X11/lib -lm -lpthread -lX11 -lpng -lz -ljpeg -o rez```

transparency works as intended, still don't know about the density issue though

**Comment by dtschump** [comment]
The 'density' is not an information that is read and written by CImg. I think this is something related to the metadata of the image file, which is not something CImg manages at all.
