### ISSUE TITLE
segfault in warn function

### ISSUE THREAD

**Issue by Bho007** [dtschump/CImg#245]
I am getting a segfault from the warn function in CImg when it tries to call vsnprintf.

![debug](https://user-images.githubusercontent.com/43696503/74097831-9bbba480-4ac5-11ea-84d8-9495092694d2.PNG)

This is the debug output from CLion. And this is the code that runs save_png

```
void VideoDecoder::savePngToFile(HPicture *hPicture, char *destination) {
    auto pngPicture = PictureBuilder::makePngFromHPicture(hPicture);
    std::string fileName = destination;
    fileName.append(std::to_string(pngSequenceNumber));
    fileName.append(".png");
    pngPicture->save_png(fileName.c_str());
    delete pngPicture;
}
```

At the time of crash, fileName is "..\..\Images\0.png" and my exit code is -1073741819 (0xC0000005)

**Comment by dtschump** [comment]
No idea. Probably not CImg's fault.
