### ISSUE TITLE
[Suggestion] stop using FALSE in CImg.h to avoid a warning in R

### ISSUE THREAD

**Issue by ShotaOchi** [dtschump/CImg#246]
I'm a contributor of imager, which is an R package for image processing based on CImg.
We encounterd a warning to be fixed on windows.

> RcppExports.cpp: In function 'void R_init_imager(DllInfo*)':
> RcppExports.cpp:1769:35: warning: invalid conversion from 'int' to 'Rboolean' [-fpermissive]
>     R_useDynamicSymbols(dll, FALSE);

windows.h defines FALSE as int.
This confuses R_useDynamicSymbols function
because R_useDynamicSymbols function expects FALSE is Rboolean.
That's why we must undef FALSE in CImg.h.

The procedure is shown below.

1. replace FALSE with FALSE_windows in CImg.h
1. insert the lines in just below #include<windows.h>

```
#ifdef FALSE
enum {FALSE_windows = FALSE};
#undef FALSE
#endif
```

Is this modification acceptable to CImg?

**Comment by dtschump** [comment]
I've done that https://github.com/dtschump/CImg/commit/696d4dee8ca39bb20613a82f406a7bf15beb41c6

But I didn't have the opportunity to test it on Windows yet, I'll try this afternoon probably.

**Comment by ShotaOchi** [comment]
We must not define FALSE in CImg.h to avoid the warning in R.
https://github.com/dtschump/CImg/commit/696d4dee8ca39bb20613a82f406a7bf15beb41c6#diff-7550555384918401009ef5ecc22bec2aR62624-R62626

If FALSE should be defined in CImg.h, it's ok not to undef FALSE in CImg.h of this repository.
We will rewrite CImg.h in imager repository when updating CImg.h.

By the way, I suggest using appveyor to test CImg on windows.
MinGW and MSYS are preinstalled in some windows images of appveyor (Visual Studio 2013, Visual Studio 2015).
I think it's not difficult to use appveyor for testing CImg on windows.
