### ISSUE TITLE
Segmentation fault in CImg constructor

### ISSUE THREAD

**Issue by pfeatherstone** [dtschump/CImg#247]
The constructor ```CImg (const t *const values, const unsigned int size_x, const unsigned int size_y, const unsigned int size_z, const unsigned int size_c, const char *const axes_order)``` does not copy the data pointed to by ```values```. This causes a segmentation fault. If you're passing a const T* const, then the clue is that owernship of ```values``` is not transferred.

**Comment by dtschump** [comment]
Confirmed. Working on it.

**Comment by dtschump** [comment]
Found the bug, and a fix: https://github.com/dtschump/CImg/commit/a604ff515d6cb35008d44851222324295c0bebf4

**Comment by MBraedley** [comment]
Despite requesting this feature about a year ago, I've only just gotten around to using it recently (like, yesterday).  Was going to create a pull request since it's not in a release yet, but when I pulled the code, I saw it was already fixed.  When can we expect the next release?
