### ISSUE TITLE
jpeg support w/o external library?

### ISSUE THREAD

**Issue by forkjoseph** [dtschump/CImg#249]
It looks like any I/O operations related to JPEG require **external** library support.

`[CImg] *** CImgIOException *** [instance(1920,1080,1,3,0x5bc4000,non-shared)] CImg<unsigned char>::save_other(): Failed to save file '/tmp/frame.jpg'. Format is not natively supported, and no external commands succeeded.`

The docker container image that I use doesn't allow shared jpeglib installed because it's insanely huge. 

If your library relies everything on external libraries, what DOES your library do? Is this a simple wrapper? 
In the description, please change to "C++ **wrapper**" from "small and open-source C++ toolkit for image processing", since **ANY** image related operations use **external** libraries, unlike ImageMagick

**Comment by dtschump** [comment]
> If your library relies everything on external libraries, what DOES your library do? Is this a simple wrapper?

RTFM. CImg is an image processing library, not an image I/O library, although there are some I/O facilities for some formats (try definining `-Dcimg_use_jpeg` and link with libjpeg).
(start with https://en.wikipedia.org/wiki/Digital_image_processing and learn what image processing is).

> Thanks for wasting my 4 hours.
> (appeared in initial comment, has been edit afterward)

Just to be sure you understand : the four hours you spent are worthless from my point of view. Spending four hours to understand how CImg can read JPEG files proves even more that you are a dumbass.
