### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by tohuuduc** [dtschump/CImg#25]
Hello experts,
I just tried to include CImg in my code, however, I had the undefine reference error. 
First I downloaded CImg from website and unpacked.
In my code i included 

#include "CImg.h"
using namespace cimg_library;

And then compiled by cmake. it appears hundreds of error like : 

CMakeFiles/test1.dir/test1.cpp.o: In function `cimg_library::cimg::X11_info::X11_info()':
/usr/include/CImg.h:2526: undefined reference to `XInitThreads'
CMakeFiles/test1.dir/test1.cpp.o: In function `cimg_library::cimg::X11_info::~X11_info()':
/usr/include/CImg.h:2541: undefined reference to `XCloseDisplay'
CMakeFiles/test1.dir/test1.cpp.o: In function `cimg_library::CImgDisplay::screen_width()':

And the sumary is

collect2: error: ld returned 1 exit status
make[3]: *** [test/test1] Error 1
make[2]: *** [test/CMakeFiles/test1.dir/all] Error 2
make[1]: *** [test/CMakeFiles/test1.dir/rule] Error 2
make: *** [test/CMakeFiles/test1.dir/rule] Error 2

I found some others also have the same problem, but their solution require to provide link every compilation with g++.(and it does not work for my case).
I installed cimg-dev from ubuntu repository but, everything is still the same.

I also use Eclipse, and the GNU tool chains kit does not detect any undefined indexer (I added path to CImg folder). But it could not be compiled.

 Could you please tell me what to do?
Thank you very much.

**Comment by dtschump** [comment]
Two solutions:
1. Either you link your code with *-lpthread -lX11*
2. Either you deactivate the support of X11 (set by default in CImg) with *-Dcimg_display=0*.

**Comment by tohuuduc** [comment]
Thank you very much for your reply. Could you please tell me more on solution 1, if possible? I would like to link to that library to access all features. I have a quick search and found it is often linked during compilation.  Can I do it in preprocessing, e.g. by #include and #define...? I certainly don't want to retype link code every compilation.
