### ISSUE TITLE
draw_pixel problem

### ISSUE THREAD

**Issue by LightSN** [dtschump/CImg#252]
I'm trying to make a program that takes 3 numbers that represents r,g,b (from 0 - 255) and I got a problem. The draw_pixel function draws pixel and then erases it and color next pixel. How to make it not erase that pixel? Code \/

`
#include "CImg.h"
#include <iostream>
#include <fstream>
using namespace std;
using namespace cimg_library;

#ifndef cimg_imagepath
#define cimg_imagepath "img/"
#endif

int main(int argc, char** argv) {
	ifstream inp;
	inp.open("out.txt");

	
	cimg_usage("View the color profile of an image along the X axis");

	const char* file_i = cimg_option("-i", cimg_imagepath "parrot.ppm", "Input image");
	
	const double sigma = cimg_option("-blur", 1.0, "Variance of gaussian pre-blurring");

	const CImg<unsigned char> image = CImg<>(file_i).normalize(0, 255).blur((float)sigma).resize(-100, -100, 1, 3);

	CImgDisplay
		main_disp(image, "Not Important", 0),
		draw_disp(500, 500, "Color profile of the X-axis", 0);

	unsigned int hatch = 0xF0F0F0F0;
	const unsigned char
		red[] = { 255,0,0 },
		green[] = { 0,255,0 },
		blue[] = { 0,0,255 },
		black[] = { 0,0,0 };
	int dx = 0;
	int dy = 0;

	int r;
	int g;
	int b;
	
	while (!main_disp.is_closed() && !draw_disp.is_closed() &&
		!main_disp.is_keyESC() && !draw_disp.is_keyESC() && !main_disp.is_keyQ() && !draw_disp.is_keyQ()) {
		
		for (int i = 0; i < 10000; i++)
		{
			dx++;
			if (dx > 495)
			{
				dx = 0;
				dy++;
				if (dy > 498)
				{
					break;
				}
			}
			inp >> r;
			inp >> g;
			inp >> b;

			cout <<r<<" "<<g<<" "<<b<< endl;
			CImg<unsigned char>(draw_disp.width(), draw_disp.height()).
				draw_point(dx, dy, red, r).
				draw_point(dx, dy, green, g).
			    draw_point(dx, dy, blue, b).
				display(draw_disp);
		}
		cimg::wait(200000);
	}
	return 0;
}`

**Comment by dtschump** [comment]
`CImg<unsigned char>(draw_disp.width(), draw_disp.height()).
			draw_point(dx, dy, red, r).... ` is not a good idea.
You are re-creating a temporary image for each new iteration of your loop.
Solution : create the image once, before the loop:
~~~~
CImg<unsigned char> img(draw_disp.width(), draw_disp.height(),1,3,0);
~~~~
And then use `img.draw_point(..)...` inside the loop, to keep the previous pixel drawn on the image `img`.
