### ISSUE TITLE
Warning: memmove writing to an object of type with no trivial copy-assignment

### ISSUE THREAD

**Issue by ShotaOchi** [dtschump/CImg#260]
The following warning message was shown when compiling imager.
>    ../inst/include/CImg.h:61975:21: warning: ‘void* memmove(void*, const void*, size_t)’ writing to an object of type ‘struct cimg_library::CImgList<unsigned char>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
   61975 |         std::memmove(fonts,fonts + 1,15*sizeof(CImgList<ucharT>));
         |         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   ../inst/include/CImg.h:57038:10: note: ‘struct cimg_library::CImgList<unsigned char>’ declared here
   57038 |   struct CImgList {

The behavior of memset in this case is undefined because CImgList is not trivially-copyable.
That's why the warning should be fixed.

However, I don't know how to fix the warning.
I must remove draw_text function to retain imager package on CRAN if we can't fix the warning.
Would you mind helping us?

**Comment by dtschump** [comment]
OK, I'll see what I can do for that. Shouldn't be too hard to fix.

**Comment by dtschump** [comment]
Could you confirm the commit fixes the warning ?

**Comment by ShotaOchi** [comment]
Thank you for your quick response.

I confirmed the warning was fixed in develop branch.
