### ISSUE TITLE
What is the reference article for sharpen function?

### ISSUE THREAD

**Issue by ShotaOchi** [dtschump/CImg#261]
I received an e-mail that requested me to send him the journal article on which the implementation of imsharpen function of imager is based on.
imsharpen function of imager is a wrapper function of sharpen function of CImg.
That's why I want to know the reference article for sharpen function of CImg.

What is the reference article for sharpen function?

**Comment by dtschump** [comment]
depending on the mode you use for sharpening:
- `sharpen_type==false`, inverse diffusion. Not sure what reference is the best here, it's the most common way of sharpening images.
- `sharpen_type==true`, shock filters: https://epubs.siam.org/doi/abs/10.1137/0727053
