### ISSUE TITLE
isosurface3d could be more efficient

### ISSUE THREAD

**Issue by UlysseV** [dtschump/CImg#264]
While browsing the code of `isosurface3d()`, I noticed that the number of call to `func` could be reduced with a factor 4.
Indeed, calls to `func` are used to populate `values2` 4  cells at a time, while 3 of those cells already contain the proper data from previous iterations.
I created a local branch which implement a single `func` call data update, along with the required initialization (the first line and row of `values2` need to be pre-computed) that give the exact same result as the original implementation while being more efficient.

See pull request : https://github.com/dtschump/CImg/pull/263

**Comment by dtschump** [comment]
Looks interesting. I'll check that today.
A similar trick could be done also for the `isoline3d` function maybe ?

**Comment by UlysseV** [comment]
Yes, I just added that.

**Comment by dtschump** [comment]
Last modif won't compile (`;` missing). Could you fix that so that I can accept the PR?

**Comment by dtschump** [comment]
Nevermind, I'll do it myself. Thanks.

**Comment by dtschump** [comment]
After some testing, I found out that your patched version exhibits a different result on a simple test case. Could you check what is going wrong ?

The test case is:
~~~~
#include "CImg.h"
using namespace cimg_library;

int main(int argc, char **argv) {

  CImg<> img(32,32,32,1);
  cimg::srand(0UL);
  img.rand(-1,1).blur(3);

  CImgList<unsigned int> primitives;
  CImg<> points = img.get_isosurface3d(primitives,0);
  points.print("POINTS");

  return 0;
}
~~~~
If you look at the statistics of the `points` image, you will see that the mean and std values are different between the two versions of CImg.
The current version gives:
~~~~
mean = 15.5527, std = 8.94981
~~~~
while your patched version gives:
~~~~
mean = 15.5459, std = 8.9702
~~~~

Is there any kind of boundary effect maybe?

**Comment by UlysseV** [comment]
I'm looking into it.

**Comment by UlysseV** [comment]
Fixed (I was messing the initialization).

Do you have an equivalent test for `isoline3d` that I could run to check that all is fine ?

**Comment by UlysseV** [comment]
The new pull request : https://github.com/dtschump/CImg/pull/265

**Comment by dtschump** [comment]
This:
~~~~
#include "CImg.h"
using namespace cimg_library;

int main(int argc, char **argv) {

  CImg<> img(512,512,1);
  cimg::srand(0UL);
  img.rand(-1,1).blur(3);

  CImgList<unsigned int> primitives;
  CImg<> points = img.get_isoline3d(primitives,0);
  points.print("POINTS");

  return 0;
}
~~~~
It seems to work OK (no differences visible so far) for `isoline3d()`.
Also, I've backported your changes directly to the `develop` branch, hence I'll probably won't accept the PR as it is. Anyway, I'd like to add your name to the contributor list if you wish ?

**Comment by UlysseV** [comment]
OK, with great pleasure.

**Comment by dtschump** [comment]
Which name should I use?

**Comment by UlysseV** [comment]
Ulysse Vimont

**Comment by UlysseV** [comment]
Note that I did that while working for a company named Anatoscope, maybe you could add my affiliation ?

**Comment by dtschump** [comment]
No problem. 
Also, if you run into Emmanuel Prados, give him a hug for me :)

**Comment by UlysseV** [comment]
Sure thing :)

I enjoy his conferences very much.
