### ISSUE TITLE
isosurface3d could be more generic

### ISSUE THREAD

**Issue by UlysseV** [dtschump/CImg#267]
Following recent work I did on isosurfacing with CImg, it occurred to me that the output storage are unnecessarily imposed on the user.
This forces the user to copy all data from `primitives` and the return value of `isosurface3d()` to her custom 3D mesh model.

Instead, it would be possible to pass `addVertex` and `addFace` functors to `isosurface3d()` and let the user populate its custom mesh structure directly.
Those functors could have default values that populate a 3xN `CImg` and a `CImgList` to mimic the current behavior.

Is this feature interesting to the target audience of CImg ?
If yes, I can implement it in a pull request.

**Comment by dtschump** [comment]
Yes, it could be interesting, at the condition we keep a version of the function that is working exactly the same as the current one.
I'd be interested by a PR against the `develop` branch is possible, this time :)

**Comment by UlysseV** [comment]
OK, I'll work on that.
