### ISSUE TITLE
Alpine Linux?

### ISSUE THREAD

**Issue by Nakilon** [dtschump/CImg#271]
It says

> highly portable. It fully works on different operating systems

But I can't find it:

https://pkgs.alpinelinux.org/packages?name=*cimg*&branch=edge
https://repology.org/project/cimg/versions

I need it to install a Ruby gem into a small Docker image.

**Comment by dtschump** [comment]
Providing a package of CImg for all flavors of Unix/Linux and OS is not our mission, but that of the packagers of your distribution.
Please open a ticket there if you need a packaged version of CImg for a specific distribution.
Anyway, installing CImg doesn't require much more than copying the `CImg.h` file somewhere on your disk
(You will find it in our portable .zip archive provided on our website).

**Comment by Nakilon** [comment]
Yeah, I found that some guys here

https://github.com/simplyboo6/VimturBase/blob/41dbc1740d8e7399d29fff432a9a3f3600dfccac/Dockerfile

and here

https://github.com/x0rzkov/dockerfiles-dataset/blob/4b19cb1db0a1276e93151e3ea0f494f32895f896/hub.docker.com/simplyboo6/vimtur/Dockerfile

were just copying the `Cimg.h` and I tried to do similar thing but does not yet work for me:

```
/ # ls -l pHash/third-party/CImg
total 3860
-rw-r--r--    1 root     root       3952555 Jul 25 07:13 CImg.h
```
```
PKG_CONFIG_PATH=pHash/third-party/CImg gem install phamilie
```
```
fingerprint.cpp:61:10: fatal error: CImg.h: No such file or directory
```

**Comment by Nakilon** [comment]
Gave up with `PKG_CONFIG_PATH` and `/ # ln -s /pHash/third-party/CImg/CImg.h /usr/include/CImg.h` did the trick.
