### ISSUE TITLE
CeCILL-C license paragraph 3.2 requires to get license acceptance before download

### ISSUE THREAD

**Issue by rrm151** [dtschump/CImg#278]
License Paragraph 3.2
One copy of the Agreement, containing a notice relating to the characteristics of the Software, to the limited warranty, and to the fact that its use is restricted to experienced users has been provided to the Licensee **prior** to its acceptance as set forth in Article 3.1 hereinabove, and the Licensee hereby acknowledges that it has read and understood it.

My interpretation is that CImg website should present the license and require user acceptance _before_ allowing download of the software package.

If the CImg team has a different interpretation which would allow for acceptance _after_ download or running, could you please share that with me.  My product includes CImg and I do not wish to demand that my customers agree to the CeCILL-C license before they can purchase it.

**Comment by dtschump** [comment]
I don't think that's necessary. The paragraph 3.2 simply states that the user of CImg, the licensed library (in this case, the user is the developer of your software) agrees to comply with the CeCiLL license from the moment he downloads the library. 
It is written this way to give the starting time from which the terms of the licence must be complied with.

The user of the software is not concerned by the acceptance of the CeCiLL license, as the license terms have been already accepted by the software developer, and are already respected when the piece of software is run.

**Comment by rrm151** [comment]
Thank you so very much for your response dtschump.  I can easily see that perhaps the _intent_ of the CeCILL license was to make this relevant to the developer only, and not the end user.  Since you are identified by github as the repository owner, your comments will be quite helpful for me in convincing my team that in the case of CImg we do not need to worry about this particular aspect of the license. 

In case you might be at all interested, after initial discussion with the FOSS experts at my company, _we_ came to the conclusion that a strict reading requires that the license must be presented prior to downloading, loading, running, or shipping.
With the **assumption** that "has been provided" is the French to English conversion of "must be provided" . . . 
- Para 3.2 states that a copy must be provided prior to acceptance.
- Acceptance is defined in para 3.1, parts i and ii
- Part i covers downloading and loading.
- Part ii covers "exercises any rights".
- Rights is anything in section 5 "Scope of Rights Granted".
- Section 5.1 item 2 then would add "running" to the list of applicable situations, and this would certainly apply to the end user.
- Section 5.3 provides for the right to "transmit" or ship the software (or end product containing the software).

Fortunately, your helpful reply in a public forum will allow me to ship the CImg library without worry on the above issue.
It probably seems like a very small issue to you, but believe me when I state again that I am **very** grateful for your response.
