### ISSUE TITLE
What file formats are supported?

### ISSUE THREAD

**Issue by logixoul** [dtschump/CImg#294]
I checked here:
https://cimg.eu/reference/group__cimg__files__io.html
But the page isn't very clear. I'd like to skip the ImageMagick dependency, since it's pretty large (I need just the "loading" part, not the "image processing" part). Can I get a wide spectrum of format support, without large dependencies?

I know I can make CImg use libjpeg, libpng, libtiff. Any other such formats with "lightweight" support in CImg?

**Comment by dtschump** [comment]
Basically:

- Supported file formats that do not require 3rd-party libraries:
  * bmp
  * pnm (i.e. pgm, ppm and pfm)
  * asc (ascii format)
  * inr (inria binary format)
  * dlm (matlab ascii format)
  * pan (pandore binary format)
(those formats do not require complicated reader/writer, so CImg already contains the code to handle those).

- Common file formats supported by linking against a 3rd-party library:
  * jpeg (link with libjpeg)
  * png (link with libpng)
  * tiff (link with libtiff)
  * exr (link with openexr)
  * mnc (link with libminc2)

**Comment by logixoul** [comment]
Ah, so not a huge bunch of formats. Thanks!

I'll probably go for OpenImageIO, but I do admire the design goals of CImg!
