### ISSUE TITLE
Abandoned members

### ISSUE THREAD

**Issue by youngquan** [dtschump/CImg#30]
I have found that I can not use image.dimx() and visu.display() any more.
How can I know that some members has been abandoned ? And how can I get the members that have the same function?

**Comment by dtschump** [comment]
I think these members have been dropped like ten years ago, so I'm a bit surprised :)
Anyway, `visu.width()`, `visu.height()`, `visu.depth()`, `visu.spectrum()` replace the (very) old
`visu.dimx()`, `visu.dimy()`, `visu.dimz()` and `visu.dimc()`.

`visu.display()` is still working by the way.

**Comment by youngquan** [comment]
Sorry, I am just starting to use this library.I just copied the code in the pdf. I will see the Tutorial on the website.Thanks for your response.
