### ISSUE TITLE
Please fix cmd typos in "CImg Library Overview". 

### ISSUE THREAD

**Issue by mxiey2k** [dtschump/CImg#301]
In CImg Library Overview Section (https://cimg.eu/reference/group__cimg__overview.html),  there are some typos in the command line related to filenames (Used hello_word instead hello_world), would you please fix them? (I have put [] around the place that need to be corrected). Otherwise the compiler would throw out error messages.

------------------------------------------------------------------------------
  g++ (MingW windows version) : Use the following command to compile a CImg-based program with g++, on Windows :
g++ -o [hello_word.exe] [hello_word.cpp] -O2 -lgdi32

g++ (Linux version) : Use the following command to compile a CImg-based program with g++, on Linux :
g++ -o [hello_word.exe] hello_world.cpp -O2 -L/usr/X11R6/lib -lm -lpthread -lX11

g++ (Solaris version) : Use the following command to compile a CImg-based program with g++, on Solaris :
g++ -o [hello_word.exe] hello_world.cpp -O2 -lm -lpthread -R/usr/X11R6/lib -lrt -lnsl -lsocket

g++ (Mac OS X version) : Use the following command to compile a CImg-based program with g++, on Mac OS X :
g++ -o [hello_word.exe] hello_world.cpp -O2 -lm -lpthread -I/usr/X11R6/include -L/usr/X11R6/lib -lm -lpthread -lX11
------------------------------------------------------------------------------
    Thanks a lot!

**Comment by dtschump** [comment]
Fixed. Thanks for the report.
