### ISSUE TITLE
NaNs are shifted in blur_median()

### ISSUE THREAD

**Issue by pentekq** [dtschump/CImg#304]
Dear David,

It looks that NaNs are not properly handle in blur_median(). 
Here is a comparison of 3 median filters with a kernel radius of 3 pixels applied on a 32-bits 36x39 float image:

![Nan-in-median-filter_comparison](https://user-images.githubusercontent.com/31826731/104043831-ad796080-51dc-11eb-804b-e3c67d3b1f62.png)

Black pixels are NaNs.
If we look in the yellow box which discards a 3 pixel thick border, all methods behave roughly the same for the filtering part, however the Cimg method shifts the NaNs to the lower right corner. 

Would it be possible to ignore NaNs in blur_median() ?

**Comment by dtschump** [comment]
Hello.
I would say that any kind of image processing involving NaNs is a bit risky. If you are using NaN to specify e.g. masked pixels, I would suggest something like:
~~~~
  CImg<> mask(img.width(),img.height(),1,1,0);
  cimg_forXY(mask,x,y)
    if (cimg::type<float>::is_nan(img(x,y))) {
      mask(x,y) = 1;
      img(x,y) = 0;
    } else ++img(x,y);

  CImg<> potential = mask.get_distance(0)*=-1;
  img.watershed(potential);  // Reconstruct interior of NaN regions.

  img.blur_median(7); // Blur image.

  cimg_forXY(mask,x,y) if (mask(x,y)) img(x,y) = cimg::type<float>::nan(); // Put NaN back at mask locations.
~~~~
It first reconstruct the values of NaN pixels by propagating their valid (non-NaN) neighbors, then apply the median blur, and (optionally) put back the NaN values at their initial positions.

**Comment by pentekq** [comment]
This is a nice work-around, thank you !
