### ISSUE TITLE
Typo in documentation  load_tiff  cimg_use_tif

### ISSUE THREAD

**Issue by quimortiz** [dtschump/CImg#319]
In documentation of function load_tiff , there is a typo in the name of the precompilation directive.  (cimg_use_tif instead of cimg_use_tiff)

>     libtiff support is enabled by defining the precompilation  directive \c cimg_use_tif.

**Comment by svavs** [comment]
Typo still present here in the website documentation for [save_tiff](https://www.cimg.eu/reference/structcimg__library_1_1CImg.html#ab83b939646fe941ba22970fa1da76c9a).
