### ISSUE TITLE
missing #pragma warning(pop) ?

### ISSUE THREAD

**Issue by NiklasRosenstein** [dtschump/CImg#33]
I was only taking a quick look through the code. I couldn't find a matching `#pragma warning(pop)` for the opening `#pragma warning(push)` in line 112. Is that intended?

**Comment by dtschump** [comment]
No, this is probably a mistake.
Does commit https://github.com/dtschump/CImg/commit/48c30f49597c8900d9eb5b5c45faa9a290b2e54c reasonably fix this issue ? (I don't have Windows right now to test).

**Comment by NiklasRosenstein** [comment]
LGTM
