### ISSUE TITLE
dilate() / erode() crashes on Windows for large images

### ISSUE THREAD

**Issue by pentekq** [dtschump/CImg#342]
Hello,

The execution of the following code leads to a segmentation fault on windows (tested on 2 computers with Windows 10 and 11) but not Linux (Ubuntu 20.04):

```
cimg_library::CImg<unsigned char> img(50000,50000,1,1,255);
img.dilate(2);
```

The error appears in the dilate() function at line 37983 (cimg_version 291)
The same goes for the erode() function or when I change the image type to float. 
If I reduce the image size to img(40000,40000,1,1,255) everything goes well. I had enough available RAM in all my tests. Is there any reason that could explain this behavior?

**Comment by dtschump** [comment]
Thanks for reporting.
Does this happen also with the very latest version ? (3.1.0_pre033122).

**Comment by pentekq** [comment]
I'm not sure what you meant by 3.1.0_pre033122 version but I tested with the 3.1.0 (latest version on master and on develop) and yes I get the same error (line 39691)

**Comment by dtschump** [comment]
That is useful, thanks. At a first glance, I don't know what happens but I'll investigate.
When on Windows, what compiler did you use ?

**Comment by pentekq** [comment]
MSVC 14.26 (Windows 11) and MSVC 14.29 (Windows 10)

**Comment by dtschump** [comment]
Thanks. I confirm that.
I think I've found a fix : https://github.com/dtschump/CImg/commit/d0f152d53aff1d8cb002e05af7f13b93d6dce7e1
I've released a new version of the CImg package, with this fix included : https://cimg.eu/download (pre-release 040122)
Could you please test it and tell me if that solves your issue ?

**Comment by pentekq** [comment]
Your fix indeed solves this issue! Thanks a lot for your incredible responsiveness and for this great software !!
