### ISSUE TITLE
depth method always give me "1"

### ISSUE THREAD

**Issue by coderkan** [dtschump/CImg#35]
Hi everyone,

I have used CImg for reading images and displaying. I have actually successfull but I have some trouble about image depth. I have an image that color depth is 24. When I read this image with 
   
   CImg<unsigned char> image("lena.jpg");
   std::cout<< image.depth() << std::endl;

image.depth() always give me "1". 
Also I have tried different images and different depth images but result is always "1".
Has any idea about it?

Best Regards...

**Comment by dtschump** [comment]
`img.depth()` returns the number of slices for a 3d volumetric image. It does not return the number of bits used to store pixel values in the original file. So it's not the color depth.
To get the color depth, you have either : 
- To guess it from the values and dimensions you get when you read the image (by instance if you read it in a `CImg<float>` with values [0,255] with `spectrum()==3`, then you have an image with 8bits RGB = 24bits ).
- To read the color depth directly from the file header if you really mind about how the pixel values have been stored in your image file.

**Comment by coderkan** [comment]
Thanks for your quick reply.
I noticed that depth() is not color depth. I have  2 images. one has 24 bit color depth and another has 32 bit color depth. So both of them gives me spectrum() = 3 and values [0,255].
And how do I know image's header that reading CImg<float> image file.

**Comment by KirbX** [comment]
I have a problem that is nearly in the same vein : 
If i consider the fact that the spectrum is the number of channels in the image, if ```spectrum = 3``` i can use red, green, and blue values, 
basically : 
```            ret(i,j,1,0) = (int)round(red);
            ret(i,j,1,1) = (int)round(green);
            ret(i,j,1,2) = (int)round(blue); ```
?
Whenever I do this, i have a segfault on the ```ret(i,j,1,2)``` and i'm sure it come from the fact that i can't modify the 3rd channel.
Do you have an idea why? (if I remove this line, it works fine, but the image ret is too blue...)
Thanks!

**Comment by KirbX** [comment]
Maybe I found the problem. 
Once again, it's possible that with a 8000*4000, my computer isn't strong enough. I'll try to create 3 different functions and call them 1 by 1. :octopus:

**Comment by dtschump** [comment]
When you access the pixel values, you specify the `z` coordinate to be `1`, which is out-of-bounds for a 2D image. It should be `0` instead.
And, as it must be `0`, it can actually be ignored, so you can access your pixels like this :+1: 
    
    ret(i,j,0) = red; ret(i,j,1) = green; ret(i,j,2) = blue;

This is possible because the memory layout used by CImg to store the image pixel values allows that.

**Comment by KirbX** [comment]
Your help is Fast & Precious! Thx buddy :+1: :+1: It works perfectly now! :) continue like this!
