### ISSUE TITLE
the integration of Cimg in dev c++

### ISSUE THREAD

**Issue by xhelallikaj** [dtschump/CImg#36]
i am a total beginner student in image processing,and i ahve to do a project related to it,i chose Cimg as best library for it,but i wanted to know if just sending the header file here is all i need to do to integrate it,why is imageMagick++ also mentioned?
http://prntscr.com/9r0yqr

**Comment by dtschump** [comment]
ImageMagick can be used to help reading/writing compressed file formats (as JPEG, GIF, and so on...).
