### ISSUE TITLE
throws exception randomnly

### ISSUE THREAD

**Issue by ajavvadi** [dtschump/CImg#39]
I have a code which loads an image file, writes to a pixel in the image and saves the image.
Some pixels are written successfully. But sometime before the loop ends, CImg throws an exception,

*** cmg::fopen(): Failed to open file 'kalyan.bmp' wih mode 'wb'.

My code snippet is as follows:

void FrameBuffer::writePixelToImage(int x, int y, Color c)
{
	std::cout << "Kalyan! in writePixelToImage" << endl;

	string str = _filename;
	CImg <unsigned char> outPutImage;
	outPutImage.load(str.c_str());

	std::cout << "Kalyan! after loading in writePixeltoImage" << endl;
	std::cout << "x: " << x << " y: " << y << endl;
	
        outPutImage(x, y, 0, 0) = c.red;
	outPutImage(x, y, 0, 1) = c.green;
	outPutImage(x, y, 0, 2) = c.blue;

	std::cout << "Kalyan! after writing color in writePixeltoImage" << endl;

	outPutImage.save(str.c_str());
}

the writePixelToImage is called several times in a loop.

**Comment by dtschump** [comment]
Not sure what is happening.
It's a bit strange to load an image, change only a pixel and save it, and doing this in a loop.
Why not loading the image once, change all the pixels, then save the final result ? Is there a good reason ?
Anyway, it should work nonetheless, I'll give a try on my machine to see if I can reproduce the issue. On what OS are you running this code, which version of CImg ? Do you write your file on a remote file system (network?) ?

**Comment by ajavvadi** [comment]
Hey,

Yeah, it was a strange thought of me to implement it that way but yeah, I had to do it.
I posted the question in StackExchange and got a reply.

On topic: Consider what happens if a file write is delayed at the OS or drive firmware. You may have closed it, but is the file in a state where it can be reopened when your program swings around a few microseconds later? Some number of open-edit-write-closes could be bogged down in a buffer somewhere waiting for processing and the exception is a manifestation of the OS giving you the finger because the buffer is full. – user4581301

I tried doing what was suggested (waited for sometime before doing the next read) there and I didn't get an error. I think what he pointed out was true. The buffer might be full, after all.

Thanks for the help!

**Comment by dtschump** [comment]
Ah that's interesting, thanks for the info :)
