### ISSUE TITLE
Change Log request

### ISSUE THREAD

**Issue by aalbiol** [dtschump/CImg#41]
I would find interesting to have a short summary of the main changes in CImg.h when a new stable version is released.
This way people could figure out if it is interesting for them to upgrade wait until a new release.

Thanks in advance

**Comment by dtschump** [comment]
That's right Antonio. I don't write Changelogs for CImg (I don't have time for this unfortunately).
A good overview of some new features can be seen in the Changelog of the G'MIC project, as the project  has a direct use of the CImg functions : https://discuss.pixls.us/t/release-of-gmic-1-6-9
