### ISSUE TITLE
Cimg library installation

### ISSUE THREAD

**Issue by zboo** [dtschump/CImg#44]
I am trying to use your library to work on DICOM data. I am a beginner in C++ program and tried to follow this guide [http://alexandre-laurent.developpez.com/tutoriels/c-cpp/installation-et-configuration-d-une-bibliotheque/](url) to install your library but I don’t find any useful elements. Could you explain me how can I easily install your library? Particularly to load DICOM data? Actually I use MinGW compilator on windows using cmd terminal.
Thank you.

**Comment by WarHawk1** [comment]
I suggest you to first install  MinGW from here  http://nuwen.net/mingw.html  then again try to install CImg
