### ISSUE TITLE
save_tiff() having issues on 32 bit computer

### ISSUE THREAD

**Issue by bijjuair** [dtschump/CImg#45]
save_tiff() function when used with the cimg_use_tiff directive, ends up in writing an incorrect file format on 32 bit machines. When the file is opened in a tool like ImageJ, gives an error that the file is not in supported format. However it is working on a 64 bit machine. 

I am not sure what the cause of the problem is. Kindly help resolve the issue.

**Comment by dtschump** [comment]
Hi.
We use the bigtiff format by default to save tiff files, which may explain this problem.
I've just committed a change to disable bigtiff when used on 32bits systems.
Could you try to get the latest repo version, and tell me is that fixes your problem ?

I've tested on a 32bits virtual machine, and save/reloading a tiff file works (but I don't have ImageJ to test more thoroughly).

**Comment by bijjuair** [comment]
Thanks. It works now.

PS: I love to code with CImg :)
