### ISSUE TITLE
Drawing a black rectangle over an image makes it brighter

### ISSUE THREAD

**Issue by groznny** [dtschump/CImg#46]
I'm trying to make an elliptical cropper, but when I draw something over an image with a color darker than {40, 40, 40}, it makes the rest of the image go brighter, and I don't know why. Do you have any ideas why this could be happening? Thanks

**Comment by dtschump** [comment]
No idea.
Did you display it in a normalized display maybe (instance of `CImgDisplay` with `normalization_type` different from 0 ?).
That typically looks like a normalization automatically done by the display class, but I may be wrong.

**Comment by shimpe** [comment]
Just a stupid suggestion: maybe it's an optical illusion? Have you actually verified that the gray values of the rest of the image actually change? There are many illusions related to light/dark colors, see e.g. https://en.wikipedia.org/wiki/Checker_shadow_illusion
