### ISSUE TITLE
Modification of Voxel values using load_medcon_external fonction to load DICOM data

### ISSUE THREAD

**Issue by zboo** [dtschump/CImg#48]
I tried to load a dicom image on my c++ program using this library but after validation voxel values has been modified. The range of the loaded image was {0,2800} instead of {-1000,2000}.
I did not found where the modification of the value is done. Indeed medcon program do not modify the voxel values.
Does anybody have an idee to load DICOM data without modification on a c++ program? The range of the voxel values is very important for medical analysis.

Thanks

**Comment by dtschump** [comment]
Hello. Is it possible to get the dicom file ? This would help to reproduce the issue and try to understand what is going on.
Thanks.

**Comment by zboo** [comment]
Thanks for your help, I'll give you the DICOM image on your email
