### ISSUE TITLE
Loading a jpeg image can leak the open file descriptor.

### ISSUE THREAD

**Issue by BevapDin** [dtschump/CImg#49]
Loading a jpeg (via libjpeg) basically does this:
```C++
struct jpeg_decompress_struct cinfo;
if (setjmp(jerr.setjmp_buffer)) { // JPEG error
    throw CImgIOException( ... jerr.message ... );
}

std::FILE *const nfile = file?file:cimg::fopen(filename,"rb");

jpeg_create_decompress(&cinfo);
// many calls to jpeg functions
CImg<ucharT> buffer(cinfo.output_width*cinfo.output_components);
assign(cinfo.output_width,cinfo.output_height,1,cinfo.output_components);
// more calls to jpeg functions
```
If some libjpeg function after `setjmp` fails, execution jumps back to `setjmp`, goes into the branch and throws the exception. The opened file is not closed and the FILE pointer `nfile` is effectively lost and *never* closed. This can probably be triggered by a faulty image file.

Similar leak happens when `buffer` is created and can not allocate enough memory. It throws from `operator new`, but `nfile` is not closed. The same happens when `assign` is called (which allocates memory for the whole image) and it fails to allocate the memory.

The issues can be triggered when a program has already allocated nearly all available (virtual) memory and tries to load a huge (according to its dimensions) image. Either allocation inside of libjpeg fails and jumps back to `setjmp`, or the constructor of `buffer` / call to `assign` fails and throws. Those exceptions were caught by my program and execution continued as it should. But later, any attempt to open a file failed because the program had reached the maximal amount of open file handles.

There may be other calls in that function that can throw.

----

Suggestion to solve the issue:
1. Move the opening the file (and definition of `nfile`) before the call to `setjmp` and close the file (if needed) in the branch right before throwing (fixes leak when libjpeg jumps back).
2. Add a simple wrapper class that automatically closes the file handle and create an instance of that class on the stack. (Maybe just `std::unique_ptr` with a specific deleter function that calls `fclose`.) This would close the file automatically upon any throwing (fixes leak from throwing constructor).

----

`_load_png` seems handle the `setjmp` related issue correctly (it closes the file when `setjmp` returns true). However, it contains a few calls to `new`, which may throw, and will *not* close the file when that happens. So there is a leak as well.

**Comment by dtschump** [comment]
Thanks for noticing this.
Commit : 
https://github.com/dtschump/CImg/commit/dd9e892f5de6f778195d9683bd2ed4e6ff2d32f6

should fix this issue.

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/CImg/commit/f0c92bad2c5626732da50b602be45c6218a445eb does the same for _load_png.
Thanks again for your detailed bug report.
