### ISSUE TITLE
FFT with fftw3

### ISSUE THREAD

**Issue by uxhub** [dtschump/CImg#51]
Hello everyone,

It is not an issue, but I would like to understand how works FFT in CImg, especially with fftw3.
Since I am concerned about performance I've test how scales the time consumption with 3d images dimension.

That's what I measured with #define cimg_use_openmp:
```
[64x64x64]
FFT forward
time: 0.01979
FFT backward
time: 1.12188

[128x128x128]
FFT forward
time: 0.169748
FFT backward
time: 1.24596

[256x256x256]
FFT forward
time: 3.53858
FFT backward
time: 5.44005

 [512x512x512]
FFT forward
time: 37.2164
FFT backward
time: 44.6921

[1024x1024x1024]
FFT forward
time: 438.787
FFT backward
time: 475.132
```

That's what I measured with #define cimg_use_openmp and  #define cimg_use_fftw3:
```
[64x64x64]
FFT forward
time: 0.036742
FFT backward
time: 0.032864

[128x128x128]
FFT forward
time: 0.507304
FFT backward
time: 0.478217

[256x256x256]
FFT forward
time: 5.61296
FFT backward
time: 5.07032

[512x512x512]
FFT forward
time: 44.0638
FFT backward
time: 41.7231

[1024x1024x1024]
FFT forward
time: 337.529
FFT backward
time: 333.753
```

It's not obvious that fftw3 improves performances, especially for small images. Should it ? What should I know about it ?

Sorry if it's not the right place to post this message... but I don't know where it has to be else.

note: times are in sec
note: I compiled fftw with3.3.4 --enable-openmp --with-combined-threads options

**Comment by dtschump** [comment]
To me, the main advantage of using fftw3 is mostly that you can work with any image size you want. You are not forced to deal with images with a 2^N size along all the axes. This is really nice, and the 'CImg-only' implementation of the FFTW does not allow that unfortunately.
Also, the CImg implementation does not (yet) use any of the OpenMP feature, so it compute the FFT with a single thread. That is something I may change in the future anyway.
As the FFTW3 implementation is probably a lot more complex than mine, I'm not surprised the timing are a bit slower for small images. If I add the OpenMP directive to the current CImg-only implementation of the FFT, no doubts we'll be even faster.

**Comment by dtschump** [comment]
Well, I've done some quick tests, including OpenMP directives to the CImg-native implementation of the FFTW. We do not gain much except for quite big images (a few ms for images >6000x6000).
I'm not sure it's worth the overhead.

**Comment by uxhub** [comment]
I agree for free prime size of arrays. But, I read on fftw webpage "FFTW," which stands for the somewhat whimsical title of "Fastest Fourier Transform in the West." So I thought FFTW was the fastest implementation (and so parallel) I can find (on cpu). 
If a single thread  CImg-only implementation is quicker for 512^3 3D-image... I don't see the point.

Strange that you can't gain much time with open directives in cimg implementation since FFT is fully parallelizable, no ? (I think about the cufft performance, the cuda fft library for gpu).

**Comment by dtschump** [comment]
Yes, this is fully parallelizable, *but* the operations involved in the XYZ loops are so simple that parallelizing the loops using OpenMP is only valid for very large dimensions, otherwise the cost of creating, running the threads and waiting for them is higher than the gain you get.
That's the point with most parallelized operations using OpenMP. In CImg, we have some conditions on the minimal size of the image data before OpenMP is actually used.

**Comment by uxhub** [comment]
Yes I understand. Could I test your openmp directives for cimg-fft for higher 3-dimensions data ?
fftw takes the advantage over the cimg-fft at 1024x1024x1024, so your new directives may be relevant at this point.
Well, I'm curious to know how gpu implementation could be more efficient in this case since gpu card can't load much memory and so process small blocks....

**Comment by dtschump** [comment]
The difference between OpenMP and GPU parallelization is that with OpenMP you often parallelize outer loops that run for many iterations, while I see GPU code more as parallelization of 'inner' operations. But I may be wrong, I'm not a GPU expert.

**Comment by dtschump** [comment]
Also, to force OpenMP to be used in the FFTW, just add the directive : 

    #pragma omp parallel for collapse(2)

in file `CImg.h`, function `static void CImg<T>::FFT(..)` just before the loops

     cimg_forYZC(real,y,z,c) { ... } (for the x-axis, and so one for the other axes).

**Comment by uxhub** [comment]
Ok I will have a try.

But, I don't understand why you want to put openmp directives in the FFTW call in cimg.h code since FFTW procedure are already parallelized.
Don't you want to parallelize native cimg-FFT implementation instead ?

**Comment by dtschump** [comment]
Using OpenMP in FFTW-based implementation is useless of course, I didn't say you should try this :) 
OpenMP directives should be added to the CImg-native part only to have sense.
For your edit2 : I've no idea if this the 2d transform is faster than calling multiple 1d transform in fftw.

**Comment by uxhub** [comment]
Sorry I miss read. And I made an huge error this morning by measuring cpu time instead of real time...

So I compare here times for cimg only, cimg-openmp and cimg-fftw, and the results make sense this time. However, it could be nice to keep the openmp directives in cimg implementation... ;)

Thank you for your attention


```
CIMG ONLY
[64x64x64]      total: 0.059459
[128x128x128] total: 0.343971
[256x256x256] total: 7.162
[512x512x512] total: 74.3901
[1024x1024x1024] total: 886.168

CIMG + OPENMP
[64x64x64] total: 0.144665
[128x128x128] total: 0.147838
[256x256x256] total: 3.05347
[512x512x512] total: 23.5586
[1024x1024x1024] total: 236.439

CIMG + FFTW
[64x64x64] total: 0.0278749
[128x128x128] total: 0.231559
[256x256x256] total: 2.73878
[512x512x512] total: 21.415
[1024x1024x1024] total: 152.021
```
