### ISSUE TITLE
Non-free image data in CImg

### ISSUE THREAD

**Issue by lrineau** [dtschump/CImg#53]
In the file [`examples/img/CImg_demo.h`][f], there is at least one file that is non-free: the picture of Lenna (similar to [this one from Wikipedia](https://en.wikipedia.org/wiki/File:Lenna.png)).

[f]: https://github.com/dtschump/CImg/blob/f0c92bad2c5626732da50b602be45c6218a445eb/examples/img/CImg_demo.h

According to the Linux distribution Fedora, that sort of file cannot be shipped in Fedora. There is [an open bug about the subject][b].

[b]:  https://bugzilla.redhat.com/show_bug.cgi?id=1295246

I plan to repackage the tarball of CImg without `examples/CImg_demo.cpp` and the corresponding `CImg_demo.h`, but that would be a lot easier if that picture was not part of the distribution of CImg. Can you consider removing it from CImg, and distribute it by another way?

**Comment by lrineau** [comment]
Red testsuite: https://cgal.geometryfactory.com/CGAL/testsuite/results-4.9-Ic-18.shtml#Combinatorial_map

**Comment by dtschump** [comment]
I've removed the data for the "Lena" image, and all references to it have been replaced by another image (my own picture). I've released a new pre-release (1.7.1_pre041116) with the changes included.

**Comment by lrineau** [comment]
(For the records, that is commit 12973657144997a874a58d2f20e0432ad099f0b2.)

Great, thanks! I will trigger new builds at Fedora..
