### ISSUE TITLE
trying to use CImg to qnx platform

### ISSUE THREAD

**Issue by smratijohri** [dtschump/CImg#56]
hi,

i want to downscale my image(format = png). i found CImg and tried to use it for downscaling my image. 
it is giving me linker error for gdi32. i can link it on my desktop, but my target machine is a hardware which has QNX operating system. So, my question is, is it possible to use this library for qnx?
if yes, please guide me for the same.
Development environment:
1. i am using qt creator as an IDE, and MinGW compiler(it is default with qt but it doesnt have gdi32 library)
Or if you have anyother suggestion which can help me achieve my goal, please do direct me in that direction, i would be very grateful. please help its a little urgent.

thanks and regards

**Comment by dtschump** [comment]
I've never tried so I can't tell. 
You should try defining macro `cimg_display=0` when compiling, to disable display capabilities of CImg (which are probably not needed in your case).

**Comment by smratijohri** [comment]
hello,
yes i don't need any display capabilities, just need resizing of a bmp/png file.
thanks for this suggestion, can you please tell me how to define this macro as 0. will it be through code or by project properties.

regards

**Comment by dtschump** [comment]
Both options are possible.
Either add

    #define cimg_display 0

before including `CImg.h`, or set it in your project settings (I can't tell you exactly where it is, it depends on the compiler and IDE you are using).
