### ISSUE TITLE
Identify input bit-depth of image?

### ISSUE THREAD

**Issue by BillTavis** [dtschump/CImg#65]
Hello, 
I am loading .png files and storing them in a CImg<double>... however, I would like to be able to identify if these .png files are 16-bits per channel or 8-bits per channel. How can I do this?

**Comment by dtschump** [comment]
There is no 'clean' ways to identify such files with CImg. This information is probably readable from the file header itself. An alternative solution consists in reading the file and detecting if the max value is higher than 255 : 

    CImg<unsigned short> img("file.png");
    const bool is_16bits = img.max()>255;

It will only fails when your input image is 16bits *and* really dark (all values below 256), but that is not a common case.

**Comment by DmitriyVovk** [comment]
Hello, please help me. I never worked with c++ and classes. 
This library looking very simple to use, but i can't compile it.
It should be a sequence of  .png files.

Open "(1).png" . Read pixel values to some buffer.
Open "(2).png" . Read pixel values to this buffer. 
Open "(n).png" . Read pixels...
Stop opening if "(n+1).png"  does not exits.

**Comment by BillTavis** [comment]
@dtschump thanks for the response. That is how I've been doing it, but unfortunately I have run into that case where all values are below 255 even though it's 16-bits per channel. For now I will have it so the bit-depth is input manually.,, it would be a nice feature request to have automatic detection.

I should note that I've run into a similar problem with saving files. I am saving to .png and when the max is below 255 it defaults to 8-bits even though I want 16-bits. The reason I have these cases is that I am working with very long animation image sequences (too long to store in memory - the images are worked with one at a time sequentially) where sometimes there is a fade to/from black.

**Comment by dtschump** [comment]
Hello Bill. I better understand your concern now.
When you output a .png file with an explicit call to `CImg<T>::save_png()`, you can specify the number of bytes per channel you want to output, so you can force a 16bits output, as e.g: 

    CImg<unsigned short> img(320,200,1,3,0);
    img.rand(0,255);
    img.save_png("foo.png",2);  // Force output to be 16bits/channel

This is only working if you link your code with the `libpng` library (so you need to enable the macro `cimg_use_png` when compiling).

Also, I'll try to add an option soon in `CImg<T>::load_png()` to make it return the bit depth of the loaded image as well. I'll tell you when it's done, it shouldn't be so hard to do.

**Comment by DmitriyVovk** [comment]
Hey! What's going? My post was just deleted?! 
[https://new.vk.com/im?sel=256987572&z=photo59564200_419012509%2Fmail62008]

**Comment by dtschump** [comment]
@BillTavis , commit https://github.com/dtschump/CImg/commit/e999dad1f7fe54e39793d62beebc0ffe4aa67df7 should help. You can call the `CImg<T>::load_png()` method with an additional argument being a pointer to an `unsigned int`. The method will set the `unsigned int` to be the number of bits per pixel used in your original .png file. You can test it against `8` or `16` then to have an idea about the file format.
Let me know if that helps.

**Comment by dtschump** [comment]
@DmitriyVovk , apparently your post had nothing to do with the current thread.
If you have a specific question, please open a new entry/issue. Thanks.

**Comment by BillTavis** [comment]
thank you!! It works great, both opening and saving.

**Comment by dtschump** [comment]
Good news ! I close this issue then.
