### ISSUE TITLE
Im attempting to draw text directly onto a yuv buffer, is this possible

### ISSUE THREAD

**Issue by sgreaves1** [dtschump/CImg#69]
I convert yuv to rgb. and then place text on the image. and convert back. is there a way to do this without the converting as it is a lengthy operation? 

I know there is a load yuv from file but i already have the yuv buffer

**Comment by dtschump** [comment]
Well, are you using `CImg<T>::draw_text()` in this context ?
If so, `CImg<T>::draw_text()` is a colorspace-agnostic operation, so you can use it to draw a text in a yuv-encoded image without problems: just pass it the yuv color you want to use for your text.
Or maybe I've missed something ?

**Comment by sgreaves1** [comment]
Can confirm that this is possible. Thank you dtschump, that is very appreciated.

**Comment by Imjamper** [comment]
@sgreaves1 Hi, can you please provide a code example? Thanks.
