### ISSUE TITLE
Copy contents of CImg to another CImg without construction

### ISSUE THREAD

**Issue by normvcr** [dtschump/CImg#70]
If I have two 3-vectors
`CImg A(3), B(3);`
and want to copy whatever is in B over to A, how does one do that?  My understanding is that
`A = B;`
will first deallocate and then reconstruct A, before copying in the values of B.  A method like
`copyLeft(A,B)`
is what I have in mind, and will throw an exception if A is not the same dimensions as B.  This is consistent with assigning a scalar to a matrix
`A = 6;`
The matrix A is not deallocated/reconstructed before it takes on the new value(s).  Admittedly, the assignment cannot fail ...

**Comment by dtschump** [comment]
If the two images have the exact same number of values/pixels, then

    A = B

will copy the image content of `B` into `A` without reallocating memory. 
If `A` and `B` have different sizes, then of course, `A` is first deallocated and re-allocated with the size of `B`. In both cases,  `B` _is not_ deallocated. `A` becomes just a copy of `B`.

If you want to _transfer_ the content of `B` into `A`, you can use : 

   B.move_to(A);

instead. After that line, `B` is deallocated (so `B` becomes an empty image), and `A` is a copy of the old `B`.
