### ISSUE TITLE
Compilation errors with a test program.

### ISSUE THREAD

**Issue by indjev99** [dtschump/CImg#74]
I get these 3 compilation errors when compiling a simple program that just includes the header file:
In function 'FILE\* cimg_library::cimg::fopen(const char_, const char_)':
5065|error: '_fileno' was not declared in this scope
In function 'int cimg_library::cimg::fseek(FILE_, INT_PTR, int)':
5093|error: '_fseeki64' was not declared in this scope
In function 'INT_PTR cimg_library::cimg::ftell(FILE_)':
5102|error: '_ftelli64' was not declared in this scope

More detailed explanation: http://stackoverflow.com/questions/38402058/compilation-errors-with-cimg

**Comment by dtschump** [comment]
It seems this happens with some buggy (old) versions of C+ compilers when option `-std=c++11` is activated. Try removing it or replacing it with `-std=gnu++11` should fix the issue.

**Comment by indjev99** [comment]
Yeah, I tried that and it only fixes the first error. However, I haven't found a fix for the other two.
