### ISSUE TITLE
wrong argument value check in image multiplication operator

### ISSUE THREAD

**Issue by shimpe** [dtschump/CImg#75]
leading to exceptions where none are expected

**Comment by dtschump** [comment]
Image multiplication operator does not operate pixel by pixel, but corresponds to a **matrix multiplication**. To multiply two images together pixelwise, there are the `CImg<T>::mul()`  and `CImg<T>::get_mul()` methods.

**Comment by shimpe** [comment]
Ok thanks. I had misunderstood.


On Sat, Jul 23, 2016 at 6:10 PM, David Tschumperlé <notifications@github.com
