### ISSUE TITLE
Matlab ´improfile´ in CImg

### ISSUE THREAD

**Issue by SebastianBugna** [dtschump/CImg#83]
Hi eveyone

I´m implementing a video restoration algorithm in C++ which I already tested in Matlab.
I used Hough transform and improfile several times, in different stages of the algorithm.

Matlab ´improfile´s´ function gives the pixel-values along a line segment within an image, given the endpoints pixel coordinates xi, yi of the line segment.
like:
[cx,cy,c] = improfile(I,xi,yi)

I is the image, xi, yi the origin pixel yi the end pixel. 
c is the intensity profile of the line segment and cx, cy are the pixel coordinates in image I.

In OpenCV there´s an equivalent which is: LineIterator
http://docs.opencv.org/trunk/dc/dd2/classcv_1_1LineIterator.html

Is there any way to do this with CImg.

Thanks in advance

**Comment by dtschump** [comment]
There is a macro to do so: `cimg_for_lineXY()`, like this:

    k = 0;
    cimg_for_lineXY(x,y,10,10,300,200) {
       value[k++] = img(x,y);
   }
