### ISSUE TITLE
CImg doesn't compile if cimg_OS is defined to 0

### ISSUE THREAD

**Issue by Ecordonnier** [dtschump/CImg#87]
Unlike what the documentation is saying (http://cimg.eu/reference/group__cimg__environment.html), cimg_OS defined to 0 is not really an option at the moment, it will not compile, see for instance code in fdate:

```
 5209 #if cimg_OS==2
 5210       HANDLE file = CreateFileA(path,GENERIC_READ,0,0,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,0);
 5211       if (file!=INVALID_HANDLE_VALUE) {
 5212         FILETIME _ft;
 5213         SYSTEMTIME ft;
 5214         if (GetFileTime(file,0,0,&_ft) && FileTimeToSystemTime(&_ft,&ft))
 5215           res = (int)(attr==0?ft.wYear:attr==1?ft.wMonth:attr==2?ft.wDay:attr==3?ft.wDayOfWeek:
 5216                       attr==4?ft.wHour:attr==5?ft.wMinute:ft.wSecond);
 5217         CloseHandle(file);
 5218       }
 5219 #else
 5220       struct stat st_buf;
```

With cimg_OS being 0, "struct stat" will fail to compile since "sys/stat.h" will not be included.
I'm not sure whether CImg wants to support "cimg_OS==0", so maybe the fix would only be to change the documentation.

**Comment by dtschump** [comment]
You are right.
Commit https://github.com/dtschump/CImg/commit/154837fc586b0613b6b60021b9020a7edb6b4530 should fix this.

Thanks for the report.

**Comment by Ecordonnier** [comment]
Thanks!
