### ISSUE TITLE
Memory leak when using more than 16 font sizes

### ISSUE THREAD

**Issue by gilbertj** [dtschump/CImg#91]
In method 

`static const CImgList<ucharT>& font(const unsigned int font_height, const bool is_variable_width=true)
`
There is a cache of 16 most recently used fonts.  On using a 17th font size it clears the oldest entry in `static CImgList<ucharT> fonts[16]` but it doesn't appear to free any of the previously allocated memory for the font.

**Comment by dtschump** [comment]
That's right. Commit https://github.com/dtschump/CImg/commit/69a3ececb385d362a97c797e7df8b83ef7bca0ce should fix this issue. Thanks for your report!

**Comment by gilbertj** [comment]
Thanks for the quick fix it appears to have solved my issue.
