### ISSUE TITLE
bug in blur_box

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#92]
Hi David. The current version of blur_box has a bug: the following doesn't compile
```
#include <CImg.h>
using namespace cimg_library;

int main()
{
  CImg<double> im(10,10);
  im.blur_box(3.0,false);
  return 1;
}
```
I'm going to upload a pull request that fixes the issue later.

**Comment by dtschump** [comment]
That's right, `std::max()` must be replaced by `cimg::max()`.
I'll fix it.
