### ISSUE TITLE
bug in rotate

### ISSUE THREAD

**Issue by dahtah** [dtschump/CImg#93]
There's a small bug in the new rotate function: 
```

int main()
{
  CImg<double> im(10,10);
  im.rotate(12,0,0,1,1,0);
  return 1;
}

```

fails at compile time. Adding the following definition to CImg.h fixes it:

```
template<typename T1,typename T2>
    inline T1 mod(const T1& x, const T2& m) {
      const double dx = (double)x, dm = (double)m;
      return (T1)(dx - dm * std::floor(dx / dm));
      }
```

**Comment by dtschump** [comment]
It works for me? What kind of error do you get ? On which platform, which compiler ?

**Comment by dahtah** [comment]
./CImg.h:28896:19: error: call to 'mod' is ambiguous
              Z = cimg::mod(d2 + R(0,2)*xc + R(1,2)*yc + R(2,2)*zc,(floa...
                  ^~~~~~~~~
Ubuntu clang version 3.6.0-2ubuntu1

**Comment by dtschump** [comment]
I think https://github.com/dtschump/CImg/commit/c7bc545a0e8e5eb511eb210b28241010f2169e11 fixes this bug.

**Comment by dahtah** [comment]
Not quite. This does:
```
              X = cimg::mod((float) (w2 + R(0,0)*xc + R(1,0)*yc + R(2,0)*zc),(float)width()),
              Y = cimg::mod((float) (h2 + R(0,1)*xc + R(1,1)*yc + R(2,1)*zc),(float)height()),
              Z = cimg::mod((float) (d2 + R(0,2)*xc + R(1,2)*yc + R(2,2)*zc),(float)depth());
```
(twice, for cubic and linear) 
I can send you an updated pull request if that helps
