### ISSUE TITLE
"Good" plugins

### ISSUE THREAD

**Issue by Meekohi** [dtschump/CImg#98]
Is there any link to "good"/"tested" plugins? In particular I'm looking for a way to read video frames a bit faster than the "use ffmpeg to write .ppm files" or "use OpenCV which is a disaster in general" options ;D Might write something up myself if it doesn't exist yet.

**Comment by dtschump** [comment]
No, unfortunately. To my knowledge, there are no other CImg plug-ins than those distributed in the package.  I must admit I don't have issues with the use of OpenCV to read video frames (at least on Linux). I'm not aware of any other "easy-to-use" library for dealing with video files to be honest.
