### ISSUE TITLE
porting guide from version 1.5.2 to 1.7.8

### ISSUE THREAD

**Issue by HJarausch** [dtschump/CImg#99]
Hi,

is there an porting guide to help porting an application (here Photivo) from using CImg-1.5.2 to CImg-1.7.8.
E.g. blur_bilateral used to have 2 arguments (see example gmic) but has changed completely now.
Is there any documentation which helps porting Photivo and other software using CImg?

Many thanks for a hint,
Helmut

**Comment by dtschump** [comment]
No documentation, but I think this should be quite straightforward.
`CImg<T>::blur_bilateral()` has instead an addition first `guide` argument, but for a standard bilateral, just pass `*this`. Is there any other issue for the portage ? I could help you with this if you need.

**Comment by HJarausch** [comment]
On 10/31/2016 09:01:33 PM, David Tschumperl� wrote:
No documentation, but I think this should be quite straightforward.
CImg<T>::blur_bilateral() has instead an addition first  
<code>guide</code> argument, but for a standard bilateral, just pass  
<code>*this</code>.
Is there any other issue for the portage ? I could help you with this  
if you need.

Many thanks for this hint. With

sed -i -e  
's/CImage.blur_bilateral(Sigma_s,Sigma_r)/CImage.blur_bilateral(CImage,Sigma_s,Sigma_r)/'  
Sources/ptCimg.cpp

photivo compiles just fine.

I just wonder why you didn't overload blur_bilateral once more such  
that it adds the first argument  *this  if it is called
with only two parameters.

Regards,
Helmut
